[package]
name = "zrotext-delivery-store"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zrotext-domain = { path = "../domain" }
tokio-postgres = { version = "0.7.13", features = ["with-uuid-1"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
uuid.workspace = true
sha2 = "0.11.0"
thiserror = "2.0.20"
