// SPDX-License-Identifier: AGPL-3.0-only
/** Dormant historical integrity only. No storage, authority, custody or cryptographic writer. */
import {canonicalSignature02} from './draft02-manifest.js';
import {verifiedContactReaderStatementIdentity01, type VerifiedContactReaderStatement, type ContactReaderStatementIdentity01} from './contact-reader-statement.js';
const enc=new TextEncoder(),max=(1n<<63n)-1n;
const fieldNames=['kind','accountId','contactId','sealRevision','trustGeneration','manifestVersion','readerGeneration','readerId','manifestDigest','statementDigest','routingDigest','requestId','rootWriterId','encapsulation','ciphertext'] as const;
const mutationNames=['operation','accountId','contactId','expectedRevision','revision','requestId','previousDigest','trustGeneration','manifestVersion','manifestDigest','statementDigest','routingDigest','legacyGeneration','name','notes'] as const;
export type ContactSlot01=Readonly<{tag:0|1;sealRevision:bigint;digest:Uint8Array}>;
export type ContactFieldUnsigned01=Readonly<{kind:1|2;accountId:Uint8Array;contactId:Uint8Array;sealRevision:bigint;trustGeneration:1n;manifestVersion:bigint;readerGeneration:bigint;readerId:Uint8Array;manifestDigest:Uint8Array;statementDigest:Uint8Array;routingDigest:Uint8Array;requestId:Uint8Array;rootWriterId:Uint8Array;encapsulation:Uint8Array;ciphertext:Uint8Array}>;
export type ContactMutationUnsigned01=Readonly<{operation:1|2|3;accountId:Uint8Array;contactId:Uint8Array;expectedRevision:bigint;revision:bigint;requestId:Uint8Array;previousDigest:Uint8Array;trustGeneration:1n;manifestVersion:bigint;manifestDigest:Uint8Array;statementDigest:Uint8Array;routingDigest:Uint8Array;legacyGeneration:bigint;name:ContactSlot01;notes:ContactSlot01}>;
export type ParsedContactField01=ContactFieldUnsigned01&Readonly<{bytes:Uint8Array;unsigned:Uint8Array;signature:Uint8Array}>;
export type ParsedContactMutation01=ContactMutationUnsigned01&Readonly<{bytes:Uint8Array;unsigned:Uint8Array;signature:Uint8Array}>;
export type VerifiedHistoricalField=Readonly<{kind:'historical_integrity';entity:'field'}>;
export type VerifiedHistoricalMutation=Readonly<{kind:'historical_integrity';entity:'mutation'}>;
export type VerifiedHistoricalTransition=Readonly<{kind:'historical_integrity';entity:'transition'}>;
type FieldIdentity=ParsedContactField01&Readonly<{digest:Uint8Array}>;
type MutationIdentity=ParsedContactMutation01&Readonly<{digest:Uint8Array}>;
type BoundField={identity:FieldIdentity;statement:ContactReaderStatementIdentity01};
type BoundMutation={identity:MutationIdentity;statement:ContactReaderStatementIdentity01};
type BoundTransition=BoundMutation&{fields:readonly (BoundField|null)[]};
const fields=new WeakMap<VerifiedHistoricalField,BoundField>(),mutations=new WeakMap<VerifiedHistoricalMutation,BoundMutation>(),transitions=new WeakMap<VerifiedHistoricalTransition,BoundTransition>();
function fail():never{throw Error('Contact content refused');}
function same(a:Uint8Array,b:Uint8Array){return a.length===b.length&&a.every((v,i)=>v===b[i]);}
function bytes(v:unknown,n:number,zero=false):Uint8Array{if(!(v instanceof Uint8Array)||v.length!==n||!zero&&v.every(x=>x===0))fail();return Uint8Array.from(v);}
function object(v:unknown,names:readonly string[]):Record<string,any>{if(!v||Object.getPrototypeOf(v)!==Object.prototype)fail();const ks=Reflect.ownKeys(v);if(ks.length!==names.length||ks.some(k=>typeof k!=='string'||!names.includes(k)))fail();const r:Record<string,any>={};for(const k of names){const d=Object.getOwnPropertyDescriptor(v,k);if(!d||!Object.hasOwn(d,'value'))fail();r[k]=d.value;}return r;}
function integer(v:unknown,zero=false):bigint{if(typeof v!=='bigint'||v<(zero?0n:1n)||v>max)fail();return v;}
function u64(v:bigint){const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,v);return b;}
function u32(v:number){const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,v);return b;}
function join(...parts:Uint8Array[]){const b=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;for(const p of parts){b.set(p,at);at+=p.length;}return b;}
function buffer(b:Uint8Array){return Uint8Array.from(b).buffer;}
function owned<T extends object>(value:T):T{const r:Record<string,unknown>={};for(const[k,v]of Object.entries(value)){if(v instanceof Uint8Array){const b=Uint8Array.from(v);Object.defineProperty(r,k,{enumerable:true,get:()=>Uint8Array.from(b)});}else Object.defineProperty(r,k,{enumerable:true,value:typeof v==='object'&&v!==null?owned(v):v});}return Object.freeze(r)as T;}
function slot(v:unknown):ContactSlot01{const s=object(v,['tag','sealRevision','digest']);integer(s.sealRevision,true);s.digest=bytes(s.digest,32,true);if(s.tag===0){if(s.sealRevision!==0n||s.digest.some((v:number)=>v!==0))fail();}else if(s.tag===1){if(s.sealRevision===0n||s.digest.every((v:number)=>v===0))fail();}else fail();return s as ContactSlot01;}
function field(v:unknown):ContactFieldUnsigned01{const s=object(v,fieldNames);for(const k of ['accountId','contactId','requestId'])s[k]=bytes(s[k],16);for(const k of ['readerId','manifestDigest','statementDigest','routingDigest','rootWriterId'])s[k]=bytes(s[k],32);for(const k of ['sealRevision','trustGeneration','manifestVersion','readerGeneration'])integer(s[k]);if(s.trustGeneration!==1n||s.kind!==1&&s.kind!==2)fail();s.encapsulation=bytes(s.encapsulation,65);if(s.encapsulation[0]!==4||!(s.ciphertext instanceof Uint8Array)||s.ciphertext.length<17||s.ciphertext.length>(s.kind===1?272:2064))fail();s.ciphertext=Uint8Array.from(s.ciphertext);return s as ContactFieldUnsigned01;}
function mutation(v:unknown):ContactMutationUnsigned01{const s=object(v,mutationNames);for(const k of ['accountId','contactId','requestId'])s[k]=bytes(s[k],16);for(const k of ['manifestDigest','statementDigest','routingDigest'])s[k]=bytes(s[k],32);s.previousDigest=bytes(s.previousDigest,32,true);for(const k of ['revision','trustGeneration','manifestVersion'])integer(s[k]);for(const k of ['expectedRevision','legacyGeneration'])integer(s[k],true);if(s.trustGeneration!==1n)fail();s.name=slot(s.name);s.notes=slot(s.notes);if(s.name.sealRevision>s.revision||s.notes.sealRevision>s.revision)fail();if(s.operation===1||s.operation===3){if(s.expectedRevision!==0n||s.revision!==1n||s.previousDigest.some((v:number)=>v!==0)||s.operation===1&&s.legacyGeneration!==0n||s.operation===3&&s.legacyGeneration===0n)fail();}else if(s.operation===2){if(s.expectedRevision===0n||s.expectedRevision===max||s.revision!==s.expectedRevision+1n||s.previousDigest.every((v:number)=>v===0)||s.legacyGeneration!==0n)fail();}else fail();return s as ContactMutationUnsigned01;}
/** Synchronous framing only; curve/trust validation is separate. */
export function encodeContactFieldUnsigned01(input:ContactFieldUnsigned01){const s=field(input);return join(enc.encode('ZTCO'),Uint8Array.of(1,s.kind),s.accountId,s.contactId,u64(s.sealRevision),u64(s.trustGeneration),u64(s.manifestVersion),u64(s.readerGeneration),s.readerId,s.manifestDigest,s.statementDigest,s.routingDigest,s.requestId,s.rootWriterId,s.encapsulation,u32(s.ciphertext.length),s.ciphertext);}
export function encodeContactMutationUnsigned01(input:ContactMutationUnsigned01){const s=mutation(input),part=(v:ContactSlot01)=>join(Uint8Array.of(v.tag),u64(v.sealRevision),v.digest);return join(enc.encode('ZTCM'),Uint8Array.of(1,s.operation),s.accountId,s.contactId,u64(s.expectedRevision),u64(s.revision),s.requestId,s.previousDigest,u64(s.trustGeneration),u64(s.manifestVersion),s.manifestDigest,s.statementDigest,s.routingDigest,u64(s.legacyGeneration),part(s.name),part(s.notes));}
function signed(v:unknown,min:number,upper:number,magic:string){if(!(v instanceof Uint8Array)||v.length<min||v.length>upper)fail();const b=Uint8Array.from(v);if(!same(b.slice(0,5),join(enc.encode(magic),Uint8Array.of(1))))fail();const signature=b.slice(-64);if(!same(signature,canonicalSignature02(signature)))fail();return {bytes:b,unsigned:b.slice(0,-64),signature};}
export async function parseContactField01(input:Uint8Array):Promise<ParsedContactField01>{const p=signed(input,396,2443,'ZTCO'),b=p.bytes,v=new DataView(b.buffer),n=v.getUint32(311);if(b.length!==379+n)fail();const s=field({kind:b[5],accountId:b.slice(6,22),contactId:b.slice(22,38),sealRevision:v.getBigUint64(38),trustGeneration:v.getBigUint64(46),manifestVersion:v.getBigUint64(54),readerGeneration:v.getBigUint64(62),readerId:b.slice(70,102),manifestDigest:b.slice(102,134),statementDigest:b.slice(134,166),routingDigest:b.slice(166,198),requestId:b.slice(198,214),rootWriterId:b.slice(214,246),encapsulation:b.slice(246,311),ciphertext:b.slice(315,315+n)});await crypto.subtle.importKey('raw',buffer(s.encapsulation),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);return owned({...s,...p});}
export function parseContactMutation01(input:Uint8Array):ParsedContactMutation01{const p=signed(input,368,368,'ZTCM'),b=p.bytes,v=new DataView(b.buffer),sl=(at:number)=>({tag:b[at],sealRevision:v.getBigUint64(at+1),digest:b.slice(at+9,at+41)});return owned({...mutation({operation:b[5],accountId:b.slice(6,22),contactId:b.slice(22,38),expectedRevision:v.getBigUint64(38),revision:v.getBigUint64(46),requestId:b.slice(54,70),previousDigest:b.slice(70,102),trustGeneration:v.getBigUint64(102),manifestVersion:v.getBigUint64(110),manifestDigest:b.slice(118,150),statementDigest:b.slice(150,182),routingDigest:b.slice(182,214),legacyGeneration:v.getBigUint64(214),name:sl(222),notes:sl(263)}),...p});}
async function hash(b:Uint8Array){return new Uint8Array(await crypto.subtle.digest('SHA-256',buffer(b)));}
async function signature(p:{unsigned:Uint8Array;signature:Uint8Array},s:ContactReaderStatementIdentity01,domain:string){const key=await crypto.subtle.importKey('raw',buffer(s.rootPoint),{name:'ECDSA',namedCurve:'P-256'},false,['verify']);if(!await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,buffer(p.signature),buffer(join(enc.encode(domain+'\0'),u32(p.unsigned.length),p.unsigned))))fail();}
function scope(p:ContactMutationUnsigned01|ContactFieldUnsigned01,s:ContactReaderStatementIdentity01,contact:Uint8Array,routing:Uint8Array){if(!same(p.accountId,s.accountId)||!same(p.contactId,contact)||!same(p.routingDigest,routing)||p.trustGeneration!==s.trustGeneration||p.manifestVersion!==s.manifestVersion||!same(p.manifestDigest,s.manifestDigest)||!same(p.statementDigest,s.digest))fail();}
export async function verifyContactField01(input:Readonly<{bytes:Uint8Array;statement:VerifiedContactReaderStatement;expectedContactId:Uint8Array;expectedRoutingDigest:Uint8Array}>):Promise<VerifiedHistoricalField>{const i=object(input,['bytes','statement','expectedContactId','expectedRoutingDigest']),s=verifiedContactReaderStatementIdentity01(i.statement),contact=bytes(i.expectedContactId,16),routing=bytes(i.expectedRoutingDigest,32);if(!(i.bytes instanceof Uint8Array)||i.bytes.length<396||i.bytes.length>2443)fail();const b=Uint8Array.from(i.bytes),p=await parseContactField01(b);scope(p,s,contact,routing);if(p.readerGeneration!==s.readerGeneration||!same(p.readerId,s.readerId)||!same(p.rootWriterId,s.rootWriterId))fail();await signature(p,s,'ZT/contact-field/commitment/v1');const result=Object.freeze({kind:'historical_integrity' as const,entity:'field' as const});fields.set(result,{identity:owned({...p,digest:await hash(b)}),statement:s});return result;}
export async function verifyContactMutation01(input:Readonly<{bytes:Uint8Array;statement:VerifiedContactReaderStatement;expectedContactId:Uint8Array;expectedRoutingDigest:Uint8Array;expectedLegacyGeneration:bigint}>):Promise<VerifiedHistoricalMutation>{const i=object(input,['bytes','statement','expectedContactId','expectedRoutingDigest','expectedLegacyGeneration']),s=verifiedContactReaderStatementIdentity01(i.statement),contact=bytes(i.expectedContactId,16),routing=bytes(i.expectedRoutingDigest,32),legacy=integer(i.expectedLegacyGeneration,true),p=parseContactMutation01(i.bytes);scope(p,s,contact,routing);if(p.legacyGeneration!==legacy)fail();await signature(p,s,'ZT/contact-field/mutation/v1');const result=Object.freeze({kind:'historical_integrity' as const,entity:'mutation' as const});mutations.set(result,{identity:owned({...p,digest:await hash(p.bytes)}),statement:s});return result;}
export function verifiedContactFieldIdentity01(result:VerifiedHistoricalField):FieldIdentity{const f=fields.get(result);if(!f)fail();return owned(f.identity);}
export function verifiedContactMutationIdentity01(result:VerifiedHistoricalMutation):MutationIdentity{const m=mutations.get(result);if(!m)fail();return owned(m.identity);}
export function verifiedContactTransitionIdentity01(result:VerifiedHistoricalTransition):MutationIdentity{const t=transitions.get(result);if(!t)fail();return owned(t.identity);}
function equalSlot(a:ContactSlot01,b:ContactSlot01){return a.tag===b.tag&&a.sealRevision===b.sealRevision&&same(a.digest,b.digest);}
export function verifyContactTransition01(input:Readonly<{previous:VerifiedHistoricalTransition|null;next:VerifiedHistoricalMutation;replacementFields:readonly VerifiedHistoricalField[]}>):VerifiedHistoricalTransition{
 const i=object(input,['previous','next','replacementFields']),next=mutations.get(i.next),previous=i.previous===null?null:transitions.get(i.previous);if(!next||i.previous!==null&&!previous||!Array.isArray(i.replacementFields)||i.replacementFields.length>2)fail();
 if(Object.getPrototypeOf(i.replacementFields)!==Array.prototype||Reflect.ownKeys(i.replacementFields).length!==i.replacementFields.length+1)fail();const supplied:BoundField[]=[];for(let at=0;at<i.replacementFields.length;at++){const d=Object.getOwnPropertyDescriptor(i.replacementFields,String(at));if(!d||!Object.hasOwn(d,'value'))fail();const f=fields.get(d.value);if(!f)fail();supplied.push(f);}if(new Set(supplied.map(f=>f.identity.kind)).size!==supplied.length)fail();const n=next.identity,s=next.statement;
 if(previous){const p=previous.identity,ps=previous.statement;if(n.operation!==2||n.expectedRevision!==p.revision||!same(n.previousDigest,p.digest)||!same(n.accountId,p.accountId)||!same(n.contactId,p.contactId)||!same(n.routingDigest,p.routingDigest)||n.trustGeneration!==p.trustGeneration||s.origin!==ps.origin||!same(s.rootFingerprint,ps.rootFingerprint)||n.manifestVersion<p.manifestVersion||n.manifestVersion===p.manifestVersion&&!same(n.manifestDigest,p.manifestDigest)||s.readerGeneration<ps.readerGeneration||s.readerGeneration===ps.readerGeneration&&(!same(s.readerId,ps.readerId)||!same(s.readerPoint,ps.readerPoint)))fail();}else if(n.operation===2)fail();
 const current:(BoundField|null)[]=[],used=new Set<BoundField>();for(const[kind,key]of [[1,'name'],[2,'notes']] as const){const slot=n[key];if(slot.tag===0){current.push(null);continue;}if(slot.sealRevision===n.revision){const f=supplied.find(f=>f.identity.kind===kind);if(!f)fail();const q=f.identity;scope(q,s,n.contactId,n.routingDigest);if(!same(q.digest,slot.digest)||q.sealRevision!==n.revision||!same(q.requestId,n.requestId)||q.readerGeneration!==s.readerGeneration||!same(q.readerId,s.readerId)||!same(q.rootWriterId,s.rootWriterId))fail();used.add(f);current.push(f);}else{const index=kind-1;if(!previous||!equalSlot(slot,previous.identity[key])||!previous.fields[index])fail();current.push(previous.fields[index]);}}
 if(used.size!==supplied.length)fail();const result=Object.freeze({kind:'historical_integrity' as const,entity:'transition' as const});transitions.set(result,{...next,fields:Object.freeze(current)});return result;
}
