// SPDX-License-Identifier: AGPL-3.0-only
/** Public genesis review only. No key generation, root unlocking or implicit consent.
 * Session and line binding are contextual: authenticated installation must enforce
 * them atomically; the manifest signature alone does not sign browser consent. */
import {enrollRootPin02,verifyManifest02,type Manifest02} from "./draft02-manifest.js";
const same=(a:Uint8Array,b:Uint8Array)=>a.length===b.length&&a.every((v,i)=>v===b[i]);
const join=(...p:Uint8Array[])=>{const b=new Uint8Array(p.reduce((n,v)=>n+v.length,0));let at=0;for(const v of p){b.set(v,at);at+=v.length;}return b;};
const enc=new TextEncoder(),zero16=new Uint8Array(16),zero32=new Uint8Array(32);
const u64=(n:bigint)=>{if(n<=0n||n>=(1n<<63n))throw Error("Genesis number refused");const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,n);return b;};
const sized=(b:Uint8Array)=>{if(b.length>65535)throw Error("Genesis length refused");return join(Uint8Array.of(b.length>>8,b.length&255),b);};
const hash=async(b:Uint8Array)=>new Uint8Array(await crypto.subtle.digest("SHA-256",Uint8Array.from(b).buffer));
export type GenesisSelection02=Readonly<{account:Uint8Array;session:Uint8Array;device:Uint8Array;line:Uint8Array;phoneSigningFingerprint:Uint8Array;generation:bigint;peer:string}>;
export type GenesisInput02=Readonly<{selection:GenesisSelection02;rootPin:Uint8Array;comparedRootFingerprint:Uint8Array;origin:string;phoneReaderPoint:Uint8Array;archiveReaderPoint:Uint8Array;phoneSignerPoint:Uint8Array;nowMs:bigint;expiresMs:bigint}>;
/** Public fixture contract. Identity fields alone prove no phone provenance.
 * The fingerprint must be independently compared on the selected phone. */
export async function verifyPhoneKeyExport02(input:Uint8Array,selection:GenesisSelection02,comparedFingerprint:Uint8Array){
 const bytes=Uint8Array.from(input),s={...selection},fp=Uint8Array.from(comparedFingerprint);for(const k of ["account","device","line","phoneSigningFingerprint"]as const)s[k]=Uint8Array.from(s[k]);
 if(bytes.length!==223||fp.length!==32||fp.every(v=>v===0)||!same(bytes.subarray(0,5),Uint8Array.of(90,84,80,75,1))||!same(bytes.subarray(5,21),s.account)||!same(bytes.subarray(21,37),s.device)||!same(bytes.subarray(37,53),s.line)||!same(bytes.subarray(53,85),s.phoneSigningFingerprint)||new DataView(bytes.buffer).getBigUint64(85)!==s.generation||!same(await hash(join(enc.encode("ZTSE/phone-keys/v1\0"),bytes)),fp))throw Error("Independent phone export comparison refused");
 return Object.freeze({phoneReaderPoint:bytes.slice(93,158),phoneSignerPoint:bytes.slice(158,223)});
}
/** Public archive-header comparison only, not AEAD verification or recovery.
 * Its key ID must come from the owner's independently accepted archive receipt. */
export async function verifyArchivePublicHeader02(input:Uint8Array,account:Uint8Array,rootFingerprint:Uint8Array,origin:string,independentArchiveId:Uint8Array){
 const b=Uint8Array.from(input),a=Uint8Array.from(account),fp=Uint8Array.from(rootFingerprint),id=Uint8Array.from(independentArchiveId),o=enc.encode(origin),h=177+o.length;
 if(b.length!==h+156||b.length>845||!same(b.subarray(0,6),Uint8Array.of(90,84,65,66,1,1))||!same(b.subarray(22,38),a)||new DataView(b.buffer).getBigUint64(38)!==1n||!same(b.subarray(46,78),fp)||id.length!==32||id.every(v=>v===0)||!same(b.subarray(78,110),id)||new DataView(b.buffer).getUint16(175)!==o.length||!same(b.subarray(177,h),o)||!same(b.subarray(h+104,h+108),Uint8Array.of(0,0,0,48))||!same(await hash(join(enc.encode("ZTSE/key/v1\0"),Uint8Array.of(0,16),b.subarray(110,175))),id))throw Error("Independent archive receipt refused");return b.slice(110,175);
}
function capture(input:GenesisInput02):GenesisInput02 {const selection={...input.selection};for(const field of ["account","session","device","line","phoneSigningFingerprint"]as const)selection[field]=Uint8Array.from(selection[field]);return {...input,selection,rootPin:Uint8Array.from(input.rootPin),comparedRootFingerprint:Uint8Array.from(input.comparedRootFingerprint),phoneReaderPoint:Uint8Array.from(input.phoneReaderPoint),archiveReaderPoint:Uint8Array.from(input.archiveReaderPoint),phoneSignerPoint:Uint8Array.from(input.phoneSignerPoint)};}
export async function encodeConversationGenesisProposal02(input:GenesisInput02){
 const i=capture(input),s=i.selection,url=new URL(i.origin);if(i.origin.length>512||url.protocol!=="https:"||url.origin!==i.origin||url.username||url.password||!/^https:\/\/[\x21-\x7e]+$/.test(i.origin)||![s.account,s.session,s.device,s.line].every(b=>b.length===16&&!b.every(v=>v===0))||s.phoneSigningFingerprint.length!==32||s.phoneSigningFingerprint.every(v=>v===0)||!/^\+[1-9][0-9]{1,14}$/.test(s.peer))throw Error("Genesis independent scope refused");u64(s.generation);u64(i.nowMs);u64(i.expiresMs);if(i.expiresMs<=i.nowMs||i.expiresMs-i.nowMs>86400000n)throw Error("Genesis expiry refused");
 const pin=await enrollRootPin02(i.rootPin,i.comparedRootFingerprint);if(!same(pin.accountId,s.account))throw Error("Genesis account refused");
 const points=[i.phoneReaderPoint,i.archiveReaderPoint,i.phoneSignerPoint,pin.rootPoint];if(points.some((p,n)=>points.slice(0,n).some(old=>same(old,p))))throw Error("Genesis point reuse refused");
 if(!same(await hash(i.phoneSignerPoint),s.phoneSigningFingerprint))throw Error("Genesis paired phone signer refused");
 const records=await Promise.all(points.map(async(point,n)=>{if(point.length!==65||point[0]!==4)throw Error("Genesis point shape refused");await crypto.subtle.importKey("raw",Uint8Array.from(point).buffer,{name:"ECDSA",namedCurve:"P-256"},false,["verify"]);const role=[1,2,4,6][n],keyId=await hash(join(enc.encode("ZTSE/key/v1\0"),Uint8Array.of(role<=3?0:1,role<=3?16:1),point)),bound=role===1||role===4;return join(Uint8Array.of(role),keyId,point,bound?s.device:zero16,bound?s.line:zero16,Uint8Array.of(0,[4,12,2,0][n]),u64(i.nowMs),u64(i.expiresMs),Uint8Array.of(1));}));
 const unsigned=join(Uint8Array.of(90,84,77,65,2),s.account,u64(1n),u64(1n),u64(i.nowMs),u64(i.expiresMs),zero32,pin.rootPoint,Uint8Array.of(4),...records),peer=enc.encode(s.peer);
 const proposal=join(Uint8Array.of(90,84,67,71,1),s.account,s.session,s.device,s.line,s.phoneSigningFingerprint,u64(s.generation),Uint8Array.of(peer.length),peer,sized(enc.encode(i.origin)),i.comparedRootFingerprint,i.rootPin,u64(i.nowMs),u64(i.expiresMs),sized(unsigned));
 return Object.freeze({unsigned,proposal,issuedMs:i.nowMs,expiresMs:i.expiresMs,successorVersion:1n,predecessorDigest:Uint8Array.from(zero32)});
}
export type GenesisCurrent02=Readonly<{selection:GenesisSelection02;rootPin:Uint8Array;nowMs:bigint;version:bigint;manifest:Uint8Array|null;ownerSessionLive:boolean;authorityLive:boolean;deviceKeyLive:boolean;lineBindingLive:boolean}>;
/** One-shot owner-controlled bridge. Server installation must use a v0 CAS and
 * recheck owner/device/line/key/revocation in its transaction. */
export function createConversationGenesis02(input:GenesisInput02,readCurrent:()=>Promise<GenesisCurrent02>,consumeOwnerDecision:(review:Awaited<ReturnType<typeof encodeConversationGenesisProposal02>>)=>Promise<void>,signWithExistingRoot:(review:Awaited<ReturnType<typeof encodeConversationGenesisProposal02>>)=>Promise<Uint8Array>,install:(signed:Uint8Array,expected:GenesisCurrent02)=>Promise<void>){
 const i=capture(input);let used=false,lastNow=0n;
 async function current(version:bigint){const raw=await readCurrent(),selection={...raw.selection};for(const k of ["account","session","device","line","phoneSigningFingerprint"]as const)selection[k]=Uint8Array.from(raw.selection[k]);const c={...raw,selection,rootPin:Uint8Array.from(raw.rootPin),manifest:raw.manifest===null?null:Uint8Array.from(raw.manifest)},s=c.selection,w=i.selection;if(!c.ownerSessionLive||!c.authorityLive||!c.deviceKeyLive||!c.lineBindingLive||c.version!==version||c.nowMs<i.nowMs||c.nowMs<lastNow||c.nowMs>=i.expiresMs||!same(c.rootPin,i.rootPin)||s.generation!==w.generation||s.peer!==w.peer||!(["account","session","device","line","phoneSigningFingerprint"]as const).every(k=>same(s[k],w[k]))||version===0n&&c.manifest!==null)throw Error("Genesis authority changed");lastNow=c.nowMs;return c;}
 return Object.freeze({async provision():Promise<Manifest02>{if(used)throw Error("Genesis proposal already consumed");used=true;await current(0n);const review=await encodeConversationGenesisProposal02(i);await consumeOwnerDecision({...review,unsigned:Uint8Array.from(review.unsigned),proposal:Uint8Array.from(review.proposal)});await current(0n);const signature=Uint8Array.from(await signWithExistingRoot({...review,unsigned:Uint8Array.from(review.unsigned),proposal:Uint8Array.from(review.proposal)}));const before=await current(0n),signed=join(review.unsigned,signature),pin=await enrollRootPin02(i.rootPin,i.comparedRootFingerprint);const verified=await verifyManifest02(signed,pin,before.nowMs);const installing=await current(0n);await install(Uint8Array.from(verified.bytes),installing);const after=await current(1n);if(!after.manifest)throw Error("Genesis installation missing");const accepted=await verifyManifest02(after.manifest,pin,after.nowMs);if(!same(accepted.digest,verified.digest))throw Error("Genesis installed fork refused");return accepted;}});
}
