// SPDX-License-Identifier: AGPL-3.0-only
/** Typed pre-interval public approval. No keys/signing/network. The manifest does
 * not sign peer/session consent; authenticated server activation enforces scope. */
import {verifiedManifestIdentity02,verifiedManifestTrust02,verifyManifest02,type Manifest02} from "./draft02-manifest.js";
const same=(a:Uint8Array,b:Uint8Array)=>a.length===b.length&&a.every((v,i)=>v===b[i]);
const join=(...p:Uint8Array[])=>{const b=new Uint8Array(p.reduce((n,v)=>n+v.length,0));let at=0;for(const v of p){b.set(v,at);at+=v.length;}return b;};
const u64=(n:bigint)=>{if(n<=0n||n>=(1n<<63n))throw Error("Activation number refused");const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,n);return b;};
const sized=(b:Uint8Array)=>{if(b.length>65535)throw Error("Activation length refused");return join(Uint8Array.of(b.length>>8,b.length&255),b);};
export type ActivationSelection02=Readonly<{account:Uint8Array;session:Uint8Array;device:Uint8Array;line:Uint8Array;generation:bigint;peer:string;phoneReader:Uint8Array;archiveReader:Uint8Array;phoneSigner:Uint8Array}>;
export async function encodeConversationActivationProposal02(input:Readonly<{selection:ActivationSelection02;predecessor:Manifest02;origin:string;comparedRootFingerprint:Uint8Array;nowMs:bigint}>){
 const s={...input.selection};for(const field of ["account","session","device","line","phoneReader","archiveReader","phoneSigner"] as const)s[field]=Uint8Array.from(s[field]);const fp=Uint8Array.from(input.comparedRootFingerprint),origin=input.origin,now=input.nowMs;
 const url=new URL(origin);if(origin.length>512||!/^https:\/\/[\x21-\x7e]+$/.test(origin)||url.protocol!=="https:"||url.origin!==origin||url.username||url.password||url.pathname!=="/"||url.search||url.hash||fp.length!==32||fp.every(v=>v===0)||![s.account,s.session,s.device,s.line].every(b=>b.length===16&&!b.every(v=>v===0))||![s.phoneReader,s.archiveReader,s.phoneSigner].every(b=>b.length===32&&!b.every(v=>v===0))||!/^\+[1-9][0-9]{1,14}$/.test(s.peer))throw Error("Activation independent scope refused");u64(s.generation);u64(now);
 const identity=verifiedManifestIdentity02(input.predecessor,now),predecessor=await verifyManifest02(Uint8Array.from(input.predecessor.bytes),verifiedManifestTrust02(input.predecessor,now),now);
 if(identity.generation!==1n||!same(identity.accountId,s.account)||identity.version>=(1n<<63n)-1n||now<predecessor.issuedMs)throw Error("Activation predecessor refused");
 const pin=join(Uint8Array.of(90,84,82,80,2),identity.accountId,u64(identity.generation),identity.rootPoint),actual=new Uint8Array(await crypto.subtle.digest("SHA-256",join(new TextEncoder().encode("ZTSE/root-pin/v2\0"),pin).buffer));if(!same(actual,fp))throw Error("Activation compared root refused");
 for(const [role,id]of [[1,s.phoneReader],[2,s.archiveReader],[4,s.phoneSigner]] as const){const selected=predecessor.keys.filter(k=>k.role===role&&k.state===1&&k.fromMs<=now&&now<k.untilMs&&(role===2||same(k.deviceId,s.device)&&same(k.lineId,s.line)));if(selected.length!==1||!same(selected[0].keyId,id))throw Error("Activation current reader/signer refused");}
 const unsigned=Uint8Array.from(predecessor.bytes.subarray(0,-64));unsigned.set(u64(identity.version+1n),29);unsigned.set(u64(now),37);unsigned.set(identity.digest,53);const peer=new TextEncoder().encode(s.peer),proposal=join(Uint8Array.of(90,84,67,65,1),s.account,s.session,s.device,s.line,u64(s.generation),Uint8Array.of(peer.length),peer,sized(new TextEncoder().encode(origin)),fp,u64(identity.version),identity.digest,s.phoneReader,s.archiveReader,s.phoneSigner,u64(now),sized(predecessor.bytes),sized(unsigned));if(proposal.length>20480)throw Error("Activation proposal size refused");return Object.freeze({unsigned,proposal,issuedMs:now,predecessorDigest:Uint8Array.from(identity.digest),successorVersion:identity.version+1n});
}
