// SPDX-License-Identifier: AGPL-3.0-only
// Real packaged Chromium/IDB; session transport is an explicitly synthetic observation.
import {test} from 'node:test';import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
import {refreshFixture,signFixtureSuccessor02,join} from '../../../sdk/typescript/test/conversation-refresh-fixture.mjs';
import {canonicalSignature02} from '../../../sdk/typescript/dist/draft02-manifest.js';
import {encodeContactReaderStatementUnsigned01} from '../../../sdk/typescript/dist/contact-reader-statement.js';
import {packageAccountRootTrust,files} from '../../../scripts/package_account_root_trust_browser.mjs';
const repo=fileURLToPath(new URL('../../../',import.meta.url)),require=createRequire(path.join(repo,'web/owner/package.json'));
async function fixture(){
 const f=await refreshFixture(),now=Date.now(),u=f.predecessor.bytes.slice(0,-64),view=new DataView(u.buffer);view.setBigUint64(29,1n);view.setBigUint64(37,BigInt(now-1000));view.setBigUint64(45,BigInt(now+60000));u.fill(0,53,85);
 for(let at=151;at<u.length;at+=149){view.setBigUint64(at+132,BigInt(now-1000));view.setBigUint64(at+140,BigInt(now+60000));}
 const signed=await signFixtureSuccessor02(f,u),pin=new Uint8Array(94);pin.set([90,84,82,80,2]);pin.set(f.review.binding.account,5);new DataView(pin.buffer).setBigUint64(21,1n);pin.set(f.predecessor.rootPoint,29);
 const o=new TextEncoder().encode(f.origin),card=new Uint8Array(133+o.length);card.set([90,84,82,67,1]);new DataView(card.buffer).setUint16(5,o.length);card.set(o,7);card.set(pin,7+o.length);
 const h=b=>Buffer.from(b).toString('hex'),uuid=b=>h(b).replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,'$1-$2-$3-$4-$5');
 const manifestDigest=new Uint8Array(await crypto.subtle.digest('SHA-256',u)),reader=f.predecessor.keys.find(k=>k.role===2),s={authorizationId:new Uint8Array(16).fill(7),accountId:f.review.binding.account,origin:f.origin,trustGeneration:1n,manifestVersion:1n,readerGeneration:1n,rootFingerprint:f.comparedRootFingerprint,manifestDigest,readerId:reader.keyId,readerPoint:reader.point,issuedMs:BigInt(now),untilMs:BigInt(now+30000),capability:3};
 const unsigned=encodeContactReaderStatementUnsigned01(s),length=new Uint8Array(4);new DataView(length.buffer).setUint32(0,unsigned.length);
 const point=f.predecessor.rootPoint,scalar=new Uint8Array(32);scalar[31]=1;const b64=b=>Buffer.from(b).toString('base64url');
 const key=await crypto.subtle.importKey('jwk',{kty:'EC',crv:'P-256',x:b64(point.slice(1,33)),y:b64(point.slice(33)),d:b64(scalar)},{name:'ECDSA',namedCurve:'P-256'},false,['sign']);scalar.fill(0);
 const signature=canonicalSignature02(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,join(new TextEncoder().encode('ZT/contact-reader/authorization/v1\0'),length,unsigned))));
 const expected=Object.fromEntries(Object.entries(s).map(([k,v])=>[k,v instanceof Uint8Array?(['accountId','authorizationId'].includes(k)?uuid(v):h(v)):typeof v==='bigint'?v.toString():v]));
 expected.statementDigest=h(new Uint8Array(await crypto.subtle.digest('SHA-256',join(unsigned,signature))));
 return {f,account:uuid(f.review.binding.account),fingerprint:h(f.comparedRootFingerprint),card,signed,statement:join(unsigned,signature),expected,u,signReader:async issued=>{const bytes=encodeContactReaderStatementUnsigned01({...s,issuedMs:BigInt(issued)}),len=new Uint8Array(4);new DataView(len.buffer).setUint32(0,bytes.length);const sig=canonicalSignature02(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,join(new TextEncoder().encode('ZT/contact-reader/authorization/v1\0'),len,bytes)))),packet=join(bytes,sig);expected.issuedMs=String(issued);expected.statementDigest=h(new Uint8Array(await crypto.subtle.digest('SHA-256',packet)));return packet;},signNext:async()=>{const next=u.slice();new DataView(next.buffer).setBigUint64(29,2n);next.set(manifestDigest,53);return signFixtureSuccessor02(f,next);}};
}
test('actual fixed package page supports genuine genesis, same/next history and intended reader integrity',async()=>{
 const {chromium}=require('playwright'),out=await mkdtemp(path.join(os.tmpdir(),'account-trust-browser-'));let browser;
 try{
  await packageAccountRootTrust(out);const modules=Object.fromEntries(await Promise.all(files.map(async n=>[n,await readFile(path.join(out,'sdk',n))]))),html=await readFile(path.join(repo,'web/owner/account-root-trust.html')),controller=await readFile(path.join(repo,'web/owner/account-root-trust.js'));
  browser=await chromium.launch({headless:true});const f=await fixture();
  async function context(heldFile=false){const ctx=await browser.newContext({serviceWorkers:'block'});await ctx.addCookies([{name:'__Host-zrotext_csrf',value:'synthetic-review',url:f.f.origin,secure:true,sameSite:'Strict'},{name:'__Host-zrotext_session',value:'synthetic-owner-a',url:f.f.origin,secure:true,httpOnly:true,sameSite:'Strict'}]);let session={account_id:f.account,user_id:'22222222-2222-4222-8222-222222222222',session_id:'33333333-3333-4333-8333-333333333333',role:'owner',server_now_ms:String(Date.now())};const requests=[];
   if(heldFile)await ctx.addInitScript(()=>{const original=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){if(this.name!=='public-card.bin')return original.call(this);window.__heldCard=true;return new Promise((yes,no)=>window.__releaseCard=()=>original.call(this).then(yes,no));};});
   await ctx.route('**/*',async route=>{const url=new URL(route.request().url());requests.push(url.pathname);if(url.origin!==f.f.origin)return route.abort();let body,type;
    if(url.pathname==='/v1/auth/session'){body=JSON.stringify(session);type='application/json';}else if(url.pathname==='/owner/account/root-trust'){body=html;type='text/html';}else if(url.pathname==='/owner/account/root-trust.js'){body=controller;type='text/javascript';}else{const name=url.pathname.replace('/v1/owner/account-root-trust-sdk/sdk/','');if(!Object.hasOwn(modules,name))return route.abort();body=modules[name];type='text/javascript';}
    return route.fulfill({status:200,body,headers:{'content-type':type,'cache-control':'no-store','content-security-policy':"default-src 'none'; script-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'"}});
   });const page=await ctx.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(10000);await page.goto(f.f.origin+'/owner/account/root-trust');await page.locator('#review').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('review').disabled);
   await page.locator('#account').fill(f.account);await page.locator('#origin').fill(f.f.origin);await page.locator('#fingerprint').fill(f.fingerprint);await page.locator('#card').setInputFiles({name:'public-card.bin',mimeType:'application/octet-stream',buffer:Buffer.from(f.card)});await page.locator('#manifest').setInputFiles({name:'manifest.bin',mimeType:'application/octet-stream',buffer:Buffer.from(f.signed)});
   return {ctx,page,requests,setSession:v=>{session=v;}};
  }
  const c=await context();try{
   await c.page.locator('#review').click();await c.page.waitForFunction(()=>!document.getElementById('decision').hidden);assert.match(await c.page.locator('#tuple').textContent(),/manifestDigest/);
   await c.page.locator('#accept').click();await c.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Signed local history accepted'));
   await c.page.locator('summary').first().click();await c.page.locator('#expected').fill(JSON.stringify(f.expected));await c.page.locator('#statement').setInputFiles({name:'statement.bin',mimeType:'application/octet-stream',buffer:Buffer.from(f.statement)});await c.page.locator('#verify-statement').click();await c.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Historical reader statement integrity'));
   for(const bytes of [f.signed,await f.signNext()]){await c.page.locator('#manifest').setInputFiles({name:'manifest.bin',mimeType:'application/octet-stream',buffer:Buffer.from(bytes)});await c.page.locator('#review').click();await c.page.waitForFunction(()=>!document.getElementById('decision').hidden);await c.page.locator('#accept').click();await c.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Signed local history accepted'));}
   assert.ok(c.requests.every(p=>p==='/v1/auth/session'||p==='/owner/account/root-trust'||p==='/owner/account/root-trust.js'||p.startsWith('/v1/owner/account-root-trust-sdk/sdk/')));
  }finally{await c.ctx.close();}
  for(const mode of ['wrong-fingerprint','decline','session-drift','cold-next']){const c=await context();try{
   if(mode==='wrong-fingerprint')await c.page.locator('#fingerprint').fill('00'.repeat(32));if(mode==='cold-next')await c.page.locator('#manifest').setInputFiles({name:'next.bin',mimeType:'application/octet-stream',buffer:Buffer.from(await f.signNext())});
   await c.page.locator('#review').click();if(mode==='wrong-fingerprint'||mode==='cold-next'){await c.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Local review unavailable'));}else{
    await c.page.waitForFunction(()=>!document.getElementById('decision').hidden);if(mode==='decline'){await c.page.locator('#decline').click();assert.equal(await c.page.locator('#decision').isHidden(),true);}else{c.setSession({account_id:f.account,user_id:'22222222-2222-4222-8222-222222222222',session_id:'44444444-4444-4444-8444-444444444444',role:'owner',server_now_ms:String(Date.now())});await c.page.locator('#accept').click();await c.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Local review unavailable'));}
   }
   const stored=await c.page.evaluate(async()=>{const {Draft02TrustStore}=await import('/v1/owner/account-root-trust-sdk/sdk/draft02-trust-store.js'),store=await Draft02TrustStore.open();try{return (await store.read())?.trust.version.toString()??null;}finally{store.close();}});assert.equal(stored,null,mode);
  }finally{await c.ctx.close();}}
  for(const mode of ['wrong-intent','wrong-packet-digest','bad-signature']){const c=await context();try{
   await c.page.locator('#review').click();await c.page.waitForFunction(()=>!document.getElementById('decision').hidden);await c.page.locator('#accept').click();await c.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Signed local history accepted'));
   const expected={...f.expected},statement=f.statement.slice();if(mode==='wrong-intent')expected.readerGeneration='2';if(mode==='wrong-packet-digest')expected.statementDigest='00'.repeat(32);if(mode==='bad-signature')statement[statement.length-1]^=1;
   await c.page.locator('summary').first().click();await c.page.locator('#expected').fill(JSON.stringify(expected));await c.page.locator('#statement').setInputFiles({name:'statement.bin',mimeType:'application/octet-stream',buffer:Buffer.from(statement)});await c.page.locator('#verify-statement').click();await c.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Local review unavailable'));assert.equal(await c.page.locator('#decision').isHidden(),true);
   const version=await c.page.evaluate(async()=>{const {Draft02TrustStore}=await import('/v1/owner/account-root-trust-sdk/sdk/draft02-trust-store.js'),store=await Draft02TrustStore.open();try{return (await store.read()).trust.version.toString();}finally{store.close();}});assert.equal(version,'1');
  }finally{await c.ctx.close();}}
  const drift=await context(true);try{
   await drift.page.locator('#review').click();await drift.page.waitForFunction(()=>window.__heldCard===true);const b='44444444-4444-4444-8444-444444444444';await drift.page.locator('#account').fill(b);drift.setSession({account_id:b,user_id:'22222222-2222-4222-8222-222222222222',session_id:'33333333-3333-4333-8333-333333333333',role:'owner',server_now_ms:String(Date.now())});await drift.ctx.addCookies([{name:'__Host-zrotext_session',value:'synthetic-owner-b',url:f.f.origin,secure:true,httpOnly:true,sameSite:'Strict'}]);await drift.page.evaluate(()=>window.__releaseCard());
   await drift.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Local review unavailable')||!document.getElementById('decision').hidden,null,{timeout:2000});
   // A regressed controller may publish review and persist account A while
   // sampling owner B. Exercise that real positive path before asserting no row.
   if(!await drift.page.locator('#decision').isHidden()){await drift.page.locator('#accept').click();await drift.page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Signed local history accepted'),null,{timeout:2000});}
   const stored=await drift.page.evaluate(async()=>{const {Draft02TrustStore}=await import('/v1/owner/account-root-trust-sdk/sdk/draft02-trust-store.js'),store=await Draft02TrustStore.open();try{const s=await store.read();return s===null?null:{account:Array.from(s.trust.accountId),version:s.trust.version.toString()};}finally{store.close();}});assert.equal(stored,null,'changed owner must not persist the original account root');assert.equal(drift.requests.filter(p=>p==='/v1/auth/session').length,0);assert.equal(await drift.page.locator('#decision').isHidden(),true);
  }finally{await drift.ctx.close();}
 }finally{if(browser)await browser.close();await rm(out,{recursive:true,force:true});}
});

test('packaged paired review keeps real history, whole signature and original uncertain identity',async()=>{
 const {chromium}=require('playwright'),out=await mkdtemp(path.join(os.tmpdir(),'paired-contact-browser-'));let browser;
 try{
  await packageAccountRootTrust(out);const modules=Object.fromEntries(await Promise.all(files.map(async n=>[n,await readFile(path.join(out,'sdk',n))]))),html=await readFile(path.join(repo,'web/owner/account-root-trust.html')),controller=await readFile(path.join(repo,'web/owner/account-root-trust.js'));
  browser=await chromium.launch({headless:true});
  for(const mode of ['positive','absent','duplicate','context-drift','wrong-ceiling','wrong-signature','complete-unknown']){
   const f=await fixture(),ctx=await browser.newContext({serviceWorkers:'block'}),calls=[],enc=b=>Buffer.from(b).toString('base64'),id=s=>Buffer.from(s.replaceAll('-',''),'hex'),number=s=>{const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(s));return b;};let pending,originalCreate,release,held=false;
   await ctx.addCookies([{name:'__Host-zrotext_csrf',value:'synthetic-review',url:f.f.origin,secure:true,sameSite:'Strict'},{name:'__Host-zrotext_session',value:'synthetic-owner',url:f.f.origin,secure:true,httpOnly:true,sameSite:'Strict'}]);
   await ctx.route('**/*',async route=>{
    const request=route.request(),url=new URL(request.url());if(url.origin!==f.f.origin)return route.abort();let body,type='application/json',status=200;
    if(url.pathname==='/owner/account/root-trust'){body=html;type='text/html';}
    else if(url.pathname==='/owner/account/root-trust.js'){body=controller;type='text/javascript';}
    else if(url.pathname==='/v1/auth/session')body=JSON.stringify({account_id:f.account,user_id:'22222222-2222-4222-8222-222222222222',session_id:'33333333-3333-4333-8333-333333333333',role:'owner',server_now_ms:String(Date.now())});
    else if(url.pathname==='/v1/owner/export'){
     calls.push({path:url.pathname,method:request.method()});assert.equal(request.headers()['x-zrotext-csrf'],'synthetic-review');assert.match(request.headers().cookie,/__Host-zrotext_session=synthetic-owner/);assert.equal(url.search,'?contact_reader_only=state');
     if(mode==='context-drift'){held=true;await new Promise(r=>release=r);}
     body=JSON.stringify({kind:'contact_reader_state',state:mode==='absent'?null:{root_pin_b64:enc(f.card.slice(7+Buffer.byteLength(f.f.origin),101+Buffer.byteLength(f.f.origin))),root_fingerprint_b64:enc(f.f.comparedRootFingerprint),trust_generation:'1',last_mutation_ms:String(Date.now()),current:{phase:'empty',mutation_revision:'0',allocation_generation:'0',observed_ms:String(Date.now())},signed_statement:null}});
     if(mode==='duplicate')body=body.replace('"kind":','"kind":"contact_reader_state","kind":');
    }else if(url.pathname.endsWith('/intents')){
     originalCreate=request.postData();calls.push({path:url.pathname,method:request.method(),body:originalCreate});const c=JSON.parse(originalCreate),o=Buffer.from(f.f.origin),len=Buffer.alloc(2);len.writeUInt16BE(o.length);
     const commitment=enc(new Uint8Array(await crypto.subtle.digest('SHA-256',Buffer.concat([Buffer.from([1]),id(f.account),len,o,id(c.create_request),number(c.expected_revision),Buffer.from([0]),Buffer.alloc(16),Buffer.alloc(8),Buffer.alloc(32),Buffer.from(c.selected_reader_id,'base64'),Buffer.from(c.compared_root_fingerprint,'base64'),number(c.requested_until_ms)]))));
     f.statement=await f.signReader(Date.now());const record=k=>({key_id_b64:enc(k.keyId),public_point_b64:enc(k.point),from_ms:String(new DataView(f.u.buffer).getBigUint64(37)),until_ms:String(new DataView(f.u.buffer).getBigUint64(45))}),reader=f.f.predecessor.keys.find(k=>k.role===2),writer=f.f.predecessor.keys.find(k=>k.role===6),unsigned=f.statement.slice(0,-64),issued=f.expected.issuedMs;
     pending={kind:'pending',create_input_digest:commitment,create_request:c.create_request,authorization:f.expected.authorizationId,generation:'1',creation_expected_revision:c.expected_revision,allocated_revision:'1',unsigned_digest:enc(new Uint8Array(await crypto.subtle.digest('SHA-256',unsigned))),unsigned:enc(unsigned),issued_ms:issued,expires_ms:String(BigInt(issued)+300000n),until_ms:f.expected.untilMs,created_by_user:'22222222-2222-4222-8222-222222222222',created_session:'33333333-3333-4333-8333-333333333333',creation_source:{kind:'historical_creation_source',account_id:f.account,root_pin_b64:enc(f.card.slice(7+o.length,101+o.length)),root_fingerprint_b64:enc(f.f.comparedRootFingerprint),trust_generation:'1',manifest_version:'1',manifest_digest_b64:enc(Buffer.from(f.expected.manifestDigest,'hex')),manifest_b64:enc(f.signed),observed_ms:issued,manifest_issued_ms:String(new DataView(f.u.buffer).getBigUint64(37)),manifest_expires_ms:String(new DataView(f.u.buffer).getBigUint64(45)),signed_until_ms:String(new DataView(f.u.buffer).getBigUint64(45)),reader:record(reader),root_writer:record(writer)},current:{phase:'empty',mutation_revision:'1',allocation_generation:'1',observed_ms:issued}};if(mode==='wrong-ceiling')pending.creation_source.signed_until_ms=String(BigInt(pending.creation_source.signed_until_ms)+1n);body=JSON.stringify(pending);
    }else if(url.pathname.endsWith('/complete')){
     const c=JSON.parse(request.postData());calls.push({path:url.pathname,method:request.method(),body:request.postData()});assert.equal(c.signed_statement,enc(f.statement));assert.equal(c.code,'123456');
     if(mode==='complete-unknown'){status=503;body='';}else body=JSON.stringify({kind:'historical_completed',create_input_digest:pending.create_input_digest,create_request:pending.create_request,authorization:pending.authorization,generation:'1',creation_expected_revision:pending.creation_expected_revision,unsigned_digest:pending.unsigned_digest,terminal_ms:String(Date.now()),current:{...pending.current,observed_ms:String(Date.now())},signed_statement:enc(f.statement),statement_digest:enc(Buffer.from(f.expected.statementDigest,'hex'))});
    }else{const name=url.pathname.replace('/v1/owner/account-root-trust-sdk/sdk/','');if(!Object.hasOwn(modules,name))return route.abort();body=modules[name];type='text/javascript';}
    return route.fulfill({status,body,headers:{'content-type':type,'cache-control':'no-store','content-security-policy':"default-src 'none'; script-src 'self'; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'"}});
   });
   try{
    const page=await ctx.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(10000);await page.goto(f.f.origin+'/owner/account/root-trust');await page.waitForFunction(()=>!document.getElementById('review').disabled);
    for(const [name,value]of [['account',f.account],['origin',f.f.origin],['fingerprint',f.fingerprint]])await page.locator('#'+name).fill(value);
    await page.locator('#card').setInputFiles({name:'public-card.bin',buffer:Buffer.from(f.card)});await page.locator('#manifest').setInputFiles({name:'manifest.bin',buffer:Buffer.from(f.signed)});await page.locator('#review').click();await page.waitForFunction(()=>!document.getElementById('decision').hidden);await page.locator('#accept').click();await page.waitForFunction(()=>document.getElementById('status').textContent.startsWith('Signed local history accepted'));
    await page.locator('summary').nth(1).click();for(const [name,value]of [['bundle','ab'.repeat(16)],['reader-id',f.expected.readerId],['reader-point',f.expected.readerPoint],['requested-until',f.expected.untilMs]])await page.locator('#'+name).fill(value);await page.locator('#issuer-review').click();
    if(mode==='context-drift'){while(!held)await new Promise(r=>setTimeout(r,5));await page.locator('#reader-id').fill('cd'.repeat(32));release();}
    if(['absent','duplicate','context-drift'].includes(mode)){await page.waitForFunction(()=>/unavailable/i.test(document.getElementById('issuer-status').textContent));assert.equal(await page.locator('#issuer-create').isDisabled(),true);assert.equal(calls.filter(c=>c.method==='POST').length,0);continue;}
    await page.waitForFunction(()=>!document.getElementById('issuer-create').disabled);await page.locator('#issuer-create').click();if(mode==='wrong-ceiling'){await page.waitForFunction(()=>/unknown/i.test(document.getElementById('issuer-status').textContent));assert.equal(await page.locator('#issuer-export').isDisabled(),true);assert.equal(await page.locator('#issuer-complete').isDisabled(),true);assert.equal(calls.filter(c=>c.path.endsWith('/complete')).length,0);continue;}await page.waitForFunction(()=>!document.getElementById('issuer-export').disabled);
    const download=page.waitForEvent('download');await page.locator('#issuer-export').click();const proposal=await download;assert.equal(proposal.suggestedFilename(),'contact-reader-proposal.json');const packet=JSON.parse(await readFile(await proposal.path(),'utf8'));assert.equal(JSON.stringify(packet.create),originalCreate);assert.deepEqual(packet.pending,pending);assert.match(await page.locator('#issuer-facts').textContent(),/contact-reader-sign --account/);
    const statement=f.statement.slice();if(mode==='wrong-signature')statement[statement.length-1]^=1;await page.locator('#issuer-signature').setInputFiles({name:'signed.bin',buffer:Buffer.from(statement)});await page.locator('#issuer-import').click();
    if(mode==='wrong-signature'){await page.waitForFunction(()=>/unknown|ended/i.test(document.getElementById('issuer-status').textContent));assert.equal(await page.locator('#issuer-complete').isDisabled(),true);assert.equal(calls.filter(c=>c.path.endsWith('/complete')).length,0);continue;}
    await page.waitForFunction(()=>!document.getElementById('issuer-complete').disabled);await page.locator('#issuer-factor').fill('123456');await page.locator('#issuer-complete').click();await page.waitForFunction(()=>/acknowledged this exact|unknown/i.test(document.getElementById('issuer-status').textContent));assert.equal(await page.locator('#issuer-factor').inputValue(),'');assert.equal(await page.locator('#issuer-complete').isDisabled(),true);assert.equal(calls.filter(c=>c.path.endsWith('/complete')).length,1);assert.equal(await page.locator('#issuer-create').isDisabled(),true);
    if(mode==='complete-unknown'){const recovery=page.waitForEvent('download');await page.locator('#issuer-recovery-export').click();const file=await recovery,raw=await readFile(await file.path(),'utf8');assert.equal(raw.includes('123456'),false);assert.equal(JSON.parse(raw).signed,enc(f.statement));assert.equal(JSON.parse(raw).create.create_request,pending.create_request);}
   }finally{if(release)release();await ctx.close();}
  }
 }finally{if(browser)await browser.close();await rm(out,{recursive:true,force:true});}
});
