# SPDX-License-Identifier: AGPL-3.0-only
"""Validate the shared SMS segment-estimate vectors against the reference.

The JSON is generated by gen_sms_segment_vectors.py; this test re-derives
every case from the spec tables so a hand-edit or a generator regression
fails CI rather than silently changing the contract.
"""

import json
import math
import pathlib
import unittest

GSM_DEFAULT = set(
    "@\u00a3$\u00a5\u00e8\u00e9\u00f9\u00ec\u00f2\u00c7\n\u00d8\u00f8\r\u00c5\u00e5"
    "\u0394_\u03a6\u0393\u039b\u03a9\u03a0\u03a8\u03a3\u0398\u039e\u00c6\u00e6\u00df"
    "\u00c9 !\"#\u00a4%&'()*+,-./0123456789:;<=>?\u00a1"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ\u00c4\u00d6\u00d1\u00dc\u00a7\u00bf"
    "abcdefghijklmnopqrstuvwxyz\u00e4\u00f6\u00f1\u00fc\u00e0"
)
GSM_EXTENSION = set("\u000c^{}\\[~]|\u20ac")
VECTORS = pathlib.Path(__file__).resolve().parent.parent / "vectors" / "sms-segment-estimate-01.json"


def reference_estimate(text):
    units = 0
    index = 0
    while index < len(text):
        code = ord(text[index])
        if 0xD800 <= code <= 0xDBFF:
            if index + 1 >= len(text) or not (0xDC00 <= ord(text[index + 1]) <= 0xDFFF):
                raise ValueError("lone surrogate")
            index += 2
        elif 0xDC00 <= code <= 0xDFFF:
            raise ValueError("lone surrogate")
        elif code < 0x20 and text[index] not in "\n\r\f":
            raise ValueError("control character")
        else:
            index += 1
        units += 1
    if all(ch in GSM_DEFAULT or ch in GSM_EXTENSION for ch in text):
        septets = sum(2 if ch in GSM_EXTENSION else 1 for ch in text)
        per_part = 160 if septets <= 160 else 153
        parts = 1 if septets <= 160 else math.ceil(septets / per_part)
        if parts > 6:
            raise ValueError("too long")
        return {
            "encoding": "gsm", "parts": parts, "perPart": per_part,
            "length": septets, "empty": len(text) == 0,
        }
    # UCS-2 length is UTF-16 code units.
    length = sum(2 if 0x10000 <= ord(ch) else 1 for ch in text)
    per_part = 70 if length <= 70 else 67
    parts = 1 if length <= 70 else math.ceil(length / per_part)
    if parts > 6:
        raise ValueError("too long")
    return {
        "encoding": "ucs2", "parts": parts, "perPart": per_part,
        "length": length, "empty": len(text) == 0,
    }


class SegmentEstimateVectors(unittest.TestCase):
    def setUp(self):
        with VECTORS.open(encoding="utf-8") as handle:
            self.vectors = json.load(handle)

    def test_every_vector_matches_the_reference(self):
        self.assertGreater(len(self.vectors["cases"]), 20)
        for case in self.vectors["cases"]:
            if "error" in case:
                with self.assertRaises(ValueError, msg=case["name"]):
                    reference_estimate(case["text"])
            else:
                self.assertEqual(
                    reference_estimate(case["text"]), case["estimate"], case["name"]
                )

    def test_the_documented_thresholds_are_all_covered(self):
        names = " ".join(case["name"] for case in self.vectors["cases"])
        for required in (
            "escape", "160", "161", "306", "307", "70", "71", "134", "135",
            "918", "919", "402", "403", "surrogate", "control", "six",
        ):
            self.assertIn(required, names)


if __name__ == "__main__":
    unittest.main()
