#!/usr/bin/env python3
"""Render docs/API-REFERENCE.md from protocol/v1/openapi/public-v1.json.

Run without arguments to rewrite the page, or with --check to fail when it is stale.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "protocol" / "v1" / "openapi" / "public-v1.json"
OUTPUT = ROOT / "docs" / "API-REFERENCE.md"
METHODS = ("get", "put", "post", "patch", "delete")


def cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def ref_name(node):
    return node["$ref"].rsplit("/", 1)[1]


def type_of(schema):
    if "$ref" in schema:
        return f"[{ref_name(schema)}](#{ref_name(schema).lower()})"
    kind = schema.get("type", "any")
    if isinstance(kind, list):
        kind = " or ".join(kind)
    if kind == "array":
        return f"array of {type_of(schema.get('items', {}))}"
    if "enum" in schema:
        return "enum: " + ", ".join(f"`{value}`" for value in schema["enum"])
    return kind + (f" ({schema['format']})" if "format" in schema else "")


def schema_table(schema):
    required = set(schema.get("required", []))
    lines = ["| Field | Type | Required | Description |", "|---|---|---|---|"]
    for name, prop in schema.get("properties", {}).items():
        lines.append(f"| `{name}` | {cell(type_of(prop))} | {'yes' if name in required else 'no'} "
                     f"| {cell(prop.get('description', ''))} |")
    return lines


def security(operation, spec):
    names = [name for option in operation.get("security", []) for name in option]
    if not names:
        return "none documented"
    return ", ".join(f"`{name}`" for name in names)


def render_operation(path, method, operation, spec):
    state = "Implemented" if operation["x-implemented"] else "**Planned: no route exists today**"
    out = [f"### `{method.upper()} {path}`", "", f"{operation['summary']}. Status: {state}.", "",
           operation["description"], "", f"Authentication: {security(operation, spec)}.", ""]
    params = operation.get("parameters", [])
    if params:
        out += ["| Parameter | In | Required | Description |", "|---|---|---|---|"]
        for param in params:
            out.append(f"| `{param['name']}` | {param['in']} | {'yes' if param.get('required') else 'no'} "
                       f"| {cell(param.get('description', ''))} |")
        out.append("")
    body = operation.get("requestBody")
    if body:
        schema = body["content"]["application/json"]["schema"]
        out += [f"Request body: [{ref_name(schema)}](#{ref_name(schema).lower()}).", ""]
    if operation.get("responses"):
        out += ["| Status | Meaning |", "|---|---|"]
        for status, response in operation["responses"].items():
            if "$ref" in response:
                response = spec["components"]["responses"][ref_name(response)]
            out.append(f"| {status} | {cell(response.get('description', ''))} |")
        out.append("")
    return out


def render(spec):
    out = [
        "<!-- Generated by scripts/render_api_reference.py from protocol/v1/openapi/public-v1.json. Do not edit. -->",
        "# Public HTTP API reference (v1)", "",
        f"{spec['info']['title']}, version {spec['info']['version']}. Machine-readable source: "
        "[`protocol/v1/openapi/public-v1.json`](../protocol/v1/openapi/public-v1.json). "
        "This page is regenerated by `python scripts/render_api_reference.py`, and CI fails when it is stale "
        "or when the spec and the server's routes drift apart.", "",
        "**Status.** Operations marked *Planned* are design targets: no route exists in the server today. "
        "There is no general send route yet. The only outbound route is the allowlisted synthetic-alpha test plane. "
        "See [Send your first message](SEND-FIRST-MESSAGE.md) for worked examples.", "",
        "## Contents", ""]
    tags = spec["tags"]
    out += [f"- [{tag['name']}](#{tag['name']})" for tag in tags]
    out += ["- [Schemas](#schemas)", ""]
    for tag in tags:
        out += [f"## {tag['name']}", "", tag["description"], ""]
        for path, item in spec["paths"].items():
            for method in METHODS:
                operation = item.get(method)
                if operation and operation["tags"] == [tag["name"]]:
                    out += render_operation(path, method, operation, spec)
    out += ["## Schemas", ""]
    for name, schema in spec["components"]["schemas"].items():
        out += [f"### {name}", "", schema.get("description", ""), ""]
        if "properties" in schema:
            out += schema_table(schema) + [""]
        elif "enum" in schema:
            out += ["Values: " + ", ".join(f"`{value}`" for value in schema["enum"]) + ".", ""]
    return "\n".join(out).rstrip("\n") + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the page is stale")
    args = parser.parse_args()
    text = render(json.loads(SPEC.read_text(encoding="utf-8")))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run python scripts/render_api_reference.py",
                  file=sys.stderr)
            return 1
        print("API reference is current.")
        return 0
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
