[package]
name = "zrotext-migrator"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sha2 = "0.11.0"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "time"] }
tokio-postgres = "0.7.13"
zrotext-postgres-connection = { path = "../postgres-connection" }
