// SPDX-License-Identifier: AGPL-3.0-only
// Synthetic signed/HPKE bytes. No private custody, installed grant or current head.
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {canonicalSignature02,enrollRootPin02,verifyManifest02} from '../dist/draft02-manifest.js';
import {encodeContactReaderStatementUnsigned01,verifyContactReaderStatement01,verifiedContactReaderStatementIdentity01} from '../dist/contact-reader-statement.js';
import * as c from '../dist/contact-content-contract.js';
const enc=new TextEncoder(),hex=s=>new Uint8Array(Buffer.from(s,'hex')),join=(...ps)=>new Uint8Array(Buffer.concat(ps));
const vector=JSON.parse(await readFile(new URL('../../../protocol/v1/contact-content-contract-vectors.json',import.meta.url),'utf8'));
const fieldKeys=['kind','accountId','contactId','sealRevision','trustGeneration','manifestVersion','readerGeneration','readerId','manifestDigest','statementDigest','routingDigest','requestId','rootWriterId','encapsulation','ciphertext'];
const mutationKeys=['operation','accountId','contactId','expectedRevision','revision','requestId','previousDigest','trustGeneration','manifestVersion','manifestDigest','statementDigest','routingDigest','legacyGeneration','name','notes'];
const statementKeys=['authorizationId','accountId','origin','trustGeneration','manifestVersion','readerGeneration','rootFingerprint','manifestDigest','readerId','readerPoint','issuedMs','untilMs','capability'];
const unsigned=(p,keys)=>Object.fromEntries(keys.map(k=>[k,k==='name'||k==='notes'?{...p[k]}:p[k]]));
async function fixture(){const v=vector.reader_statement,trust=await enrollRootPin02(hex(v.root_pin_hex),hex(v.expected_root_fingerprint_hex)),manifest=await verifyManifest02(hex(v.accepted_manifest_hex),{...trust,version:6n,digest:hex(v.accepted_previous_digest_hex)},2000n),nextManifest=await verifyManifest02(hex(vector.successor_manifest_hex),{...trust,version:7n,digest:manifest.digest},2002n);
 const check=(bytes,acceptedManifest)=>verifyContactReaderStatement01({bytes,acceptedManifest,expectedAccountId:hex(v.account_hex),expectedOrigin:v.origin,expectedRootFingerprint:hex(v.expected_root_fingerprint_hex),comparison:'declared_issued_ms'}),statement=await check(hex(v.statement_hex),manifest),nextStatement=await check(hex(vector.successor_statement_hex),nextManifest),id=verifiedContactReaderStatementIdentity01(statement),scalar=new Uint8Array(32);scalar[31]=1;
 const b64=b=>Buffer.from(b).toString('base64url'),key=await crypto.subtle.importKey('jwk',{kty:'EC',crv:'P-256',x:b64(id.rootPoint.slice(1,33)),y:b64(id.rootPoint.slice(33)),d:b64(scalar)},{name:'ECDSA',namedCurve:'P-256'},false,['sign']);scalar.fill(0);
 const sign=async(b,domain)=>{const n=new Uint8Array(4);new DataView(n.buffer).setUint32(0,b.length);return join(b,canonicalSignature02(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,join(enc.encode(domain+'\0'),n,b)))));};
 const scope={expectedContactId:hex(vector.contact_hex),expectedRoutingDigest:hex(vector.routing_digest_hex)},field=(bytes,selected=statement)=>c.verifyContactField01({bytes,statement:selected,...scope}),mutation=(bytes,selected=statement,legacy=0n)=>c.verifyContactMutation01({bytes,statement:selected,...scope,expectedLegacyGeneration:legacy});
 const name=await field(hex(vector.name_hex)),notes=await field(hex(vector.notes_hex)),replacement=await field(hex(vector.replacement_notes_hex),nextStatement),create=await mutation(hex(vector.create_hex)),update=await mutation(hex(vector.update_hex),nextStatement),cleared=await mutation(hex(vector.clear_hex),nextStatement),first=c.verifyContactTransition01({previous:null,next:create,replacementFields:[name,notes]}),second=c.verifyContactTransition01({previous:first,next:update,replacementFields:[replacement]}),last=c.verifyContactTransition01({previous:second,next:cleared,replacementFields:[]});
 return {scope,trust,manifest,nextManifest,check,statement,nextStatement,name,notes,replacement,create,update,cleared,first,second,last,field,mutation,sign,
  changedStatement:async(selected,changes,accepted)=>check(await sign(encodeContactReaderStatementUnsigned01({...unsigned(verifiedContactReaderStatementIdentity01(selected),statementKeys),...changes}),'ZT/contact-reader/authorization/v1'),accepted),
  changedMutation:async(p,changes,selected=nextStatement,legacy=0n)=>mutation(await sign(c.encodeContactMutationUnsigned01({...unsigned(p,mutationKeys),...changes}),'ZT/contact-field/mutation/v1'),selected,legacy),
  changedField:async(p,changes,selected=statement)=>field(await sign(c.encodeContactFieldUnsigned01({...unsigned(p,fieldKeys),...changes}),'ZT/contact-field/commitment/v1'),selected)};
}
test('shared actual signed HPKE vectors validate creation reader transition retain and clear',async()=>{const f=await fixture();for(const[m,key]of[[f.create,'create_digest_hex'],[f.update,'update_digest_hex'],[f.cleared,'clear_digest_hex']])assert.deepEqual(c.verifiedContactMutationIdentity01(m).digest,hex(vector[key]));assert.equal(c.verifiedContactTransitionIdentity01(f.last).revision,3n);assert.equal(c.verifiedContactTransitionIdentity01(f.last).name.tag,0);assert.equal(c.verifiedContactTransitionIdentity01(f.second).name.sealRevision,1n);assert.deepEqual(c.verifiedContactTransitionIdentity01(f.second).notes.digest,c.verifiedContactFieldIdentity01(f.replacement).digest);assert.deepEqual(f.last,{kind:'historical_integrity',entity:'transition'});});
test('owned brands refuse clones and defensive copies cannot replace internal prior slots',async()=>{const f=await fixture();for(const[result,get]of[[f.name,c.verifiedContactFieldIdentity01],[f.create,c.verifiedContactMutationIdentity01],[f.first,c.verifiedContactTransitionIdentity01]]){assert.throws(()=>get({...result}));const id=get(result);id.bytes.fill(0);id.digest.fill(0);assert.notEqual(get(result).bytes[0],0);}const p=c.verifiedContactTransitionIdentity01(f.first);p.name.digest.fill(0);assert.equal(c.verifyContactTransition01({previous:f.first,next:f.update,replacementFields:[f.replacement]}).kind,'historical_integrity');assert.throws(()=>c.verifyContactTransition01({previous:f.create,next:f.update,replacementFields:[f.replacement]}));});
test('replacement arrays are finite closed distinct exact used fields without getters',async()=>{const f=await fixture();for(const replacementFields of[[f.name,f.notes,f.replacement],[f.name,f.name],[f.notes],[f.name],[f.name,f.replacement],[]])assert.throws(()=>c.verifyContactTransition01({previous:f.first,next:f.update,replacementFields}));assert.throws(()=>c.verifyContactTransition01({previous:f.second,next:f.cleared,replacementFields:[f.notes]}));const a=[f.replacement];Object.defineProperty(a,'0',{get(){throw Error('Must not invoke caller getter');}});assert.throws(()=>c.verifyContactTransition01({previous:f.first,next:f.update,replacementFields:a}),/Contact content refused/);});
test('clear and replacement cannot resurrect old field by later retained digest',async()=>{const f=await fixture(),p=c.verifiedContactTransitionIdentity01(f.last),old=c.verifiedContactTransitionIdentity01(f.first),resurrect=await f.changedMutation(p,{expectedRevision:3n,revision:4n,previousDigest:p.digest,name:{...old.name}});assert.throws(()=>c.verifyContactTransition01({previous:f.last,next:resurrect,replacementFields:[]}));const second=c.verifiedContactTransitionIdentity01(f.second),replaced=await f.changedMutation(second,{expectedRevision:2n,revision:3n,previousDigest:second.digest,notes:{...old.notes}});assert.throws(()=>c.verifyContactTransition01({previous:f.second,next:replaced,replacementFields:[]}));});
test('authentic wrong predecessor skipped identity scope and kind substitutions have no transition',async()=>{const f=await fixture();assert.throws(()=>c.verifyContactTransition01({previous:null,next:f.update,replacementFields:[f.replacement]}));assert.throws(()=>c.verifyContactTransition01({previous:f.first,next:f.cleared,replacementFields:[]}));const p=c.verifiedContactMutationIdentity01(f.update);for(const change of[{previousDigest:new Uint8Array(32).fill(9)},{name:{...p.notes},notes:{...p.name}}]){const m=await f.changedMutation(p,change);assert.throws(()=>c.verifyContactTransition01({previous:f.first,next:m,replacementFields:[f.replacement]}));}for(const change of[{contactId:new Uint8Array(16).fill(9)},{routingDigest:new Uint8Array(32).fill(9)},{statementDigest:new Uint8Array(32).fill(9)}])await assert.rejects(f.changedMutation(p,change));});
test('replacement signature alone cannot change request or successor field bindings',async()=>{const f=await fixture(),p=c.verifiedContactFieldIdentity01(f.replacement),m=c.verifiedContactMutationIdentity01(f.update);for(const change of[{requestId:new Uint8Array(16).fill(9)},{sealRevision:1n},{kind:1}]){const field=await f.changedField(p,change,f.nextStatement),id=c.verifiedContactFieldIdentity01(field),next=await f.changedMutation(m,{notes:{tag:1,sealRevision:2n,digest:id.digest}});assert.throws(()=>c.verifyContactTransition01({previous:f.first,next,replacementFields:[field]}));}});
test('statement substitution same scope and lower accepted history cannot become a successor',async()=>{const f=await fixture();await assert.rejects(f.mutation(hex(vector.update_hex),f.statement));const p=c.verifiedContactTransitionIdentity01(f.last),base=c.verifiedContactMutationIdentity01(f.create);const lower=await f.changedMutation(base,{operation:2,expectedRevision:3n,revision:4n,previousDigest:p.digest,name:{...p.name},notes:{...p.notes}},f.statement);assert.throws(()=>c.verifyContactTransition01({previous:f.last,next:lower,replacementFields:[]}));});
test('genuinely accepted same-version fork and equal-generation replacement reader cannot advance history',async()=>{
 const f=await fixture(),old=c.verifiedContactMutationIdentity01(f.create),changes={operation:2,expectedRevision:1n,revision:2n,previousDigest:old.digest};
 const ordinary=await f.changedMutation(old,changes,f.statement);
 assert.equal(c.verifyContactTransition01({previous:f.first,next:ordinary,replacementFields:[]}).kind,'historical_integrity');
 const forkBytes=f.manifest.bytes.slice(0,-64),view=new DataView(forkBytes.buffer);view.setBigUint64(45,f.manifest.expiresMs-1n);
 const forkManifest=await verifyManifest02(await f.sign(forkBytes,'ZTSE/manifest/v2'),{...f.trust,version:6n,digest:hex(vector.reader_statement.accepted_previous_digest_hex)},2000n);
 assert.equal(forkManifest.version,f.manifest.version);assert.notDeepEqual(forkManifest.digest,f.manifest.digest);
 const forkStatement=await f.changedStatement(f.statement,{manifestDigest:forkManifest.digest},forkManifest),forkId=verifiedContactReaderStatementIdentity01(forkStatement);
 const fork=await f.changedMutation(old,{...changes,manifestDigest:forkId.manifestDigest,statementDigest:forkId.digest},forkStatement);
 assert.throws(()=>c.verifyContactTransition01({previous:f.first,next:fork,replacementFields:[]}));
 const reusedGeneration=await f.changedStatement(f.nextStatement,{readerGeneration:1n},f.nextManifest),id=verifiedContactReaderStatementIdentity01(reusedGeneration);
 assert.notDeepEqual(id.readerId,verifiedContactReaderStatementIdentity01(f.statement).readerId);
 const switched=await f.changedMutation(old,{...changes,manifestVersion:id.manifestVersion,manifestDigest:id.manifestDigest,statementDigest:id.digest},reusedGeneration);
 assert.throws(()=>c.verifyContactTransition01({previous:f.first,next:switched,replacementFields:[]}));
});
test('slot zero sentinels integer bounds and unsigned data shape cannot acquire a verification brand',async()=>{
 const f=await fixture(),m=c.verifiedContactMutationIdentity01(f.create),q=c.verifiedContactFieldIdentity01(f.name);
 for(const name of [{tag:0,sealRevision:1n,digest:new Uint8Array(32)},{tag:0,sealRevision:0n,digest:new Uint8Array(32).fill(1)},{tag:1,sealRevision:0n,digest:m.name.digest},{tag:1,sealRevision:1n,digest:new Uint8Array(32)},{tag:2,sealRevision:1n,digest:m.name.digest},{...m.name,extra:true}])assert.throws(()=>c.encodeContactMutationUnsigned01({...unsigned(m,mutationKeys),name}));
 for(const change of [{sealRevision:0n},{sealRevision:1n<<63n},{readerGeneration:0n},{ciphertext:new Uint8Array(16)},{ciphertext:new Uint8Array(273)},{accountId:new Uint8Array(16)},{extra:true}])assert.throws(()=>c.encodeContactFieldUnsigned01({...unsigned(q,fieldKeys),...change}));
 for(const kind of [1,2])for(const n of [17,kind===1?272:2064])assert.equal(c.encodeContactFieldUnsigned01({...unsigned(q,fieldKeys),kind,ciphertext:new Uint8Array(n)}).length,315+n);
 await assert.rejects(c.verifyContactField01({bytes:q.bytes,statement:{...f.statement},...f.scope}));
 const input={bytes:q.bytes,statement:f.statement,...f.scope};Object.defineProperty(input,'bytes',{get(){throw Error('Caller getter must not execute');}});
 await assert.rejects(c.verifyContactField01(input),/Contact content refused/);
});
test('create update conversion legacy semantics and MAX are closed',async()=>{const f=await fixture(),p=c.verifiedContactMutationIdentity01(f.create),converted=await f.changedMutation(p,{operation:3,legacyGeneration:7n},f.statement,7n);assert.equal(c.verifyContactTransition01({previous:null,next:converted,replacementFields:[f.name,f.notes]}).kind,'historical_integrity');await assert.rejects(f.mutation(c.verifiedContactMutationIdentity01(converted).bytes,f.statement,6n));for(const change of[{legacyGeneration:1n},{operation:3,legacyGeneration:0n},{previousDigest:new Uint8Array(32).fill(1)},{expectedRevision:1n},{revision:0n},{trustGeneration:2n},{operation:2,expectedRevision:(1n<<63n)-1n,revision:1n,previousDigest:new Uint8Array(32).fill(1)}])assert.throws(()=>c.encodeContactMutationUnsigned01({...unsigned(p,mutationKeys),...change}));});
test('parsers reject exact lengths trailing data highS offcurve and ciphertext aliases',async()=>{const f=await fixture();for(const b of[hex(vector.name_hex).slice(1),join(hex(vector.name_hex),Uint8Array.of(0)),new Uint8Array(2444)])await assert.rejects(c.parseContactField01(b));for(const b of[hex(vector.create_hex).slice(1),join(hex(vector.create_hex),Uint8Array.of(0))])assert.throws(()=>c.parseContactMutation01(b));const p=c.verifiedContactFieldIdentity01(f.name),point=new Uint8Array(65);point[0]=4;const off=await f.sign(c.encodeContactFieldUnsigned01({...unsigned(p,fieldKeys),encapsulation:point}),'ZT/contact-field/commitment/v1');await assert.rejects(c.parseContactField01(off));const bad=hex(vector.name_hex);new DataView(bad.buffer).setUint32(311,17);await assert.rejects(c.parseContactField01(bad));const order=0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551n,b=hex(vector.create_hex);let high=order-BigInt('0x'+Buffer.from(b.slice(-32)).toString('hex'));for(let at=b.length-1;at>=b.length-32;at--){b[at]=Number(high&255n);high>>=8n;}assert.throws(()=>c.parseContactMutation01(b));});
test('signed ciphertext or domain substitution refuses and inputs are captured before awaits',async()=>{const f=await fixture(),p=c.verifiedContactFieldIdentity01(f.name),wrong=await f.sign(c.encodeContactFieldUnsigned01(unsigned(p,fieldKeys)),'ZT/contact-field/mutation/v1');await assert.rejects(f.field(wrong));const changed=hex(vector.name_hex);changed[315]^=1;await assert.rejects(f.field(changed));const b=hex(vector.name_hex),contact=f.scope.expectedContactId.slice(),routing=f.scope.expectedRoutingDigest.slice(),pending=c.verifyContactField01({bytes:b,statement:f.statement,expectedContactId:contact,expectedRoutingDigest:routing});b.fill(0);contact.fill(0);routing.fill(0);assert.equal((await pending).kind,'historical_integrity');});
