// SPDX-License-Identifier: AGPL-3.0-only
import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { lookup } from 'node:dns/promises';
import { createHash } from 'node:crypto';
import { validateReady,parseNativeResult,nativeRequest,verifyIndependentScope,fixtureControl,allowFrontendRequest,fixtureFrontendHandler } from './conversation-setup-server-orchestration.mjs';
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const origin='https://owner.example.test:4443';
const hash=b=>createHash('sha256').update(b).digest('hex');
function ready(){const paired=Buffer.alloc(65);paired[0]=4;return {version:1,synthetic:true,port:4444,controlToken:'07'.repeat(32),origin,baseline:{accountId:id,userId:id,sessionId:id,deviceId:id,lineId:id,nextGeneration:'1',pairedPoint:paired.toString('hex'),pairedFingerprintHex:hash(paired),rootFactor:'fixture-factor'.padEnd(26,'x'),lineFactor:'fixture-factor'.padEnd(26,'y'),cookies:[{name:'__Host-zrotext_session',value:'fixture-session'},{name:'__Host-zrotext_csrf',value:'fixture-csrf'}],lease:{connectionEpoch:'1',deploymentEpoch:'1',siteId:'fixture-site',instanceId:'fixture-instance'}}};}
function artifacts(){return {rootPin:'00'.repeat(94),rootFingerprint:'00'.repeat(32),bundleId:'11'.repeat(16),encryptedBackup:'00'.repeat(237),publicCard:'00'.repeat(134)};}
function result(operation='prepareRootFixture'){return {version:1,synthetic:true,operation,artifacts:artifacts(),...(operation==='signCustody'?{signatures:{enrollmentSignature:'01'.repeat(64),custodySignature:'02'.repeat(64)}}:operation==='signLineRegistration'?{signatures:{rootSignature:'03'.repeat(64)}}:{})};}
const encoded=value=>'\nZT_OWNER_SETUP_RESULT='+JSON.stringify(value)+'\ntest result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 20 filtered out; finished in 0.20s\n';
test('readiness freezes independently selected fixture baseline',()=>{const input=ready(),output=validateReady(input);input.baseline.cookies[0].value='changed';input.baseline.lease.siteId='changed';assert.equal(output.baseline.cookies[0].value,'fixture-session');assert.equal(output.baseline.lease.siteId,'fixture-site');});
test('the two actual completion steps cannot reuse one recovery factor',()=>{const r=ready();r.baseline.lineFactor=r.baseline.rootFactor;assert.throws(()=>validateReady(r));});
for(const [name,change]of [['real origin',r=>r.origin='https://example.com:4443'],['path',r=>r.origin+='/path'],['missing port',r=>r.origin='https://owner.invalid'],['zero generation',r=>r.baseline.nextGeneration='0'],['extra authority',r=>r.baseline.privateKey={}],['extra lease',r=>r.baseline.lease.privateKey={}],['wrong point hash',r=>r.baseline.pairedFingerprintHex='00'.repeat(32)],['bad factor',r=>r.baseline.rootFactor='short'],['bad cookie',r=>r.baseline.cookies[0].name='other'],['zero baseline',r=>r.baseline.accountId='00000000-0000-0000-0000-000000000000']])test('readiness refuses '+name,()=>{const r=ready();change(r);assert.throws(()=>validateReady(r));});
for(const operation of ['prepareRootFixture','signCustody','signLineRegistration'])test('parses exactly typed public native '+operation+' result',()=>{assert.deepEqual(parseNativeResult(encoded(result(operation)),operation),result(operation));});
for(const operation of ['prepareRootFixture','signCustody','signLineRegistration'])test('actual selected libtest prefix accepted only for '+operation,()=>{const selected=operation==='signLineRegistration'?'windows::line_key_registration::tests::native_console_registration_requires_independent_scope_and_fresh_publication':'windows::custody_sign::tests::native_console_custody_signs_only_reviewed_bundle';const output=encoded(result(operation)).replace('\nZT_OWNER_SETUP_RESULT=',`\ntest ${selected} ... ZT_OWNER_SETUP_RESULT=`);assert.deepEqual(parseNativeResult(output,operation),result(operation));assert.throws(()=>parseNativeResult(output.replace(selected,'wrong::test'),operation));assert.throws(()=>parseNativeResult(output.replace('1 passed; 0 failed','0 passed; 1 failed'),operation));assert.throws(()=>parseNativeResult(output.replace('0 ignored','1 ignored'),operation));});
for(const [name,output]of [['duplicate',encoded(result())+encoded(result())],['lookalike','prefix'+encoded(result()).trimStart()],['oversized','a'.repeat(65537)],['private token',encoded(result())+'ZTRK1-fixture'],['wrong operation',encoded(result('signCustody'))],['wrong synthetic',encoded({...result(),synthetic:false})],['extra material',encoded({...result(),privateKey:{}})],['noncanonical hex',encoded({...result(),artifacts:{...artifacts(),bundleId:'AA'.repeat(16)}})]])test('native output refuses '+name,()=>assert.throws(()=>parseNativeResult(output,'prepareRootFixture')));
test('native request carries public content only using existing exact operation',()=>{const request=nativeRequest('prepareRootFixture',{account:id,origin});assert.deepEqual(JSON.parse(Buffer.from(request,'hex')),{version:1,synthetic:true,operation:'prepareRootFixture',expected:{account:id,origin}});assert.throws(()=>nativeRequest('genericSign',{}));assert.throws(()=>nativeRequest('signCustody',{},artifacts(),new Uint8Array(8192)));});
function expected(){const r=ready();return {...r.baseline,origin,rootFingerprintHex:'07'.repeat(32),approvalFingerprintHex:'09'.repeat(32)};}
function scope(line=false){const e=expected();return {account:id,user:id,session:id,origin,rootFingerprint:e.rootFingerprintHex,challenge:other,nonce:'08'.repeat(32),issued:'1000',expires:'2000',...(line?{device:id,line:id,generation:'1',approvalFingerprint:e.approvalFingerprintHex,pairedSigningFingerprint:e.pairedFingerprintHex,connectionEpoch:'1',deploymentEpoch:'1',site:'fixture-site',instance:'fixture-instance'}:{})};}
test('DB scope remains independent of transcript and exact selected authority',()=>{const s=scope(true);assert.deepEqual(verifyIndependentScope(s,expected(),'line',other,1500),s);});
for(const name of ['account','user','session','rootFingerprint','device','line','generation','approvalFingerprint','pairedSigningFingerprint','connectionEpoch','deploymentEpoch','site','instance'])test('scope substitution '+name+' is refused before native signing',()=>{const s=scope(true);s[name]='substituted';assert.throws(()=>verifyIndependentScope(s,expected(),'line',other,1500));});
for(const now of [999,2000])test('DB scope outside exact time window '+now+' is refused',()=>assert.throws(()=>verifyIndependentScope(scope(),expected(),'root',other,now)));
test('zero nonce and excessive lifetime are refused',()=>{const s=scope();s.nonce='00'.repeat(32);assert.throws(()=>verifyIndependentScope(s,expected(),'root',other,1500));s.nonce='08'.repeat(32);s.expires='301001';assert.throws(()=>verifyIndependentScope(s,expected(),'root',other,1500));});
test('frontend passes only actual product paths with exact host and no fixture token',()=>{assert.equal(allowFrontendRequest(origin,'/v1/auth/sealed-root',{host:'owner.example.test:4443'}),true);for(const path of ['/__fixture/owner-setup','/%5f%5ffixture/owner-setup','/owner/../__fixture/owner-setup','//elsewhere.invalid/path','/%ZZ'])assert.equal(allowFrontendRequest(origin,path,{host:'owner.example.test:4443'}),false);assert.equal(allowFrontendRequest(origin,'/owner/conversation',{host:'elsewhere.invalid'}),false);assert.equal(allowFrontendRequest(origin,'/owner/conversation',{host:'owner.example.test:4443','x-zrotext-fixture-token':'fixture'}),false);});
test('actual loopback control transport uses fixed endpoint/token and validates response purpose',async()=>{
  let responseOperation='snapshot',big=false;const requests=[];
  const server=http.createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;requests.push({method:req.method,path:req.url,controlHeader:req.headers['x-zrotext-fixture-token'],body:JSON.parse(body)});res.writeHead(200,{'content-type':'application/json'});res.end(big?'x'.repeat(16385):JSON.stringify({version:1,synthetic:true,operation:responseOperation,counters:{rootCompletions:0,lineRegistrations:0,lineApprovals:0,phoneAcknowledgments:0}}));});
  const address=(await lookup('localhost',{family:4})).address;await new Promise(resolve=>server.listen(0,address,resolve));
  try{const r=ready();r.port=server.address().port;const call=fixtureControl(r);await call('snapshot');assert.deepEqual(requests,[{method:'POST',path:'/__fixture/owner-setup',controlHeader:r.controlToken,body:{version:1,operation:'snapshot'}}]);responseOperation='finish';await assert.rejects(call('snapshot'));big=true;await assert.rejects(call('snapshot'));await assert.rejects(call('root_sign_scope','not-a-uuid'));assert.equal(requests.length,3);}finally{await new Promise(resolve=>server.close(resolve));}
});
test('trickling control bytes cannot extend the absolute request deadline',async()=>{
  let writes=0,closed=false;const server=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'application/json'});res.write('{');writes++;const interval=setInterval(()=>{res.write(' ');writes++;},5);res.on('close',()=>{closed=true;clearInterval(interval);});});
  const address=(await lookup('localhost',{family:4})).address;await new Promise(resolve=>server.listen(0,address,resolve));
  try{const r=ready();r.port=server.address().port;await assert.rejects(fixtureControl(r,{timeoutMs:50})('snapshot'));for(let i=0;i<20&&!closed;i++)await new Promise(resolve=>setTimeout(resolve,5));assert.ok(writes>1,'Bytes really trickled while the request was held');assert.equal(closed,true,'Owned connection closed at the absolute deadline');}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
});
test('real proxy handler closes a trickling product response at its absolute deadline',async()=>{
  let writes=0,closed=false;const backend=http.createServer((req,res)=>{res.writeHead(200);res.write('fixture');writes++;const interval=setInterval(()=>{res.write(' ');writes++;},5);res.on('close',()=>{closed=true;clearInterval(interval);});});
  const address=(await lookup('localhost',{family:4})).address;await new Promise(resolve=>backend.listen(0,address,resolve));const r=ready();r.port=backend.address().port;
  // HTTP here isolates the handler's deadline; real consumption constructs HTTPS.
  const frontend=http.createServer(fixtureFrontendHandler(r,{timeoutMs:50}));await new Promise(resolve=>frontend.listen(0,address,resolve));
  try{let received=0;await new Promise((resolve,reject)=>{const request=http.get({hostname:'localhost',family:4,agent:false,port:frontend.address().port,path:'/v1/auth/sealed-root',headers:{host:'owner.example.test:4443'}},response=>{response.on('data',chunk=>{received+=chunk.length;});response.on('aborted',resolve);response.on('error',resolve);response.on('end',()=>reject(Error('Trickle unexpectedly completed')));});request.on('error',resolve);});for(let i=0;i<20&&!closed;i++)await new Promise(resolve=>setTimeout(resolve,5));assert.ok(received>0&&writes>1);assert.equal(closed,true);}finally{frontend.closeAllConnections();backend.closeAllConnections();await Promise.all([new Promise(resolve=>frontend.close(resolve)),new Promise(resolve=>backend.close(resolve))]);}
});
