// SPDX-License-Identifier: AGPL-3.0-only
import test from "node:test";import assert from "node:assert/strict";
import {encodeConversationGenesisProposal02,createConversationGenesis02} from "../dist/conversation-genesis-proposal.js";
import {refreshFixture,join,signFixtureSuccessor02} from "./conversation-refresh-fixture.mjs";
import {enrollRootPin02,verifyManifest02} from "../dist/draft02-manifest.js";
import {genesisFixture} from "./conversation-genesis-fixture.mjs";
import {verifyPhoneKeyExport02,verifyArchivePublicHeader02} from "../dist/conversation-genesis-proposal.js";
import {createHash} from "node:crypto";import {readFile} from "node:fs/promises";
test("genesis public codec matches durable synthetic offline vector",async()=>{const f=await genesisFixture(),p=await encodeConversationGenesisProposal02(f.input),v=JSON.parse(await readFile(new URL("../../../protocol/v1/vectors/conversation-genesis-01.json",import.meta.url),"utf8"));assert.equal(Buffer.from(p.unsigned).toString("hex"),v.unsignedManifest);assert.equal(Buffer.from(p.proposal).toString("hex"),v.proposal);});
test("phone key identity matching never replaces independent fingerprint comparison",async()=>{const f=await genesisFixture(),s=f.input.selection,gen=new Uint8Array(8);new DataView(gen.buffer).setBigUint64(0,s.generation);const bytes=join(Uint8Array.of(90,84,80,75,1),s.account,s.device,s.line,s.phoneSigningFingerprint,gen,f.input.phoneReaderPoint,f.input.phoneSignerPoint),fp=new Uint8Array(createHash("sha256").update(join(new TextEncoder().encode("ZTSE/phone-keys/v1\0"),bytes)).digest());assert.deepEqual((await verifyPhoneKeyExport02(bytes,s,fp)).phoneReaderPoint,f.input.phoneReaderPoint);await assert.rejects(verifyPhoneKeyExport02(bytes,s,new Uint8Array(32).fill(9)));for(const field of ["account","device","line","phoneSigningFingerprint"])await assert.rejects(verifyPhoneKeyExport02(bytes,{...s,[field]:new Uint8Array(16).fill(9)},fp));for(const at of [0,5,21,37,53,85,93,158,222]){const changed=Uint8Array.from(bytes);changed[at]^=1;await assert.rejects(verifyPhoneKeyExport02(changed,s,fp));}});
test("archive public header requires independent receipt but proves no decryption",async()=>{const {archiveFixture}=await import("./conversation-archive-fixture.mjs"),f=await archiveFixture(),o=f.options;assert.deepEqual(await verifyArchivePublicHeader02(o.encrypted,o.binding.account,o.comparedRootFingerprint,o.origin,o.binding.archiveReader),f.predecessor.keys.find(k=>k.role===2).point);for(const at of [0,22,38,46,78,110,175,177]){const changed=Uint8Array.from(o.encrypted);changed[at]^=1;await assert.rejects(verifyArchivePublicHeader02(changed,o.binding.account,o.comparedRootFingerprint,o.origin,o.binding.archiveReader));}await assert.rejects(verifyArchivePublicHeader02(o.encrypted,o.binding.account,o.comparedRootFingerprint,o.origin,new Uint8Array(32).fill(9)));});
test("genesis public review encodes exact root-bound canonical roles and zero anchor",async()=>{const f=await genesisFixture(),p=await encodeConversationGenesisProposal02(f.input);assert.deepEqual(p.proposal.subarray(0,5),Uint8Array.of(90,84,67,71,1));const accepted=await verifyManifest02(await signFixtureSuccessor02(f.f,p.unsigned),await enrollRootPin02(f.input.rootPin,f.input.comparedRootFingerprint),f.input.nowMs);assert.equal(accepted.version,1n);assert.deepEqual(accepted.previousDigest,new Uint8Array(32));assert.deepEqual(accepted.keys.map(k=>[k.role,k.scope,k.state]),[[1,4,1],[2,12,1],[4,2,1],[6,0,1]]);assert.deepEqual(accepted.keys[0].deviceId,f.input.selection.device);assert.deepEqual(accepted.keys[2].lineId,f.input.selection.line);assert.deepEqual(accepted.keys[1].deviceId,new Uint8Array(16));});
test("genesis owner decision existing custodian and CAS install are one-shot",async()=>{const f=await genesisFixture(),flow=f.create();assert.equal(f.state.signs,0);assert.equal((await flow.provision()).version,1n);assert.equal(f.state.decisions,1);assert.equal(f.state.signs,1);assert.equal(f.state.installs,1);await assert.rejects(flow.provision(),/consumed/);});
test("independent root account and public points cannot be substituted",async()=>{const f=await genesisFixture();for(const change of [{comparedRootFingerprint:new Uint8Array(32).fill(9)},{selection:{...f.input.selection,account:new Uint8Array(16).fill(9)}},{phoneSignerPoint:f.input.phoneReaderPoint},{archiveReaderPoint:new Uint8Array(65)},{origin:"https://owner.invalid/"},{expiresMs:f.input.nowMs},{expiresMs:f.input.nowMs+86400001n}])await assert.rejects(encodeConversationGenesisProposal02({...f.input,...change}));});
test("session device line key binding authority loss and expiry around signing block installation",async()=>{for(const stage of ["decision","sign"]){for(const field of ["ownerSessionLive","authorityLive","deviceKeyLive","lineBindingLive","session","device","line","phoneSigningFingerprint","generation","version","nowMs","manifest"]){const f=await genesisFixture(),mutate=()=>{if(field.endsWith("Live"))f.state.current={...f.state.current,[field]:false};else if(["session","device","line","phoneSigningFingerprint","generation"].includes(field))f.state.current={...f.state.current,selection:{...f.state.current.selection,[field]:field==="generation"?2n:new Uint8Array(16).fill(9)}};else f.state.current={...f.state.current,[field]:field==="version"?1n:field==="nowMs"?f.input.expiresMs:new Uint8Array(1)};};const flow=f.create(stage==="decision"?{decide:async()=>mutate()}:{sign:async r=>{const bytes=await signFixtureSuccessor02(f.f,r.unsigned);mutate();return bytes.slice(-64);}});await assert.rejects(flow.provision(),/authority/);assert.equal(f.state.installs,0,`${stage}/${field}`);}}});
test("invalid signature failed install and installed fork never yield authority",async()=>{let f=await genesisFixture();await assert.rejects(f.create({sign:async()=>new Uint8Array(64)}).provision());assert.equal(f.state.installs,0);f=await genesisFixture();await assert.rejects(f.create({install:async()=>{throw Error("CAS lost");}}).provision(),/CAS lost/);f=await genesisFixture();await assert.rejects(f.create({install:async()=>{f.state.current={...f.state.current,version:1n,manifest:f.f.predecessor.bytes};}}).provision());});
test("mutating caller or review buffers cannot change root approved installation",async()=>{const f=await genesisFixture(),original=Uint8Array.from(f.input.selection.session),flow=f.create({decide:async r=>{r.unsigned.fill(0);r.proposal.fill(0);f.input.selection.session.fill(9);f.state.current={...f.state.current,selection:{...f.state.current.selection,session:original}};}});assert.equal((await flow.provision()).version,1n);});
