// SPDX-License-Identifier: AGPL-3.0-only
import {createECDH} from "node:crypto";import {keyId} from "../dist/draft01.js";
import test from "node:test";import assert from "node:assert/strict";
import {prepareConversationCustody02} from "../dist/conversation-custody.js";
import {unlockExistingArchive02} from "../dist/conversation-archive-custody.js";
import {archiveFixture} from "./conversation-archive-fixture.mjs";
import {verifyManifest02,verifiedManifestTrust02,canonicalSignature02} from "../dist/draft02-manifest.js";
import {join,signFixtureSuccessor02} from "./conversation-refresh-fixture.mjs";
test("existing archive decrypts to nonextractable memory lease with explicit accountwide decision",async()=>{const f=await archiveFixture(),lease=await unlockExistingArchive02(f.options);try{assert.equal(f.state.decisions,1);await lease.withKey(f.options.binding,async key=>{assert.equal(key.extractable,false);assert.equal(key.algorithm.name,"ECDH");await assert.rejects(crypto.subtle.exportKey("jwk",key));});}finally{lease.close();}await assert.rejects(lease.withKey(f.options.binding,async()=>{}),/unavailable/);});
test("wrong recovery and authenticated same-shape wrong scalar are refused",async()=>{let f=await archiveFixture();await assert.rejects(unlockExistingArchive02({...f.options,recovery:new Uint8Array(32).fill(9)}));f=await archiveFixture({scalar:2});await assert.rejects(unlockExistingArchive02(f.options),/actual point differs/);});
test("archive framing identity AAD and ciphertext mutations fail closed",async()=>{const f=await archiveFixture();for(const offset of [0,4,5,6,22,38,46,78,110,175,177,199,230,245,280,f.options.encrypted.length-1]){const encrypted=Uint8Array.from(f.options.encrypted);encrypted[offset]^=1;await assert.rejects(unlockExistingArchive02({...f.options,encrypted}));}for(const encrypted of [f.options.encrypted.subarray(0,-1),join(f.options.encrypted,Uint8Array.of(0)),new Uint8Array(846)])await assert.rejects(unlockExistingArchive02({...f.options,encrypted}));});
test("independent root origin selection and expiry substitutions are refused",async()=>{const f=await archiveFixture();for(const changed of [{origin:f.origin+"/"},{comparedRootFingerprint:new Uint8Array(32).fill(1)},{untilMs:f.nowMs},{untilMs:f.nowMs+1800001n},{binding:{...f.options.binding,session:new Uint8Array(16).fill(9)}}])await assert.rejects(unlockExistingArchive02({...f.options,...changed}));});
test("authority loss at every crypto publication checkpoint releases no lease",async()=>{for(let threshold=1;threshold<=6;threshold++){const f=await archiveFixture();let calls=0;await assert.rejects(unlockExistingArchive02({...f.options,readCurrent:async()=>++calls>=threshold?null:f.state.current}));}});
test("abort during explicit decision prevents late publication",async()=>{const f=await archiveFixture();await assert.rejects(unlockExistingArchive02({...f.options,consumeUnlockDecision:async()=>f.controller.abort()}),/closed/);});
test("session loss during archive operation blocks its plaintext and closes lease",async()=>{const f=await archiveFixture(),lease=await unlockExistingArchive02(f.options);await assert.rejects(lease.withKey(f.options.binding,async()=>{f.state.current=null;return "synthetic plaintext";}),/authority lost/);await assert.rejects(lease.withKey(f.options.binding,async()=>{}),/unavailable/);});
test("unsupported actual full point derivation has no advertised-point fallback",async()=>{const f=await archiveFixture(),saved=crypto.subtle.exportKey;crypto.subtle.exportKey=async()=>{throw Error("Synthetic export unavailable");};try{await assert.rejects(unlockExistingArchive02(f.options),/export unavailable/);}finally{crypto.subtle.exportKey=saved;}});
test("input mutation after admission cannot alter approved archive bytes or selection",async()=>{const f=await archiveFixture();const source={...f.options,recovery:Uint8Array.from(f.options.recovery),encrypted:Uint8Array.from(f.options.encrypted),binding:{...f.options.binding,session:Uint8Array.from(f.options.binding.session)}};source.consumeUnlockDecision=async()=>{source.encrypted.fill(0);source.recovery.fill(0);source.binding.session.fill(0);};const lease=await unlockExistingArchive02(source);lease.close();});

test("benign signed role5 renewal preserves existing archive lease",async()=>{const f=await archiveFixture(),lease=await unlockExistingArchive02(f.options);try{const next=await verifyManifest02(await signFixtureSuccessor02(f),verifiedManifestTrust02(f.predecessor,f.nowMs),f.nowMs);f.state.current={...f.state.current,manifest:next,nowMs:f.nowMs+1n};assert.equal(await lease.withKey(f.options.binding,async key=>key.extractable),false);}finally{lease.close();}});
test("current archive revocation blocks history even with matching old ciphertext",async()=>{const f=await archiveFixture(),lease=await unlockExistingArchive02(f.options);try{const unsigned=Uint8Array.from(f.review.unsigned),records=[];unsigned[151+149+148]=2;for(let at=151;at<unsigned.length;at+=149)records.push(unsigned.slice(at,at+149));const d=new Uint8Array(32);d[31]=6;const ecdh=createECDH("prime256v1");ecdh.setPrivateKey(d);d.fill(0);const point=new Uint8Array(ecdh.getPublicKey()),replacement=Uint8Array.from(records.find(r=>r[0]===2));replacement.set(await keyId(0x10,point),1);replacement.set(point,33);replacement[148]=1;records.push(replacement);records.sort((a,b)=>Buffer.compare(Buffer.from(a.subarray(0,33)),Buffer.from(b.subarray(0,33))));const header=unsigned.slice(0,151);header[150]=records.length;const next=await verifyManifest02(await signFixtureSuccessor02(f,join(header,...records)),verifiedManifestTrust02(f.predecessor,f.nowMs),f.nowMs);f.state.current={...f.state.current,manifest:next};await assert.rejects(lease.withKey(f.options.binding,async()=>"synthetic old plaintext"),/reader unavailable/);await assert.rejects(lease.withKey(f.options.binding,async()=>{}),/unavailable/);}finally{lease.close();}});

test("lease close notifies every subscriber despite a throwing subscriber",async()=>{const f=await archiveFixture(),lease=await unlockExistingArchive02(f.options);let cleared=0;lease.onClose(()=>{throw Error("Synthetic subscriber failure");});lease.onClose(()=>cleared++);f.controller.abort();assert.equal(cleared,1);await assert.rejects(lease.withKey(f.options.binding,async()=>{}),/unavailable/);lease.close();assert.equal(cleared,1);});
test("actual bounded expiry closes key lease and notifies subscribers",async()=>{const f=await archiveFixture(),lease=await unlockExistingArchive02({...f.options,untilMs:f.nowMs+80n});let cleared=0;lease.onClose(()=>cleared++);try{await new Promise(resolve=>setTimeout(resolve,120));assert.equal(cleared,1);await assert.rejects(lease.withKey(f.options.binding,async()=>{}),/unavailable/);}finally{lease.close();}});

test("already aborted composed custody closes the supplied archive lease",async()=>{const f=await archiveFixture(),lease=await unlockExistingArchive02(f.options),controller=new AbortController();let closed=0;lease.onClose(()=>closed++);controller.abort();await assert.rejects(prepareConversationCustody02({binding:f.options.binding,archiveLease:lease,signal:controller.signal}),/closed/);assert.equal(closed,1);});
