// SPDX-License-Identifier: AGPL-3.0-only
import test from "node:test";
import assert from "node:assert/strict";
import {encodeConversationRefreshProposal02} from "../dist/conversation-refresh-proposal.js";
import {refreshFixture} from "./conversation-refresh-fixture.mjs";
test("typed public file contains exact SDK-verified predecessor and reviewed unsigned successor",async()=>{const f=await refreshFixture(),b=await encodeConversationRefreshProposal02(f);assert.equal(Buffer.from(b.subarray(0,5)).toString("hex"),"5a54434601");let at=5;for(const name of ["account","session","interval","device","line"]){assert.deepEqual(b.subarray(at,at+16),f.review.binding[name]);at+=16;}assert.equal(new DataView(b.buffer).getBigUint64(at),1n);at+=8;const peerLength=b[at++];assert.equal(new TextDecoder().decode(b.subarray(at,at+peerLength)),"+12");at+=peerLength;const originLength=new DataView(b.buffer).getUint16(at);at+=2;assert.equal(new TextDecoder().decode(b.subarray(at,at+originLength)),f.origin);at+=originLength;assert.deepEqual(b.subarray(at,at+32),f.comparedRootFingerprint);at+=32;assert.equal(new DataView(b.buffer).getBigUint64(at),7n);at+=8;for(const expected of [f.review.predecessorDigest,f.review.binding.phoneReader,f.review.binding.archiveReader,f.review.keyId,f.review.publicPoint]){assert.deepEqual(b.subarray(at,at+expected.length),expected);at+=expected.length;}assert.equal(new DataView(b.buffer).getBigUint64(at),f.review.untilMs);at+=8;for(const expected of [f.predecessor.bytes,f.review.unsigned]){assert.equal(new DataView(b.buffer).getUint16(at),expected.length);at+=2;assert.deepEqual(b.subarray(at,at+expected.length),expected);at+=expected.length;}assert.equal(at,b.length);});
test("unverified predecessor and mismatched independent root are refused",async()=>{const f=await refreshFixture();await assert.rejects(encodeConversationRefreshProposal02({...f,predecessor:{...f.predecessor}}));await assert.rejects(encodeConversationRefreshProposal02({...f,comparedRootFingerprint:new Uint8Array(32).fill(8)}),/compared root/);});
test("unsigned authority substitution never produces an offline proposal",async()=>{const f=await refreshFixture();for(const offset of [5,21,29,45,53,85,150,151+149+140]){const unsigned=Uint8Array.from(f.review.unsigned);unsigned[offset]^=1;await assert.rejects(encodeConversationRefreshProposal02({...f,review:{...f.review,unsigned}}));}});
test("scope, reader, key and expiry substitution are refused",async()=>{const f=await refreshFixture();for(const review of [{...f.review,predecessorDigest:new Uint8Array(32).fill(8)},{...f.review,publicPoint:new Uint8Array(65)},{...f.review,untilMs:f.nowMs},{...f.review,successorVersion:9n},{...f.review,binding:{...f.review.binding,archiveReader:new Uint8Array(32).fill(8)}},{...f.review,binding:{...f.review.binding,line:new Uint8Array(16).fill(8)}}])await assert.rejects(encodeConversationRefreshProposal02({...f,review}));});
test("ambiguous or insecure offline origin is refused",async()=>{const f=await refreshFixture();const credentialOrigin=new URL(f.origin);credentialOrigin.username="name";await assert.rejects(encodeConversationRefreshProposal02({...f,origin:credentialOrigin.toString()}),/origin/);for(const origin of ["http://owner.invalid","https://owner.invalid/","https://owner.invalid/path","https://owner.invalid?x","https://owner.invalid#x","https://OWNER.invalid","https://owner.invalid:443"])await assert.rejects(encodeConversationRefreshProposal02({...f,origin}),/origin/);});
