// SPDX-License-Identifier: AGPL-3.0-only
import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { copyAcceptanceFixture, validateAcceptanceProviders, runSetupServerAcceptance } from './conversation-setup-server-browser.mjs';
const hash=(...parts)=>createHash('sha256').update(Buffer.concat(parts.map(p=>Buffer.from(p)))).digest('hex');
const id='11111111-1111-4111-8111-111111111111';
function fixture(){
  const rootPin=new Uint8Array(94);rootPin.set([90,84,82,80,2]);rootPin.set(Buffer.from(id.replaceAll('-',''),'hex'),5);Buffer.from(rootPin.buffer).writeBigUInt64BE(1n,21);rootPin[29]=4;
  const pairedPoint=new Uint8Array(65);pairedPoint[0]=4;pairedPoint[1]=1;
  return {fixtureOnly:true,origin:'https://setup-fixture.invalid',accountId:id,userId:id,sessionId:id,deviceId:id,lineId:id,backupId:id,nextGeneration:'1',rootPin,rootFingerprintHex:hash(Buffer.from('ZTSE/root-pin/v2\0'),rootPin),rootBackup:new Uint8Array(237),publicCard:new Uint8Array(134),pairedPoint,pairedFingerprintHex:hash(pairedPoint),rootFactor:'fixture-factor',lineFactor:'fixture-factor',cookies:[{name:'__Host-zrotext_session',value:'fixture-session'},{name:'__Host-zrotext_csrf',value:'fixture-csrf'}],lease:{connectionEpoch:'1',deploymentEpoch:'1',siteId:'fixture-site',instanceId:'fixture-instance'}};
}
test('copies public artifacts, cookies and independently provided lease before browser use',()=>{const source=fixture(),copied=copyAcceptanceFixture(source);source.rootPin[30]=7;source.cookies[0].value='changed';source.lease.siteId='changed';assert.equal(copied.rootPin[30],0);assert.equal(copied.cookies[0].value,'fixture-session');assert.equal(copied.cookies[0].secure,true);assert.equal(copied.lease.siteId,'fixture-site');});
test('unexpected nested lease material is refused',()=>{const f=fixture();f.lease.privateKey={};assert.throws(()=>copyAcceptanceFixture(f));});
for(const [name,mutate] of [
 ['not fixture',f=>f.fixtureOnly=false],['live hostname',f=>f.origin='https://example.com'],['HTTP',f=>f.origin='http://setup-fixture.invalid'],['origin path',f=>f.origin+='/path'],['userinfo',f=>f.origin='https://user@setup-fixture.invalid'],['root secret',f=>f.recoverySecret=new Uint8Array(32)],['wrong account',f=>f.accountId='22222222-2222-4222-8222-222222222222'],['root generation',f=>Buffer.from(f.rootPin.buffer).writeBigUInt64BE(2n,21)],['root fingerprint',f=>f.rootFingerprintHex='00'.repeat(32)],['paired fingerprint',f=>f.pairedFingerprintHex='00'.repeat(32)],['unbounded backup',f=>f.rootBackup=new Uint8Array(749)],['unbounded card',f=>f.publicCard=new Uint8Array(646)],['zero generation',f=>f.nextGeneration='0'],['overflow epoch',f=>f.lease.connectionEpoch='9223372036854775808'],['noncanonical epoch',f=>f.lease.connectionEpoch='01'],['wrong cookie',f=>f.cookies[0].name='other'],['newline factor',f=>f.lineFactor='fixture\n']
])test(name+' refuses before context or provider invocation',async()=>{let touched=0;const f=fixture();mutate(f);await assert.rejects(runSetupServerAcceptance({fixture:f,browser:{newContext(){touched++;throw Error('must not run');}},...Object.fromEntries(['signRootCustody','signLineRegistration','snapshot','submitPhoneProof','acknowledgePhone'].map(name=>[name,()=>{touched++;}]))}));assert.equal(touched,0);});
for(const name of ['browser','signRootCustody','signLineRegistration','snapshot','submitPhoneProof','acknowledgePhone'])test('missing '+name+' is a concrete fixture prerequisite',()=>{const input={browser:{newContext(){}},...Object.fromEntries(['signRootCustody','signLineRegistration','snapshot','submitPhoneProof','acknowledgePhone'].map(k=>[k,()=>{}]))};delete input[name];assert.throws(()=>validateAcceptanceProviders(input));});
test('runner keeps actual requests and external custody/phone providers separate',async()=>{const source=await readFile(new URL('./conversation-setup-server-browser.mjs',import.meta.url),'utf8');assert.ok(!/route\.fulfill|globalThis\.fetch\s*=|ZtConversationOwnerSetup\s*=|ZtConversationSimulatorAdapter\s*=|privateKey\s*:\s*|recoverySecret|readiness/.test(source));assert.ok(source.includes("headers.origin"));assert.ok(source.includes('input.signRootCustody'));assert.ok(source.includes('input.signLineRegistration'));assert.ok(source.includes('input.submitPhoneProof'));assert.ok(source.includes('input.acknowledgePhone'));assert.ok(source.includes('await context.close()'));});
