// SPDX-License-Identifier: AGPL-3.0-only
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {fileURLToPath} from 'node:url';
import {webcrypto,createHash} from 'node:crypto';
import {Aes128Gcm,CipherSuite,DhkemP256HkdfSha256,HkdfSha256} from '@hpke/core';
import {keyId} from '../dist/draft01.js';
import {canonicalSignature02,verifyManifest02} from '../dist/draft02-manifest.js';
import {sealEncryptedTemplate} from '../dist/encrypted-template.js';
import {OwnerEncryptedTemplateClient} from '../dist/owner-encrypted-template-client.js';
globalThis.crypto??=webcrypto;
const enc=new TextEncoder(),fixed=(v,n)=>new Uint8Array(n).fill(v);
const concat=(...parts)=>new Uint8Array(Buffer.concat(parts.map(p=>Buffer.from(p))));
const u64=n=>{const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,n);return b;};
const u32=n=>{const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n);return b;};
const hex=b=>Buffer.from(b).toString('hex');
export async function templateFixture(){
 const nowMs=1893500000000n,root=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
 const signer=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
 const suite=new CipherSuite({kem:new DhkemP256HkdfSha256(),kdf:new HkdfSha256(),aead:new Aes128Gcm()});
 const archive=await suite.kem.deriveKeyPair(fixed(34,32));
 const rootPoint=new Uint8Array(await crypto.subtle.exportKey('raw',root.publicKey)),signerPoint=new Uint8Array(await crypto.subtle.exportKey('raw',signer.publicKey)),readerPoint=new Uint8Array(await suite.kem.serializePublicKey(archive.publicKey));
 const account=fixed(1,16),device=fixed(2,16),line=fixed(3,16),zero16=new Uint8Array(16),zero32=new Uint8Array(32),reader=await keyId(16,readerPoint);
 const record=async(role,point,d,l,scope)=>concat(Uint8Array.of(role),await keyId(role===2?16:257,point),point,d,l,Uint8Array.of(0,scope),u64(nowMs-1000n),u64(nowMs+3600000n),Uint8Array.of(1));
 const unsigned=concat(enc.encode('ZTMA'),Uint8Array.of(2),account,u64(1n),u64(1n),u64(nowMs-1000n),u64(nowMs+3600000n),zero32,rootPoint,Uint8Array.of(3),await record(2,readerPoint,zero16,zero16,12),await record(4,signerPoint,device,line,2),await record(6,rootPoint,zero16,zero16,0));
 const signature=canonicalSignature02(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},root.privateKey,concat(enc.encode('ZTSE/manifest/v2\0'),u32(unsigned.length),unsigned))));
 const manifestBytes=concat(unsigned,signature),trust={accountId:account,generation:1n,rootPoint,version:0n,digest:zero32,anchorDigest:zero32},manifest=await verifyManifest02(manifestBytes,trust,nowMs);
 const binding={account,device,line,interval:fixed(4,16),session:fixed(6,16),generation:1n,peer:'+12',phoneReader:fixed(7,32),archiveReader:reader};
 const scope={accountId:account,deviceId:device,lineId:line,intervalId:binding.interval,templateId:fixed(5,16),bindingGeneration:1n,revision:1n,expiresMs:nowMs+300000n,trustGeneration:1n,manifestVersion:1n,peerDigest:new Uint8Array(createHash('sha256').update('+12').digest()),readerId:reader,manifestDigest:Uint8Array.from(manifest.digest)};
 const envelope=await sealEncryptedTemplate(manifest,scope,nowMs,{template:'Synthetic {{name}}',values:{name:'Example'}});
 return {binding,scope,envelope,manifest,manifestBytes,trust,nowMs,archive};
}
export const requestId='00000000-0000-0000-0000-000000000009';
export function templateHost(f,extra={}){return {enabled:true,origin:'https://gateway.invalid',binding:f.binding,templateId:f.scope.templateId,readCurrent:async()=>({binding:f.binding,manifest:f.manifest,nowMs:f.nowMs,ownerSessionLive:true,consentLive:true,phase:'active',validForMs:60000}),currentCsrf:()=> 'synthetic-csrf',consumeCiphertextReview:async()=>{},signal:new AbortController().signal,...extra};}
const write=f=>({requestId,expectedRevision:0,scope:f.scope,envelope:f.envelope});
const receipt=()=>new Response('{"revision":1}',{headers:{'content-type':'application/json'}});
const latest=f=>new Response(Uint8Array.from(f.envelope),{headers:{'content-type':'application/vnd.zrotext.workflow-template.v1'}});
if(process.argv[1]===fileURLToPath(import.meta.url)){
 test('dormant owner template client refuses without network or caller mutation',async()=>{const f=await templateFixture();let calls=0;const c=new OwnerEncryptedTemplateClient(templateHost(f,{enabled:false,fetchImpl:async()=>{calls++;return receipt();}}));await assert.rejects(c.prepareSave(write(f)));assert.equal(calls,0);});
 test('exact copied ciphertext and metadata review produces only saved revision acknowledgement',async()=>{const f=await templateFixture();const original=Uint8Array.from(f.envelope);let reviewed,request;const c=new OwnerEncryptedTemplateClient(templateHost(f,{consumeCiphertextReview:async r=>{reviewed=r;r.scope.templateId.fill(8);f.envelope.fill(0);f.scope.templateId.fill(9);},fetchImpl:async(u,o)=>{request={u,o};return receipt();}}));const ticket=await c.prepareSave(write(f));const result=await c.commit(ticket);assert.equal(result.state,'acknowledged_saved_revision');assert.equal(result.revision,1);assert.equal(result.encryptedDigest,hex(createHash('sha256').update(original).digest()));assert.deepEqual(new Uint8Array(request.o.body),original);assert.equal(request.o.credentials,'same-origin');assert.equal(request.o.redirect,'error');assert.equal(request.o.headers['x-zrotext-csrf'],'synthetic-csrf');assert.equal(reviewed.expectedRevision,0);assert.equal(c.pending(),null);c.close();});
 test('matching GET never acknowledges unknown POST and retry uses exact same identity and bytes',async()=>{const f=await templateFixture();let posts=0;const bodies=[];const c=new OwnerEncryptedTemplateClient(templateHost(f,{fetchImpl:async(u,o)=>{if(o.method==='GET')return latest(f);bodies.push({bytes:new Uint8Array(o.body),id:o.headers['idempotency-key']});if(++posts===1)throw new Error('synthetic-lost-response');return receipt();}}));const ticket=await c.prepareSave(write(f));await assert.rejects(c.commit(ticket),e=>e.state==='unknown');const observed=await c.verifyUnknown(ticket);assert.equal(observed.requestAcknowledged,false);assert.equal(observed.matchesPending,true);assert.ok(c.pending());await assert.rejects(c.prepareSave({...write(f),requestId:'00000000-0000-0000-0000-000000000010'}));await c.retryUnknown(ticket);assert.equal(posts,2);assert.deepEqual(bodies[0],bodies[1]);assert.equal(c.pending(),null);c.close();});
 test('revocation after response bytes fences acknowledgements and closes current authority',async()=>{const f=await templateFixture();let live=true;const options=templateHost(f,{readCurrent:async()=>({...await templateHost(f).readCurrent(),ownerSessionLive:live}),fetchImpl:async()=>{live=false;return receipt();}});const c=new OwnerEncryptedTemplateClient(options);const ticket=await c.prepareSave(write(f));await assert.rejects(c.commit(ticket),e=>e.state==='unknown');assert.ok(c.pending());await assert.rejects(c.readLatest());});
 test('plain forged or mutated public manifests cannot grant template scope',async()=>{const f=await templateFixture();for(const manifest of [{...f.manifest},{...f.manifest,rootPoint:fixed(1,65)}]){const c=new OwnerEncryptedTemplateClient(templateHost(f,{readCurrent:async()=>({...await templateHost(f).readCurrent(),manifest})}));await assert.rejects(c.prepareSave(write(f)));c.close();}const original=f.manifest.rootPoint;f.manifest.rootPoint=fixed(8,65);const c=new OwnerEncryptedTemplateClient(templateHost(f,{fetchImpl:async()=>receipt()}));const t=await c.prepareSave(write(f));await c.commit(t);f.manifest.rootPoint=original;c.close();});
 test('host and review waits obey original absolute deadline and reject late output',async()=>{const f=await templateFixture();for(const boundary of ['readCurrent','consumeCiphertextReview','currentCsrf']){let release;const held=new Promise(r=>{release=r;});let calls=0;const c=new OwnerEncryptedTemplateClient(templateHost(f,{timeoutMs:25,[boundary]:()=>held,fetchImpl:async()=>{calls++;return receipt();}}));const start=performance.now();await assert.rejects(c.prepareSave(write(f)));assert.ok(performance.now()-start<1000);release(boundary==='readCurrent'?await templateHost(f).readCurrent():boundary==='currentCsrf'?'synthetic-csrf':undefined);await new Promise(r=>setTimeout(r,10));assert.equal(calls,0);c.close();}});
 test('idle ticket expiry never renews and no POST occurs after close or abort',async()=>{const f=await templateFixture();let calls=0;const c=new OwnerEncryptedTemplateClient(templateHost(f,{timeoutMs:80,fetchImpl:async()=>{calls++;return receipt();}}));const t=await c.prepareSave(write(f));await new Promise(r=>setTimeout(r,100));await assert.rejects(c.commit(t));assert.equal(calls,0);const abort=new AbortController();const d=new OwnerEncryptedTemplateClient(templateHost(f,{signal:abort.signal,fetchImpl:async()=>{calls++;return receipt();}}));const dt=await d.prepareSave(write(f));abort.abort();await assert.rejects(d.commit(dt));assert.equal(calls,0);});
 test('unknown response and bounded body never discard ambiguous identity',async()=>{const f=await templateFixture();for(const body of ['{"revision":1,"revision":1}','{"revision":2}','{"revision":1,"send":true}','x'.repeat(257)]){const c=new OwnerEncryptedTemplateClient(templateHost(f,{fetchImpl:async()=>new Response(body,{headers:{'content-type':'application/json'}})}));const t=await c.prepareSave(write(f));await assert.rejects(c.commit(t),e=>e.state==='unknown');assert.ok(c.pending());c.close();}});
 test('latest head observation rejects delayed older revision and preserves unknown on refusal',async()=>{const f=await templateFixture();const second={...f.scope,revision:2n};const newer=await sealEncryptedTemplate(f.manifest,second,f.nowMs,{template:'Synthetic newer',values:{}});let n=0;const c=new OwnerEncryptedTemplateClient(templateHost(f,{fetchImpl:async()=>new Response(n++===0?newer:f.envelope,{headers:{'content-type':'application/vnd.zrotext.workflow-template.v1'}})}));assert.equal((await c.readLatest()).scope.revision,2n);await assert.rejects(c.readLatest());c.close();let posts=0;const d=new OwnerEncryptedTemplateClient(templateHost(f,{fetchImpl:async()=>{if(++posts===1)throw new Error('lost');return new Response('',{status:409});}}));const t=await d.prepareSave(write(f));await assert.rejects(d.commit(t),e=>e.state==='unknown');await assert.rejects(d.retryUnknown(t),e=>e.state==='unknown');assert.ok(d.pending());d.close();});
 test('CSRF changes and foreign scope refuse before mutation and expired reads never publish',async()=>{const f=await templateFixture();let csrf='synthetic-csrf',calls=0;const c=new OwnerEncryptedTemplateClient(templateHost(f,{currentCsrf:()=>csrf,consumeCiphertextReview:async()=>{csrf='changed-csrf';},fetchImpl:async()=>{calls++;return receipt();}}));await assert.rejects(c.prepareSave(write(f)));assert.equal(calls,0);const d=new OwnerEncryptedTemplateClient(templateHost(f));await assert.rejects(d.prepareSave({...write(f),scope:{...f.scope,intervalId:fixed(9,16)}}));d.close();});
 test('late POST acknowledgement after deadline remains unknown and cannot revive a ticket',async()=>{const f=await templateFixture();let release,started;const observed=new Promise(r=>{started=r;});const c=new OwnerEncryptedTemplateClient(templateHost(f,{timeoutMs:120,fetchImpl:()=>{started();return new Promise(r=>{release=r;});}}));const t=await c.prepareSave(write(f));const result=c.commit(t);await observed;await assert.rejects(result,e=>e.state==='unknown');assert.ok(c.pending());release(receipt());await new Promise(r=>setTimeout(r,10));assert.ok(c.pending());await assert.rejects(c.retryUnknown(t),e=>e.state==='unknown');});
 test('streamed bodies and redirected responses cannot publish outside the original lifetime',async()=>{const f=await templateFixture();for(const response of [()=>new Response(new ReadableStream({start(controller){controller.enqueue(f.envelope.slice(0,12));}}),{headers:{'content-type':'application/vnd.zrotext.workflow-template.v1'}}),()=>{const r=latest(f);Object.defineProperty(r,'url',{value:'https://foreign.invalid/'});return r;}]){const c=new OwnerEncryptedTemplateClient(templateHost(f,{timeoutMs:60,fetchImpl:async()=>response()}));const before=performance.now();await assert.rejects(c.readLatest());assert.ok(performance.now()-before<1000);c.close();}});
 test('manual retry and verification caps include readLatest aliases and retain exact pending identity',async()=>{const f=await templateFixture();let posts=0;const c=new OwnerEncryptedTemplateClient(templateHost(f,{fetchImpl:async(u,o)=>{if(o.method==='GET')return latest(f);posts++;return new Response('',{status:503});}}));const t=await c.prepareSave(write(f));await assert.rejects(c.commit(t),e=>e.state==='unknown');await c.readLatest();await c.verifyUnknown(t);await c.readLatest();await assert.rejects(c.verifyUnknown(t),e=>e.code==='attempts_exhausted');await assert.rejects(c.retryUnknown(t));await assert.rejects(c.retryUnknown(t));await assert.rejects(c.retryUnknown(t),e=>e.code==='attempts_exhausted');assert.equal(posts,3);assert.ok(c.pending());c.close();});
 test('same revision changed ciphertext and accessor inputs refuse without identity inference',async()=>{const f=await templateFixture();const other=await sealEncryptedTemplate(f.manifest,f.scope,f.nowMs,{template:'Different synthetic',values:{}});let n=0;const c=new OwnerEncryptedTemplateClient(templateHost(f,{fetchImpl:async()=>new Response(n++===0?f.envelope:other,{headers:{'content-type':'application/vnd.zrotext.workflow-template.v1'}})}));await c.readLatest();await assert.rejects(c.readLatest(),e=>e.code==='head_changed');c.close();let accessed=false;const input={...write(f)};Object.defineProperty(input,'scope',{get(){accessed=true;return f.scope;}});const d=new OwnerEncryptedTemplateClient(templateHost(f));await assert.rejects(d.prepareSave(input));assert.equal(accessed,false);d.close();});
}
