// SPDX-License-Identifier: AGPL-3.0-only
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {OwnerTemplateAuthoring} from '../dist/owner-template-authoring.js';
import {templateFixture,templateHost,requestId} from './owner-encrypted-template-client.test.mjs';
import {openEncryptedTemplate} from '../dist/encrypted-template.js';
import {keyId} from '../dist/draft01.js';
import {canonicalSignature02,verifyManifest02} from '../dist/draft02-manifest.js';

export function authoringHost(f,extra={}) {
 return {...templateHost(f),readDraftState:async()=>({epoch:1n,revision:1n,custodyLive:true}),consumeDraftReview:async()=>true,...extra};
}
export const draft=f=>({requestId,expectedRevision:0,scope:f.scope,template:'Synthetic {{name}} ^',values:{name:'Example'},epoch:1n,draftRevision:1n});
async function twoPhoneFixture(first){
 const f=await templateFixture(),root=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
 const point=new Uint8Array(await crypto.subtle.exportKey('raw',root.publicKey)),zero16=new Uint8Array(16),zero32=new Uint8Array(32),enc=new TextEncoder();
 const join=(...a)=>new Uint8Array(Buffer.concat(a.map(b=>Buffer.from(b)))),u64=n=>{const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,n);return b;},u32=n=>{const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n);return b;};
 const phones=[];for(let i=0;i<2;i++){const key=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),p=new Uint8Array(await crypto.subtle.exportKey('raw',key.publicKey));phones.push({p,id:await keyId(257,p)});}phones.sort((a,b)=>Buffer.compare(Buffer.from(a.id),Buffer.from(b.id)));
 const record=async(role,p,d,l,scope,from,until)=>join(Uint8Array.of(role),await keyId(role===2?16:257,p),p,d,l,Uint8Array.of(0,scope),u64(from),u64(until),Uint8Array.of(1));
 const records=[await record(2,f.manifest.keys.find(k=>k.role===2).point,zero16,zero16,12,f.nowMs-1000n,f.nowMs+3600000n),await record(4,phones[0].p,f.binding.device,f.binding.line,2,first==='expired'?f.nowMs-5000n:f.nowMs+1000n,first==='expired'?f.nowMs-1000n:f.nowMs+3600000n),await record(4,phones[1].p,f.binding.device,f.binding.line,2,f.nowMs-1000n,f.nowMs+1000n),await record(6,point,zero16,zero16,0,f.nowMs-1000n,f.nowMs+3600000n)];
 const unsigned=join(enc.encode('ZTMA'),Uint8Array.of(2),f.binding.account,u64(1n),u64(1n),u64(f.nowMs-1000n),u64(f.nowMs+3600000n),zero32,point,Uint8Array.of(records.length),...records);
 const signature=canonicalSignature02(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},root.privateKey,join(enc.encode('ZTSE/manifest/v2\0'),u32(unsigned.length),unsigned))));
 f.trust={...f.trust,rootPoint:point};f.manifestBytes=join(unsigned,signature);f.manifest=await verifyManifest02(f.manifestBytes,f.trust,f.nowMs);f.scope={...f.scope,manifestDigest:Uint8Array.from(f.manifest.digest)};return f;
}

if(process.argv[1]?.endsWith('owner-template-authoring.test.mjs')) {
 test('exact copied local review seals actual HPKE content and requires separate explicit commit',async()=>{
  const f=await templateFixture();let posts=0,posted,review;const input=draft(f);
  const a=new OwnerTemplateAuthoring(authoringHost(f,{consumeDraftReview:async r=>{review=r;input.values.name='Changed';input.template='Changed';r.scope.templateId.fill(8);return true;},fetchImpl:async(_,o)=>{posts++;posted=new Uint8Array(o.body);return new Response('{"revision":1}',{headers:{'content-type':'application/json'}});}}));
  const ticket=await a.prepare(input);assert.equal(posts,0);assert.equal(review.preview.text,'Synthetic Example ^');assert.equal(review.preview.estimate.encoding,'gsm');
  await a.client.commit(ticket);assert.equal(posts,1);const opened=await openEncryptedTemplate(f.manifest,f.scope,f.nowMs,f.archive.privateKey,posted);assert.deepEqual(opened,{template:'Synthetic {{name}} ^',values:{name:'Example'}});a.close();
 });
 test('declined exact review prepares no persistence ticket or network request',async()=>{const f=await templateFixture();let posts=0,metadata=0;const a=new OwnerTemplateAuthoring(authoringHost(f,{consumeDraftReview:async()=>false,consumeCiphertextReview:async()=>{metadata++;},fetchImpl:async()=>{posts++;throw Error('No request expected');}}));await assert.rejects(a.prepare(draft(f)),e=>e.code==='review_declined');assert.equal(metadata,0);assert.equal(posts,0);a.close();});
 test('busy ownership precedes adversarial input inspection and refuses nested preparation',async()=>{const f=await templateFixture();let nested,reviews=0;const a=new OwnerTemplateAuthoring(authoringHost(f,{consumeDraftReview:async()=>{reviews++;return true;}}));const input=new Proxy(draft(f),{getPrototypeOf(target){nested=a.prepare(draft(f));return Reflect.getPrototypeOf(target);}});const outer=a.prepare(input);const [x,y]=await Promise.allSettled([outer,nested]);assert.equal(x.status,'fulfilled');assert.equal(y.status,'rejected');assert.equal(y.reason.code,'busy');assert.equal(reviews,1);a.close();});
 test('accessors and malformed values are refused without invoking getters or review',async()=>{const f=await templateFixture();let getters=0,reviews=0;for(const input of [Object.defineProperty(draft(f),'template',{get(){getters++;return 'Synthetic';}}),{...draft(f),values:Object.defineProperty({},'name',{enumerable:true,get(){getters++;return 'Example';}})},{...draft(f),template:'{{missing}}'},{...draft(f),template:'\ud800'},{...draft(f),template:'x'.repeat(1000)}]){const a=new OwnerTemplateAuthoring(authoringHost(f,{consumeDraftReview:async()=>{reviews++;return true;}}));await assert.rejects(a.prepare(input));a.close();}assert.equal(getters,0);assert.equal(reviews,0);});
 for(const field of ['epoch','revision','custodyLive'])test(`changed draft ${field} after review refuses preparation`,async()=>{const f=await templateFixture();let reviewed=false,metadata=0;const a=new OwnerTemplateAuthoring(authoringHost(f,{consumeDraftReview:async()=>{reviewed=true;return true;},readDraftState:async()=>({epoch:field==='epoch'&&reviewed?2n:1n,revision:field==='revision'&&reviewed?2n:1n,custodyLive:!(field==='custodyLive'&&reviewed)}),consumeCiphertextReview:async()=>{metadata++;}}));await assert.rejects(a.prepare(draft(f)));assert.equal(metadata,0);a.close();});
 for(const field of ['ownerSessionLive','binding','csrf','manifest'])test(`changed ${field} after review refuses sealing`,async()=>{const f=await templateFixture();let reviewed=false;const baseline=await templateHost(f).readCurrent();const a=new OwnerTemplateAuthoring(authoringHost(f,{consumeDraftReview:async()=>{reviewed=true;return true;},currentCsrf:()=>field==='csrf'&&reviewed?'changed-csrf':'synthetic-csrf',readCurrent:async()=>({...baseline,ownerSessionLive:!(field==='ownerSessionLive'&&reviewed),binding:field==='binding'&&reviewed?{...f.binding,session:new Uint8Array(16).fill(8)}:f.binding,manifest:field==='manifest'&&reviewed?{...f.manifest}:f.manifest})}));await assert.rejects(a.prepare(draft(f)));a.close();});
 test('outer deadline closes owned persistence and fences a late child preparation',async()=>{const f=await templateFixture();let release,entered;const held=new Promise(r=>{release=r;}),atMetadata=new Promise(r=>{entered=r;});const a=new OwnerTemplateAuthoring(authoringHost(f,{timeoutMs:100,consumeCiphertextReview:async()=>{entered();await held;}}));const result=a.prepare(draft(f));await atMetadata;await assert.rejects(result,e=>e.code==='deadline');release();await assert.rejects(a.client.prepareSave({requestId,expectedRevision:0,scope:f.scope,envelope:f.envelope}));assert.equal(a.client.pending(),null);a.close();});
 test('close during held plaintext review prevents late persistence preparation',async()=>{const f=await templateFixture();let release,entered;const held=new Promise(r=>{release=r;}),ready=new Promise(r=>{entered=r;});let metadata=0;const a=new OwnerTemplateAuthoring(authoringHost(f,{consumeDraftReview:async()=>{entered();await held;return true;},consumeCiphertextReview:async()=>{metadata++;}}));const result=a.prepare(draft(f));await ready;a.close();await assert.rejects(result);release();assert.equal(metadata,0);});
 test('unknown dispatched persistence identity survives authoring close and replacement refusal',async()=>{const f=await templateFixture();let posts=0;const a=new OwnerTemplateAuthoring(authoringHost(f,{fetchImpl:async()=>{posts++;return new Response('',{status:503});}}));const ticket=await a.prepare(draft(f));await assert.rejects(a.client.commit(ticket),e=>e.state==='unknown');const pending=a.client.pending();await assert.rejects(a.prepare({...draft(f),requestId:'00000000-0000-0000-0000-000000000010'}));a.close();assert.deepEqual(a.client.pending(),pending);assert.equal(posts,1);});
 test('expired first phone key cannot falsely refuse the currently authorized second key',async()=>{const f=await twoPhoneFixture('expired');const a=new OwnerTemplateAuthoring(authoringHost(f));assert.ok(await a.prepare(draft(f)));a.close();});
 test('future first phone key cannot extend the active second phone key deadline',async()=>{const f=await twoPhoneFixture('future');let release;const held=new Promise(r=>{release=r;});const a=new OwnerTemplateAuthoring(authoringHost(f,{consumeDraftReview:async()=>{await held;return true;}}));const started=performance.now();await assert.rejects(a.prepare(draft(f)),e=>e.code==='deadline');assert.ok(performance.now()-started<3000,'active phone expiry must shorten the original ten-second budget');release();a.close();});
 test('shadowed instance methods cannot replace the real branded persistence preparation or close',async()=>{const f=await templateFixture();const a=new OwnerTemplateAuthoring(authoringHost(f,{fetchImpl:async()=>new Response('{"revision":1}',{headers:{'content-type':'application/json'}})}));const fake=Object.freeze({});a.client.prepareSave=async()=>fake;a.client.close=()=>{};const ticket=await a.prepare(draft(f));assert.notEqual(ticket,fake);assert.equal((await a.client.commit(ticket)).state,'acknowledged_saved_revision');a.close();await assert.rejects(a.client.readLatest());});
 test('returned ticket and held explicit commit retain the original authoring lifetime deadline',async()=>{const f=await templateFixture();const a=new OwnerTemplateAuthoring(authoringHost(f,{timeoutMs:1000,consumeDraftReview:async()=>{await new Promise(r=>setTimeout(r,500));return true;},fetchImpl:async(_,o)=>new Promise((_,reject)=>o.signal.addEventListener('abort',()=>reject(Error('Synthetic aborted transport')),{once:true}))}));const started=performance.now();const ticket=await a.prepare(draft(f));await assert.rejects(a.client.commit(ticket),e=>e.state==='unknown');assert.ok(performance.now()-started<1300,'child preparation must not restart the original lifetime deadline');assert.ok(a.client.pending());a.close();});
}
