// SPDX-License-Identifier: AGPL-3.0-only
// Synthetic DOM/session observations; genuine signed SDK and IndexedDB operations.
const {test}=require('node:test'),assert=require('node:assert/strict');
const {readFile}=require('node:fs/promises'),{pathToFileURL}=require('node:url'),path=require('node:path');
const repo=path.resolve(__dirname,'../..'),sdk=pathToFileURL(path.join(repo,'sdk/typescript/dist/')).href;
let loaded;
async function api(){if(!loaded){let s=await readFile(path.join(__dirname,'account-root-trust.js'),'utf8');for(const n of ['draft02-manifest.js','draft02-trust-store.js','contact-reader-statement.js'])s=s.replaceAll('/v1/owner/account-root-trust-sdk/sdk/'+n,sdk+n);loaded=import('data:text/javascript;base64,'+Buffer.from(s).toString('base64'));}return loaded;}
async function fixture(){
 const {refreshFixture,signFixtureSuccessor02}=await import(pathToFileURL(path.join(repo,'sdk/typescript/test/conversation-refresh-fixture.mjs'))),{IDBFactory}=await import(pathToFileURL(path.join(repo,'sdk/typescript/node_modules/fake-indexeddb/build/esm/index.js')));
 const {File}=require('node:buffer'),f=await refreshFixture(),now=Date.now(),unsigned=f.predecessor.bytes.slice(0,-64),v=new DataView(unsigned.buffer);v.setBigUint64(29,1n);v.setBigUint64(37,BigInt(now-1000));v.setBigUint64(45,BigInt(now+60000));unsigned.fill(0,53,85);
 for(let at=151;at<unsigned.length;at+=149){v.setBigUint64(at+132,BigInt(now-1000));v.setBigUint64(at+140,BigInt(now+60000));}
 const signed=await signFixtureSuccessor02(f,unsigned),account=Buffer.from(f.review.binding.account).toString('hex').replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,'$1-$2-$3-$4-$5'),pin=new Uint8Array(94);pin.set([90,84,82,80,2]);pin.set(f.review.binding.account,5);new DataView(pin.buffer).setBigUint64(21,1n);pin.set(f.predecessor.rootPoint,29);
 const o=new TextEncoder().encode(f.origin),card=new Uint8Array(133+o.length);card.set([90,84,82,67,1]);new DataView(card.buffer).setUint16(5,o.length);card.set(o,7);card.set(pin,7+o.length);
 class Node {value='';files=[];disabled=true;hidden=false;textContent='';events=new Map();addEventListener(e,fn){this.events.set(e,fn);}removeEventListener(e){this.events.delete(e);}}
 const ids=['account','origin','fingerprint','card','manifest','inputs','review','decision','tuple','accept','decline','status','reconcile','expected','statement','verify-statement'],nodes=Object.fromEntries(ids.map(n=>[n,new Node()]));
 nodes.account.value=account;nodes.origin.value=f.origin;nodes.fingerprint.value=Buffer.from(f.comparedRootFingerprint).toString('hex');nodes.card.files=[new File([card],'public-card.bin')];nodes.manifest.files=[new File([signed],'manifest.bin')];
 const doc=new Node();doc.hidden=false;doc.cookie='__Host-zrotext_csrf=synthetic-review';doc.getElementById=id=>nodes[id];const win=new Node();win.location={origin:f.origin};win.File=File;
 let calls=0,response={account_id:account,user_id:'22222222-2222-4222-8222-222222222222',session_id:'33333333-3333-4333-8333-333333333333',role:'owner'},hold=null;
 win.fetch=async()=>{calls++;if(hold)await hold();return new Response(JSON.stringify(response),{headers:{'Content-Type':'application/json'}});};
 const a=await api();global.document=doc;global.window=win;global.indexedDB=new IDBFactory();const review=a.startAccountRootReview();delete global.document;delete global.window;
 return {review,nodes,doc,win,a,card,pin,signed,f,get calls(){return calls;},setSession:fn=>fn(response),hold:fn=>hold=fn};
}
test('real independently pinned genesis accepts only public local history',async()=>{const f=await fixture();try{assert.equal((await f.review.prepare()).phase,'REVIEWING');assert.match(f.nodes.tuple.textContent,/manifestDigest/);assert.equal((await f.review.accept()).phase,'LOCAL_ACCEPTED_HISTORY');assert.equal(f.review.status().current,undefined);assert.equal(f.review.status().unknown,null);}finally{f.review.close();}});
test('independent account origin and fingerprint mismatches refuse before HTTP',async()=>{for(const kind of ['account','origin','fingerprint']){const f=await fixture();try{if(kind==='account')f.nodes.account.value='44444444-4444-4444-8444-444444444444';if(kind==='origin')f.nodes.origin.value='https://different.invalid';if(kind==='fingerprint')f.nodes.fingerprint.value='00'.repeat(32);await assert.rejects(f.review.prepare());assert.notEqual(f.review.status().phase,'LOCAL_ACCEPTED_HISTORY');assert.equal(f.calls,0);}finally{f.review.close();}}});
test('card parser refuses trailing bytes, wrong binary tag and wrong expected origin',async()=>{const f=await fixture();try{assert.deepEqual(f.a.capturePublicCard(f.card,f.f.origin),f.pin);for(const b of [new Uint8Array([...f.card,0]),f.card.map((v,i)=>i===4?2:v)])assert.throws(()=>f.a.capturePublicCard(b,f.f.origin));assert.throws(()=>f.a.capturePublicCard(f.card,'https://other.invalid'));}finally{f.review.close();}});
test('decline makes no local positive write and refuses reuse',async()=>{const f=await fixture();try{await f.review.prepare();f.review.decline();await assert.rejects(f.review.accept());const {Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),s=await Draft02TrustStore.open();try{assert.equal(await s.read(),null);}finally{s.close();}}finally{f.review.close();}});
test('actual owner session and CSRF drift refuse local acceptance',async()=>{for(const mode of ['session','cookie']){const f=await fixture();try{await f.review.prepare();if(mode==='session')f.setSession(v=>v.session_id='44444444-4444-4444-8444-444444444444');else f.doc.cookie='__Host-zrotext_csrf=changed-review';await assert.rejects(f.review.accept());assert.notEqual(f.review.status().phase,'LOCAL_ACCEPTED_HISTORY');}finally{f.review.close();}}});
test('held genuine file operation settles outward on close and observes late rejection',async()=>{const f=await fixture();let reject,touched=false;const file=f.nodes.card.files[0];Object.defineProperty(file,'arrayBuffer',{value:()=>{touched=true;return new Promise((_,no)=>reject=no);}});const p=f.review.prepare();while(!touched)await new Promise(r=>setImmediate(r));f.review.close();await assert.rejects(p);reject(Error('Synthetic late read failure'));await new Promise(r=>setImmediate(r));assert.equal(f.review.status().phase,'CLOSED');});
test('close after prepared review removes listeners and prevents late acceptance',async()=>{const f=await fixture();await f.review.prepare();f.review.close();await assert.rejects(f.review.accept());assert.equal(f.nodes.tuple.textContent,'');assert.equal(f.doc.events.size,0);assert.equal(f.win.events.size,0);assert.equal(f.nodes.inputs.events.size,0);});
test('held real initial digest cannot postpone the ten second outward deadline',async()=>{const f=await fixture(),subtle=crypto.subtle,original=subtle.digest.bind(subtle);let release,held=false;subtle.digest=(algorithm,data)=>{if(new Uint8Array(data).length===111){held=true;return new Promise(r=>release=()=>original(algorithm,data).then(r));}return original(algorithm,data);};try{const p=f.review.prepare();await assert.rejects(p);assert.equal(held,true);assert.notEqual(f.review.status().phase,'REVIEWING');release();await new Promise(r=>setTimeout(r,20));}finally{subtle.digest=original;f.review.close();}});
test('malformed and oversized File selections refuse before HTTP or file callback',async()=>{for(const mode of ['structural','oversized']){const f=await fixture();try{let calls=0;if(mode==='structural')f.nodes.card.files=[{size:f.card.length,arrayBuffer(){calls++;throw Error('must not read');}}];else{const {File}=require('node:buffer');f.nodes.card.files=[new File([new Uint8Array(646)],'oversized.bin')];Object.defineProperty(f.nodes.card.files[0],'arrayBuffer',{value:()=>{calls++;throw Error('must not read');}});}await assert.rejects(f.review.prepare());assert.equal(f.calls,0);assert.equal(calls,0);}finally{f.review.close();}}});
test('selected genuine File objects are frozen before asynchronous reading',async()=>{const f=await fixture(),file=f.nodes.card.files[0],original=file.arrayBuffer.bind(file);let release,held=false;Object.defineProperty(file,'arrayBuffer',{value:()=>{held=true;return new Promise(r=>release=async()=>r(await original()));}});try{const p=f.review.prepare();while(!held)await new Promise(r=>setImmediate(r));f.nodes.card.files=[];f.nodes.manifest.files=[];await release();assert.equal((await p).phase,'REVIEWING');assert.equal((await f.review.accept()).phase,'LOCAL_ACCEPTED_HISTORY');}finally{f.review.close();}});
test('duplicate session fields and invalid MIME refuse without local writes',async()=>{for(const mode of ['duplicate','mime']){const f=await fixture();try{f.win.fetch=async()=>new Response(mode==='duplicate'?`{"account_id":"${f.nodes.account.value}","account_id":"${f.nodes.account.value}","user_id":"22222222-2222-4222-8222-222222222222","session_id":"33333333-3333-4333-8333-333333333333","role":"owner"}`:'{}',{headers:{'Content-Type':mode==='mime'?'application/json-other':'application/json'}});await assert.rejects(f.review.prepare());assert.notEqual(f.review.status().phase,'LOCAL_ACCEPTED_HISTORY');}finally{f.review.close();}}});
test('lost receipt after genuine local commit preserves unknown and reconciles read-only',async()=>{const f=await fixture(),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),original=Draft02TrustStore.prototype.acceptManifest;try{await f.review.prepare();Draft02TrustStore.prototype.acceptManifest=async function(...args){await original.apply(this,args);throw Error('Synthetic local receipt lost');};await assert.rejects(f.review.accept());Draft02TrustStore.prototype.acceptManifest=original;const before=f.review.status();assert.equal(before.phase,'UNKNOWN');assert.equal(before.unknown.version,'1');await assert.rejects(f.review.prepare());assert.equal((await f.review.reconcile()).kind,'local_content_match');assert.deepEqual(f.review.status().unknown,before.unknown);assert.match(f.nodes.status.textContent,/does not prove which operation/);f.review.close();assert.deepEqual(f.review.status().unknown,before.unknown);}finally{Draft02TrustStore.prototype.acceptManifest=original;f.review.close();}});
test('four unresolved real digests remain charged after close until actual settlement',async()=>{const fixtures=[];for(let i=0;i<5;i++)fixtures.push(await fixture());const subtle=crypto.subtle,original=subtle.digest.bind(subtle),releases=[];let held=0;subtle.digest=(algorithm,data)=>{if(new Uint8Array(data).length===111){held++;return new Promise((yes,no)=>releases.push(()=>original(algorithm,data).then(yes,no)));}return original(algorithm,data);};try{const pending=[];for(let i=0;i<4;i++){const p=fixtures[i].review.prepare();p.catch(()=>{});pending.push(p);while(held<i+1)await new Promise(r=>setImmediate(r));}const fifth=fixtures[4].review.prepare();fifth.catch(()=>{});assert.equal(await Promise.race([fifth.then(()=>false,()=>true),new Promise(r=>setTimeout(()=>r(false),100))]),true,'fifth unresolved operation must refuse promptly');for(let i=0;i<4;i++)fixtures[i].review.close();await Promise.all(pending.map(p=>assert.rejects(p)));await assert.rejects(fixtures[4].review.prepare());assert.equal(held,4);subtle.digest=original;releases.forEach(fn=>fn());await new Promise(r=>setTimeout(r,30));assert.equal((await fixtures[4].review.prepare()).phase,'REVIEWING');}finally{subtle.digest=original;releases.forEach(fn=>fn());for(const f of fixtures)f.review.close();}});
test('late actual IndexedDB open is closed after outward abort without publication',async()=>{const f=await fixture(),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),original=Draft02TrustStore.open;let release,opened=false,closed=0;Draft02TrustStore.open=async function(...args){const store=await original.apply(this,args),close=store.close.bind(store);store.close=()=>{closed++;close();};opened=true;return new Promise(r=>release=()=>r(store));};try{const p=f.review.prepare();while(!opened)await new Promise(r=>setImmediate(r));f.review.close();await assert.rejects(p);assert.equal(closed,0);release();await new Promise(r=>setImmediate(r));assert.equal(closed,1);assert.equal(f.review.status().phase,'CLOSED');}finally{Draft02TrustStore.open=original;if(release)release();f.review.close();}});
test('two genuine connections cannot apply a stale reviewed predecessor',async()=>{const f=await fixture();global.document=f.doc;global.window=f.win;const second=f.a.startAccountRootReview();delete global.document;delete global.window;try{await f.review.prepare();await second.prepare();await f.review.accept();await assert.rejects(second.accept());const {Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),store=await Draft02TrustStore.open();try{assert.equal((await store.read()).trust.version,1n);}finally{store.close();}assert.equal(second.status().unknown,null);}finally{second.close();f.review.close();}});
test('genuine root loss during reviewed intent refuses instead of reenrolling',async()=>{const f=await fixture();try{await f.review.prepare();await f.review.accept();await f.review.prepare();const db=await new Promise((yes,no)=>{const r=indexedDB.open('ztse-draft02-trust-v1',1);r.onsuccess=()=>yes(r.result);r.onerror=()=>no(r.error);});try{await new Promise((yes,no)=>{const t=db.transaction('owner-root-high-water','readwrite');t.objectStore('owner-root-high-water').clear();t.oncomplete=yes;t.onabort=no;});}finally{db.close();}await assert.rejects(f.review.accept());const {Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),store=await Draft02TrustStore.open();try{assert.equal(await store.read(),null);}finally{store.close();}assert.equal(f.review.status().unknown,null);}finally{f.review.close();}});
test('idle prepared review expires and removes its retained display',async t=>{const f=await fixture();t.mock.timers.enable({apis:['setTimeout']});try{await f.review.prepare();assert.equal(f.review.status().phase,'REVIEWING');t.mock.timers.tick(300001);assert.equal(f.review.status().phase,'DECLINED');assert.equal(f.nodes.tuple.textContent,'');await assert.rejects(f.review.accept());}finally{t.mock.timers.reset();f.review.close();}});
test('held genuine history confirmation closes outward and retains possible local write',async()=>{const f=await fixture(),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),original=Draft02TrustStore.prototype.verifyStoredHistory;let release,held=false;try{await f.review.prepare();Draft02TrustStore.prototype.verifyStoredHistory=function(...args){held=true;return new Promise((yes,no)=>release=()=>original.apply(this,args).then(yes,no));};const p=f.review.accept();p.catch(()=>{});while(!held)await new Promise(r=>setImmediate(r));f.review.close();await assert.rejects(p);assert.equal(f.review.status().phase,'UNKNOWN');assert.equal(f.review.status().unknown.version,'1');release();await new Promise(r=>setTimeout(r,20));assert.equal(f.review.status().phase,'UNKNOWN');}finally{Draft02TrustStore.prototype.verifyStoredHistory=original;if(release)release();f.review.close();}});
