// SPDX-License-Identifier: AGPL-3.0-only
// Synthetic DOM/session observations; genuine signed SDK and IndexedDB operations.
const {test}=require('node:test'),assert=require('node:assert/strict');
const {readFile}=require('node:fs/promises'),{pathToFileURL}=require('node:url'),path=require('node:path');
const repo=path.resolve(__dirname,'../..'),sdk=pathToFileURL(path.join(repo,'sdk/typescript/dist/')).href;
let loaded;
async function api(change){if(change){let s=await readFile(path.join(__dirname,'account-root-trust.js'),'utf8');s=change(s);for(const n of ['draft02-manifest.js','draft02-trust-store.js','contact-reader-statement.js'])s=s.replaceAll('/v1/owner/account-root-trust-sdk/sdk/'+n,sdk+n);return import('data:text/javascript;base64,'+Buffer.from(s).toString('base64'));}if(!loaded){let s=await readFile(path.join(__dirname,'account-root-trust.js'),'utf8');for(const n of ['draft02-manifest.js','draft02-trust-store.js','contact-reader-statement.js'])s=s.replaceAll('/v1/owner/account-root-trust-sdk/sdk/'+n,sdk+n);loaded=import('data:text/javascript;base64,'+Buffer.from(s).toString('base64'));}return loaded;}
async function fixture(change){
 const {refreshFixture,signFixtureSuccessor02}=await import(pathToFileURL(path.join(repo,'sdk/typescript/test/conversation-refresh-fixture.mjs'))),{IDBFactory}=await import(pathToFileURL(path.join(repo,'sdk/typescript/node_modules/fake-indexeddb/build/esm/index.js')));
 const {File}=require('node:buffer'),f=await refreshFixture(),now=Date.now(),unsigned=f.predecessor.bytes.slice(0,-64),v=new DataView(unsigned.buffer);v.setBigUint64(29,1n);v.setBigUint64(37,BigInt(now-1000));v.setBigUint64(45,BigInt(now+180000));unsigned.fill(0,53,85);
 for(let at=151;at<unsigned.length;at+=149){v.setBigUint64(at+132,BigInt(now-1000));v.setBigUint64(at+140,BigInt(now+180000));}
 const signed=await signFixtureSuccessor02(f,unsigned),account=Buffer.from(f.review.binding.account).toString('hex').replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,'$1-$2-$3-$4-$5'),pin=new Uint8Array(94);pin.set([90,84,82,80,2]);pin.set(f.review.binding.account,5);new DataView(pin.buffer).setBigUint64(21,1n);pin.set(f.predecessor.rootPoint,29);
 const o=new TextEncoder().encode(f.origin),card=new Uint8Array(133+o.length);card.set([90,84,82,67,1]);new DataView(card.buffer).setUint16(5,o.length);card.set(o,7);card.set(pin,7+o.length);
 class Node {value='';files=[];disabled=true;hidden=false;textContent='';events=new Map();addEventListener(e,fn){this.events.set(e,fn);}removeEventListener(e){this.events.delete(e);}}
 const ids=['account','origin','fingerprint','card','manifest','inputs','review','decision','tuple','accept','decline','status','reconcile','expected','statement','verify-statement','bundle','reader-id','reader-point','requested-until','issuer-review','issuer-create','issuer-retry','issuer-export','issuer-recovery-export','issuer-import','issuer-signature','issuer-complete','issuer-factor','issuer-lookup','issuer-cancel','issuer-withdraw','issuer-decline','issuer-facts','issuer-status','issuer-recovery','issuer-recover'],nodes=Object.fromEntries(ids.map(n=>[n,new Node()]));
 nodes.account.value=account;nodes.origin.value=f.origin;nodes.fingerprint.value=Buffer.from(f.comparedRootFingerprint).toString('hex');nodes.card.files=[new File([card],'public-card.bin')];nodes.manifest.files=[new File([signed],'manifest.bin')];
 const doc=new Node();doc.hidden=false;doc.cookie='__Host-zrotext_csrf=synthetic-review';doc.getElementById=id=>nodes[id];const win=new Node();win.location={origin:f.origin};win.File=File;
 let calls=0,response={account_id:account,user_id:'22222222-2222-4222-8222-222222222222',session_id:'33333333-3333-4333-8333-333333333333',role:'owner'},hold=null;
 win.fetch=async()=>{calls++;if(hold)await hold();return new Response(JSON.stringify(response),{headers:{'Content-Type':'application/json'}});};
 const downloads=[];win.Blob=Blob;win.URL={createObjectURL:b=>{downloads.push(b);return 'blob:synthetic-public';},revokeObjectURL:()=>{}};doc.createElement=()=>({click(){}});const a=await api(change);global.document=doc;global.window=win;global.indexedDB=new IDBFactory();const review=a.startAccountRootReview();delete global.document;delete global.window;
 return {review,nodes,doc,win,a,card,pin,signed,f,downloads,get calls(){return calls;},setSession:fn=>fn(response),hold:fn=>hold=fn};
}
test('real independently pinned genesis accepts only public local history',async()=>{const f=await fixture();try{assert.equal((await f.review.prepare()).phase,'REVIEWING');assert.match(f.nodes.tuple.textContent,/manifestDigest/);assert.equal((await f.review.accept()).phase,'LOCAL_ACCEPTED_HISTORY');assert.equal(f.review.status().current,undefined);assert.equal(f.review.status().unknown,null);}finally{f.review.close();}});
test('independent account origin and fingerprint mismatches refuse before HTTP',async()=>{for(const kind of ['account','origin','fingerprint']){const f=await fixture();try{if(kind==='account')f.nodes.account.value='44444444-4444-4444-8444-444444444444';if(kind==='origin')f.nodes.origin.value='https://different.invalid';if(kind==='fingerprint')f.nodes.fingerprint.value='00'.repeat(32);await assert.rejects(f.review.prepare());assert.notEqual(f.review.status().phase,'LOCAL_ACCEPTED_HISTORY');assert.equal(f.calls,0);}finally{f.review.close();}}});
test('card parser refuses trailing bytes, wrong binary tag and wrong expected origin',async()=>{const f=await fixture();try{assert.deepEqual(f.a.capturePublicCard(f.card,f.f.origin),f.pin);for(const b of [new Uint8Array([...f.card,0]),f.card.map((v,i)=>i===4?2:v)])assert.throws(()=>f.a.capturePublicCard(b,f.f.origin));assert.throws(()=>f.a.capturePublicCard(f.card,'https://other.invalid'));}finally{f.review.close();}});
test('decline makes no local positive write and refuses reuse',async()=>{const f=await fixture();try{await f.review.prepare();f.review.decline();await assert.rejects(f.review.accept());const {Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),s=await Draft02TrustStore.open();try{assert.equal(await s.read(),null);}finally{s.close();}}finally{f.review.close();}});
test('actual owner session and CSRF drift refuse local acceptance',async()=>{for(const mode of ['session','cookie']){const f=await fixture();try{await f.review.prepare();if(mode==='session')f.setSession(v=>v.session_id='44444444-4444-4444-8444-444444444444');else f.doc.cookie='__Host-zrotext_csrf=changed-review';await assert.rejects(f.review.accept());assert.notEqual(f.review.status().phase,'LOCAL_ACCEPTED_HISTORY');}finally{f.review.close();}}});
test('held genuine file operation settles outward on close and observes late rejection',async()=>{const f=await fixture();let reject,touched=false;const file=f.nodes.card.files[0];Object.defineProperty(file,'arrayBuffer',{value:()=>{touched=true;return new Promise((_,no)=>reject=no);}});const p=f.review.prepare();while(!touched)await new Promise(r=>setImmediate(r));f.review.close();await assert.rejects(p);reject(Error('Synthetic late read failure'));await new Promise(r=>setImmediate(r));assert.equal(f.review.status().phase,'CLOSED');});
test('close after prepared review removes listeners and prevents late acceptance',async()=>{const f=await fixture();await f.review.prepare();f.review.close();await assert.rejects(f.review.accept());assert.equal(f.nodes.tuple.textContent,'');assert.equal(f.doc.events.size,0);assert.equal(f.win.events.size,0);assert.equal(f.nodes.inputs.events.size,0);});
test('held real initial digest cannot postpone the ten second outward deadline',async()=>{const f=await fixture(),subtle=crypto.subtle,original=subtle.digest.bind(subtle);let release,held=false;subtle.digest=(algorithm,data)=>{if(new Uint8Array(data).length===111){held=true;return new Promise(r=>release=()=>original(algorithm,data).then(r));}return original(algorithm,data);};try{const p=f.review.prepare();await assert.rejects(p);assert.equal(held,true);assert.notEqual(f.review.status().phase,'REVIEWING');release();await new Promise(r=>setTimeout(r,20));}finally{subtle.digest=original;f.review.close();}});
test('malformed and oversized File selections refuse before HTTP or file callback',async()=>{for(const mode of ['structural','oversized']){const f=await fixture();try{let calls=0;if(mode==='structural')f.nodes.card.files=[{size:f.card.length,arrayBuffer(){calls++;throw Error('must not read');}}];else{const {File}=require('node:buffer');f.nodes.card.files=[new File([new Uint8Array(646)],'oversized.bin')];Object.defineProperty(f.nodes.card.files[0],'arrayBuffer',{value:()=>{calls++;throw Error('must not read');}});}await assert.rejects(f.review.prepare());assert.equal(f.calls,0);assert.equal(calls,0);}finally{f.review.close();}}});
test('selected genuine File objects are frozen before asynchronous reading',async()=>{const f=await fixture(),file=f.nodes.card.files[0],original=file.arrayBuffer.bind(file);let release,held=false;Object.defineProperty(file,'arrayBuffer',{value:()=>{held=true;return new Promise(r=>release=async()=>r(await original()));}});try{const p=f.review.prepare();while(!held)await new Promise(r=>setImmediate(r));f.nodes.card.files=[];f.nodes.manifest.files=[];await release();assert.equal((await p).phase,'REVIEWING');assert.equal((await f.review.accept()).phase,'LOCAL_ACCEPTED_HISTORY');}finally{f.review.close();}});
test('duplicate session fields and invalid MIME refuse without local writes',async()=>{for(const mode of ['duplicate','mime']){const f=await fixture();try{f.win.fetch=async()=>new Response(mode==='duplicate'?`{"account_id":"${f.nodes.account.value}","account_id":"${f.nodes.account.value}","user_id":"22222222-2222-4222-8222-222222222222","session_id":"33333333-3333-4333-8333-333333333333","role":"owner"}`:'{}',{headers:{'Content-Type':mode==='mime'?'application/json-other':'application/json'}});await assert.rejects(f.review.prepare());assert.notEqual(f.review.status().phase,'LOCAL_ACCEPTED_HISTORY');}finally{f.review.close();}}});
test('lost receipt after genuine local commit preserves unknown and reconciles read-only',async()=>{const f=await fixture(),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),original=Draft02TrustStore.prototype.acceptManifest;try{await f.review.prepare();Draft02TrustStore.prototype.acceptManifest=async function(...args){await original.apply(this,args);throw Error('Synthetic local receipt lost');};await assert.rejects(f.review.accept());Draft02TrustStore.prototype.acceptManifest=original;const before=f.review.status();assert.equal(before.phase,'UNKNOWN');assert.equal(before.unknown.version,'1');await assert.rejects(f.review.prepare());assert.equal((await f.review.reconcile()).kind,'local_content_match');assert.deepEqual(f.review.status().unknown,before.unknown);assert.match(f.nodes.status.textContent,/does not prove which operation/);f.review.close();assert.deepEqual(f.review.status().unknown,before.unknown);}finally{Draft02TrustStore.prototype.acceptManifest=original;f.review.close();}});
test('four unresolved real digests remain charged after close until actual settlement',async()=>{const fixtures=[];for(let i=0;i<5;i++)fixtures.push(await fixture());const subtle=crypto.subtle,original=subtle.digest.bind(subtle),releases=[];let held=0;subtle.digest=(algorithm,data)=>{if(new Uint8Array(data).length===111){held++;return new Promise((yes,no)=>releases.push(()=>original(algorithm,data).then(yes,no)));}return original(algorithm,data);};try{const pending=[];for(let i=0;i<4;i++){const p=fixtures[i].review.prepare();p.catch(()=>{});pending.push(p);while(held<i+1)await new Promise(r=>setImmediate(r));}const fifth=fixtures[4].review.prepare();fifth.catch(()=>{});assert.equal(await Promise.race([fifth.then(()=>false,()=>true),new Promise(r=>setTimeout(()=>r(false),100))]),true,'fifth unresolved operation must refuse promptly');for(let i=0;i<4;i++)fixtures[i].review.close();await Promise.all(pending.map(p=>assert.rejects(p)));await assert.rejects(fixtures[4].review.prepare());assert.equal(held,4);subtle.digest=original;releases.forEach(fn=>fn());await new Promise(r=>setTimeout(r,30));assert.equal((await fixtures[4].review.prepare()).phase,'REVIEWING');}finally{subtle.digest=original;releases.forEach(fn=>fn());for(const f of fixtures)f.review.close();}});
test('late actual IndexedDB open is closed after outward abort without publication',async()=>{const f=await fixture(),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),original=Draft02TrustStore.open;let release,opened=false,closed=0;Draft02TrustStore.open=async function(...args){const store=await original.apply(this,args),close=store.close.bind(store);store.close=()=>{closed++;close();};opened=true;return new Promise(r=>release=()=>r(store));};try{const p=f.review.prepare();while(!opened)await new Promise(r=>setImmediate(r));f.review.close();await assert.rejects(p);assert.equal(closed,0);release();await new Promise(r=>setImmediate(r));assert.equal(closed,1);assert.equal(f.review.status().phase,'CLOSED');}finally{Draft02TrustStore.open=original;if(release)release();f.review.close();}});
test('two genuine connections cannot apply a stale reviewed predecessor',async()=>{const f=await fixture();global.document=f.doc;global.window=f.win;const second=f.a.startAccountRootReview();delete global.document;delete global.window;try{await f.review.prepare();await second.prepare();await f.review.accept();await assert.rejects(second.accept());const {Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),store=await Draft02TrustStore.open();try{assert.equal((await store.read()).trust.version,1n);}finally{store.close();}assert.equal(second.status().unknown,null);}finally{second.close();f.review.close();}});
test('genuine root loss during reviewed intent refuses instead of reenrolling',async()=>{const f=await fixture();try{await f.review.prepare();await f.review.accept();await f.review.prepare();const db=await new Promise((yes,no)=>{const r=indexedDB.open('ztse-draft02-trust-v1',1);r.onsuccess=()=>yes(r.result);r.onerror=()=>no(r.error);});try{await new Promise((yes,no)=>{const t=db.transaction('owner-root-high-water','readwrite');t.objectStore('owner-root-high-water').clear();t.oncomplete=yes;t.onabort=no;});}finally{db.close();}await assert.rejects(f.review.accept());const {Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),store=await Draft02TrustStore.open();try{assert.equal(await store.read(),null);}finally{store.close();}assert.equal(f.review.status().unknown,null);}finally{f.review.close();}});
test('idle prepared review expires and removes its retained display',async t=>{const f=await fixture();t.mock.timers.enable({apis:['setTimeout']});try{await f.review.prepare();assert.equal(f.review.status().phase,'REVIEWING');t.mock.timers.tick(300001);assert.equal(f.review.status().phase,'DECLINED');assert.equal(f.nodes.tuple.textContent,'');await assert.rejects(f.review.accept());}finally{t.mock.timers.reset();f.review.close();}});
test('held genuine history confirmation closes outward and retains possible local write',async()=>{const f=await fixture(),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),original=Draft02TrustStore.prototype.verifyStoredHistory;let release,held=false;try{await f.review.prepare();Draft02TrustStore.prototype.verifyStoredHistory=function(...args){held=true;return new Promise((yes,no)=>release=()=>original.apply(this,args).then(yes,no));};const p=f.review.accept();p.catch(()=>{});while(!held)await new Promise(r=>setImmediate(r));f.review.close();await assert.rejects(p);assert.equal(f.review.status().phase,'UNKNOWN');assert.equal(f.review.status().unknown.version,'1');release();await new Promise(r=>setTimeout(r,20));assert.equal(f.review.status().phase,'UNKNOWN');}finally{Draft02TrustStore.prototype.verifyStoredHistory=original;if(release)release();f.review.close();}});
test('selected account stays frozen across a held real file and changed owner observation',async()=>{const f=await fixture(),file=f.nodes.card.files[0],original=file.arrayBuffer.bind(file);let release,held=false;Object.defineProperty(file,'arrayBuffer',{value:()=>{held=true;return new Promise(r=>release=async()=>r(await original()));}});try{const p=f.review.prepare();p.catch(()=>{});while(!held)await new Promise(r=>setImmediate(r));f.nodes.account.value='44444444-4444-4444-8444-444444444444';f.setSession(v=>v.account_id=f.nodes.account.value);await release();await assert.rejects(p);assert.equal(f.calls,0);assert.notEqual(f.review.status().phase,'REVIEWING');const {Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),store=await Draft02TrustStore.open();try{assert.equal(await store.read(),null);}finally{store.close();}}finally{f.review.close();}});
test('unknown reconciliation refuses a changed visible account before sampling session',async()=>{const f=await fixture(),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),original=Draft02TrustStore.prototype.acceptManifest;try{await f.review.prepare();Draft02TrustStore.prototype.acceptManifest=async function(...args){await original.apply(this,args);throw Error('Synthetic lost receipt');};await assert.rejects(f.review.accept());Draft02TrustStore.prototype.acceptManifest=original;const unknown=f.review.status().unknown,calls=f.calls;f.nodes.account.value='44444444-4444-4444-8444-444444444444';f.setSession(v=>v.account_id=f.nodes.account.value);await assert.rejects(f.review.reconcile());assert.equal(f.calls,calls);assert.deepEqual(f.review.status().unknown,unknown);}finally{Draft02TrustStore.prototype.acceptManifest=original;f.review.close();}});
test('final prepare session sample refuses account changes while its response is held',async()=>{const f=await fixture();let release,held=false;f.hold(()=>f.calls===2?new Promise(r=>{held=true;release=r;}):Promise.resolve());try{const p=f.review.prepare();p.catch(()=>{});while(!held)await new Promise(r=>setImmediate(r));f.nodes.account.value='44444444-4444-4444-8444-444444444444';f.setSession(v=>v.account_id=f.nodes.account.value);release();await assert.rejects(p);assert.equal(f.review.status().phase,'DECLINED');assert.equal(f.review.status().unknown,null);}finally{if(release)release();f.review.close();}});

async function waitFor(fn){for(let n=0;n<500;n++){if(fn())return;await new Promise(r=>setTimeout(r,5));}assert.fail('Synthetic observation did not settle');}
function click(f,id){f.nodes[id].events.get('click')({preventDefault(){}});}
async function issuerFixture(change){
 const f=await fixture(change),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),{verifiedAccountArchiveStatementRecords02}=await import(sdk+'draft02-manifest.js');
 await f.review.prepare();await f.review.accept();const store=await Draft02TrustStore.open();let m,facts;
 try{const s=await store.read();m=await store.verifyStoredHistory(s.trust.digest,BigInt(Date.now()));facts=verifiedAccountArchiveStatementRecords02(m,m.keys.find(k=>k.role===2).keyId,BigInt(Date.now()));}finally{store.close();}
 const enc=b=>Buffer.from(b).toString('base64'),h=b=>Buffer.from(b).toString('hex'),number=n=>{const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(n));return b;},id=s=>Buffer.from(s.replaceAll('-',''),'hex');
 f.nodes.bundle.value='ab'.repeat(16);f.nodes['reader-id'].value=h(facts.readerId);f.nodes['reader-point'].value=h(facts.readerPoint);f.nodes['requested-until'].value=String(Date.now()+90000);
 const requests=[];let stateMode='valid',createMode='valid',hold=null,pending=null,statement=null,originalCreate=null;
 const current=()=>({phase:'empty',mutation_revision:'0',allocation_generation:'0',observed_ms:String(Date.now())});
 const state=()=>({kind:'contact_reader_state',state:{root_pin_b64:enc(f.pin),root_fingerprint_b64:enc(f.f.comparedRootFingerprint),trust_generation:'1',last_mutation_ms:String(Date.now()),current:current(),signed_statement:null}});
 const nativeSession=f.win.fetch;
 f.win.fetch=async(url,options)=>{
  if(url==='/v1/auth/session')return nativeSession(url,options);
  requests.push({url,options});assert.equal(options.headers['x-zrotext-csrf'],'synthetic-review');assert.equal(options.headers.Origin,undefined);assert.equal(options.credentials,'same-origin');assert.equal(options.cache,'no-store');assert.equal(options.redirect,'error');
  if(hold)await hold(url);let value;
  if(url==='/v1/owner/export?contact_reader_only=state'){
   value=state();if(stateMode==='absent')value.state=null;if(stateMode==='max')value.state.current.mutation_revision='9223372036854775807';
   if(stateMode==='wrong-root')value.state.root_fingerprint_b64=enc(new Uint8Array(32).fill(9));
   let raw=JSON.stringify(value);if(stateMode==='duplicate')raw=raw.replace('"kind":','"kind":"contact_reader_state","kind":');if(stateMode==='escaped')raw=raw.replace('"kind":','"\\u006bind":');
   if(stateMode==='oversized')raw+=' '.repeat(4097);return new Response(raw,{headers:{'Content-Type':'application/json'}});
  }
  if(url.endsWith('/intents')){
   if(createMode==='uncertain')return new Response('',{status:503});const c=JSON.parse(options.body);if(originalCreate)assert.equal(options.body,originalCreate);else originalCreate=options.body;
   const empty=c.prior.phase==='empty',o=Buffer.from(f.f.origin),len=Buffer.alloc(2);len.writeUInt16BE(o.length);
   const commitment=await crypto.subtle.digest('SHA-256',Buffer.concat([Buffer.from([1]),Buffer.from(f.f.review.binding.account),len,o,id(c.create_request),number(c.expected_revision),Buffer.from([empty?0:c.prior.phase==='active'?1:2]),empty?Buffer.alloc(16):id(c.prior.authorization),number(empty?0:c.prior.generation),empty?Buffer.alloc(32):Buffer.from(c.prior.digest,'base64'),Buffer.from(c.selected_reader_id,'base64'),Buffer.from(c.compared_root_fingerprint,'base64'),number(c.requested_until_ms)]));
   const issued=BigInt(Date.now()),authorization='77777777-7777-4777-8777-777777777777',generation='1';
   const {encodeContactReaderStatementUnsigned01}=await import(sdk+'contact-reader-statement.js');
   const unsigned=encodeContactReaderStatementUnsigned01({authorizationId:id(authorization),accountId:f.f.review.binding.account,origin:f.f.origin,trustGeneration:1n,manifestVersion:1n,readerGeneration:1n,rootFingerprint:f.f.comparedRootFingerprint,manifestDigest:facts.digest,readerId:facts.readerId,readerPoint:facts.readerPoint,issuedMs:issued,untilMs:BigInt(c.requested_until_ms),capability:3});
   const key=(keyId,point,from,until)=>({key_id_b64:enc(keyId),public_point_b64:enc(point),from_ms:String(from),until_ms:String(until)});
   pending={kind:'pending',create_input_digest:enc(new Uint8Array(commitment)),create_request:c.create_request,authorization,generation,creation_expected_revision:c.expected_revision,allocated_revision:'1',unsigned_digest:enc(new Uint8Array(await crypto.subtle.digest('SHA-256',unsigned))),unsigned:enc(unsigned),issued_ms:String(issued),expires_ms:String(issued+300000n),until_ms:c.requested_until_ms,created_by_user:'22222222-2222-4222-8222-222222222222',created_session:'33333333-3333-4333-8333-333333333333',creation_source:{kind:'historical_creation_source',account_id:f.nodes.account.value,root_pin_b64:enc(f.pin),root_fingerprint_b64:enc(f.f.comparedRootFingerprint),trust_generation:'1',manifest_version:'1',manifest_digest_b64:enc(facts.digest),manifest_b64:enc(m.bytes),observed_ms:String(issued),manifest_issued_ms:String(facts.issuedMs),manifest_expires_ms:String(facts.expiresMs),signed_until_ms:String([facts.expiresMs,facts.readerUntilMs,facts.rootUntilMs].reduce((a,b)=>a<b?a:b)),reader:key(facts.readerId,facts.readerPoint,facts.readerFromMs,facts.readerUntilMs),root_writer:key(facts.rootWriterId,facts.rootPoint,facts.rootFromMs,facts.rootUntilMs)},current:{phase:'empty',mutation_revision:'1',allocation_generation:'1',observed_ms:String(issued)}};
   value=structuredClone(pending);if(createMode==='wrong-source')value.creation_source.reader.public_point_b64=enc(facts.rootPoint);if(createMode==='wrong-actor')value.created_session='44444444-4444-4444-8444-444444444444';if(createMode==='expanded-ceiling')value.creation_source.signed_until_ms=String(BigInt(value.creation_source.signed_until_ms)+1n);if(createMode==='contracted-ceiling')value.creation_source.signed_until_ms=String(BigInt(value.creation_source.signed_until_ms)-1n);if(createMode==='source-below-intent')value.creation_source.signed_until_ms=String(BigInt(value.until_ms)-1n);if(createMode==='expanded-intent')value.until_ms=String(BigInt(value.until_ms)+1n);if(createMode==='shortened-intent')value.until_ms=String(BigInt(value.until_ms)-1n);
  }else if(url.includes('/complete')){
   const c=JSON.parse(options.body);assert.equal(c.code,'123456');assert.equal(c.signed_statement,enc(statement));if(createMode==='complete-uncertain')return new Response('',{status:503});value={kind:'historical_completed',create_input_digest:pending.create_input_digest,create_request:pending.create_request,authorization:pending.authorization,generation:pending.generation,creation_expected_revision:pending.creation_expected_revision,unsigned_digest:pending.unsigned_digest,terminal_ms:String(Date.now()),current:{...pending.current,observed_ms:String(Date.now())},signed_statement:enc(statement),statement_digest:enc(new Uint8Array(await crypto.subtle.digest('SHA-256',statement)))};
  }else if(url.includes('/cancel')){
   value={kind:'cancelled',create_input_digest:pending.create_input_digest,create_request:pending.create_request,authorization:pending.authorization,generation:pending.generation,creation_expected_revision:pending.creation_expected_revision,unsigned_digest:pending.unsigned_digest,terminal_ms:String(Date.now()),current:{...pending.current,observed_ms:String(Date.now())}};
  }else value=pending??{kind:'unavailable'};
  return new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});
 };
 async function sign(){
  const point=facts.rootPoint,scalar=new Uint8Array(32);scalar[31]=1;const key=await crypto.subtle.importKey('jwk',{kty:'EC',crv:'P-256',x:Buffer.from(point.slice(1,33)).toString('base64url'),y:Buffer.from(point.slice(33)).toString('base64url'),d:Buffer.from(scalar).toString('base64url')},{name:'ECDSA',namedCurve:'P-256'},false,['sign']);scalar.fill(0);
  const unsigned=Buffer.from(pending.unsigned,'base64'),length=Buffer.alloc(4);length.writeUInt32BE(unsigned.length);const {canonicalSignature02}=await import(sdk+'draft02-manifest.js');const signature=canonicalSignature02(new Uint8Array(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},key,Buffer.concat([Buffer.from('ZT/contact-reader/authorization/v1\0'),length,unsigned]))));statement=new Uint8Array(Buffer.concat([unsigned,signature]));const {File}=require('node:buffer');f.nodes['issuer-signature'].files=[new File([statement],'signed-statement.bin')];return statement;
 }
 return Object.assign(f,{requests,stateMode:v=>stateMode=v,createMode:v=>createMode=v,holdIssuer:v=>hold=v,sign,getPending:()=>pending,issuerStatus:()=>f.nodes['issuer-status'].textContent});
}
async function issuerReview(f){f.nodes['issuer-status'].textContent='';click(f,'issuer-review');await waitFor(()=>!f.nodes['issuer-create'].disabled||/unavailable|ended/i.test(f.issuerStatus()));}
async function issuerCreate(f,retry=false){f.nodes['issuer-status'].textContent='';click(f,retry?'issuer-retry':'issuer-create');await waitFor(()=>!f.nodes['issuer-export'].disabled||/outcome|unknown|unavailable/i.test(f.issuerStatus()));await new Promise(r=>setImmediate(r));}

test('paired DOM flow uses real private accepted history and whole root-signed packet',async()=>{const f=await issuerFixture();try{await issuerReview(f);assert.equal(f.nodes['issuer-create'].disabled,false);await issuerCreate(f);assert.match(f.issuerStatus(),/Original intent saved/);click(f,'issuer-export');await waitFor(()=>f.nodes['issuer-facts'].textContent.includes('Public proposal'));assert.match(f.nodes['issuer-facts'].textContent,/--bundle ababab/);assert.equal(f.downloads.length,1);const proposal=JSON.parse(await f.downloads[0].text());assert.deepEqual(Object.keys(proposal),['create','pending']);await f.sign();click(f,'issuer-import');await waitFor(()=>!f.nodes['issuer-complete'].disabled);f.nodes['issuer-factor'].value='123456';click(f,'issuer-complete');await waitFor(()=>/acknowledged this exact/.test(f.issuerStatus()));assert.equal(f.nodes['issuer-factor'].value,'');assert.equal(f.requests.filter(r=>r.options.method==='POST').length,2);assert.equal(f.review.status().current,undefined);}finally{f.review.close();}});
test('absent state, exhausted revision, wrong root and bounded duplicate-aware bootstrap refuse positives',async()=>{for(const mode of ['absent','max','wrong-root','duplicate','escaped','oversized']){const f=await issuerFixture();try{f.stateMode(mode);await issuerReview(f);assert.equal(f.nodes['issuer-create'].disabled,true,mode);assert.equal(f.requests.filter(r=>r.options.method==='POST').length,0,mode);}finally{f.review.close();}}});
test('independent existing kit, reader and until inputs refuse before content transport',async()=>{for(const name of ['bundle','reader-id','reader-point','requested-until']){const f=await issuerFixture();try{f.nodes[name].value=name==='requested-until'?'0':'00';await issuerReview(f);assert.equal(f.requests.length,0);assert.equal(f.nodes['issuer-create'].disabled,true);}finally{f.review.close();}}});
test('genuine source mismatch or creator-session mismatch leaves only original uncertainty',async()=>{for(const mode of ['wrong-source','wrong-actor','expanded-ceiling','contracted-ceiling','source-below-intent','expanded-intent','shortened-intent']){const f=await issuerFixture();try{f.createMode(mode);await issuerReview(f);await issuerCreate(f);assert.match(f.issuerStatus(),/unknown/i);assert.equal(f.nodes['issuer-complete'].disabled,true);assert.equal(f.requests.filter(r=>r.options.method==='POST').length,1);await assert.rejects(f.review.prepare());}finally{f.review.close();}}});
test('three uncertain CREATE transports share one body and leave no fourth positive capacity',async()=>{const f=await issuerFixture();try{f.createMode('uncertain');await issuerReview(f);for(let i=0;i<3;i++){await issuerCreate(f,i>0);assert.match(f.issuerStatus(),/unknown/i);}const count=f.requests.length;await issuerCreate(f,true);assert.equal(f.requests.length,count);assert.equal(f.nodes['issuer-retry'].disabled,true);assert.equal(f.nodes['issuer-complete'].disabled,true);assert.equal(new Set(f.requests.filter(r=>r.options.method==='POST').map(r=>r.options.body)).size,1);}finally{f.review.close();}});
test('idle sixty-second approval ends before longer root review and never renews',async t=>{const f=await issuerFixture();t.mock.timers.enable({apis:['setTimeout']});try{click(f,'issuer-review');for(let n=0;n<10000&&f.nodes['issuer-create'].disabled;n++)await new Promise(r=>setImmediate(r));assert.equal(f.nodes['issuer-create'].disabled,false);t.mock.timers.tick(60001);assert.match(f.issuerStatus(),/approval ended/i);click(f,'issuer-create');await new Promise(r=>setImmediate(r));assert.equal(f.requests.filter(r=>r.options.method==='POST').length,0);assert.equal(f.nodes['issuer-create'].disabled,true);}finally{t.mock.timers.reset();f.review.close();}});
test('ambiguous COMPLETE clears factor and cannot retry or replace the whole packet',async()=>{const f=await issuerFixture();try{await issuerReview(f);await issuerCreate(f);await f.sign();click(f,'issuer-import');await waitFor(()=>!f.nodes['issuer-complete'].disabled);f.createMode('complete-uncertain');f.nodes['issuer-factor'].value='123456';click(f,'issuer-complete');await waitFor(()=>/approval ended|unknown/i.test(f.issuerStatus()));const sent=f.requests.filter(r=>r.url.endsWith('/complete')).length;assert.equal(sent,1);assert.equal(f.nodes['issuer-factor'].value,'');f.nodes['issuer-factor'].value='123456';click(f,'issuer-complete');await new Promise(r=>setImmediate(r));assert.equal(f.nodes['issuer-factor'].value,'');assert.equal(f.requests.filter(r=>r.url.endsWith('/complete')).length,1);click(f,'issuer-import');await new Promise(r=>setImmediate(r));assert.equal(f.nodes['issuer-complete'].disabled,true);}finally{f.review.close();}});
test('expired approval permits exact ordinary cancel without root history or MFA',async()=>{const f=await issuerFixture();try{await issuerReview(f);await issuerCreate(f);click(f,'issuer-decline');await waitFor(()=>/approval ended/.test(f.issuerStatus()));const db=await new Promise((yes,no)=>{const q=indexedDB.open('ztse-draft02-trust-v1',1);q.onsuccess=()=>yes(q.result);q.onerror=()=>no(q.error);});try{await new Promise((yes,no)=>{const tx=db.transaction('owner-root-high-water','readwrite');tx.objectStore('owner-root-high-water').clear();tx.oncomplete=yes;tx.onabort=no;});}finally{db.close();}const {Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),store=await Draft02TrustStore.open();try{assert.equal(await store.read(),null);}finally{store.close();}click(f,'issuer-cancel');await waitFor(()=>/reduction acknowledged/.test(f.issuerStatus()));const request=f.requests.find(r=>r.url.endsWith('/cancel'));assert.deepEqual(Object.keys(JSON.parse(request.options.body)),['generation','create_request','unsigned_digest']);assert.equal(f.nodes['issuer-factor'].value,'');assert.equal(f.nodes['issuer-create'].disabled,true);}finally{f.review.close();}});
test('held bootstrap context drift refuses before CREATE with actual history preserved',async()=>{const f=await issuerFixture();let release,held=false;try{f.holdIssuer(url=>url.includes('/export')?new Promise(r=>{held=true;release=r;}):Promise.resolve());click(f,'issuer-review');await waitFor(()=>held);f.nodes['reader-id'].value='cd'.repeat(32);release();await waitFor(()=>/unavailable/i.test(f.issuerStatus()));assert.equal(f.requests.filter(r=>r.options.method==='POST').length,0);}finally{if(release)release();f.review.close();}});
test('escaped wire-key guard removal changes the genuine DOM bootstrap outcome',async()=>{const needle='if(key&&!/^"[A-Za-z][A-Za-z0-9_]*"$/.test(raw))refuse();';const f=await issuerFixture(s=>{assert.equal(s.split(needle).length,2);return s.replace(needle,'if(false)refuse();');});try{f.stateMode('escaped');await issuerReview(f);assert.equal(f.nodes['issuer-create'].disabled,false,'the malformed key reaches real review only when its guard is removed');assert.equal(f.requests.filter(r=>r.options.method==='POST').length,0);}finally{f.review.close();}});
test('four unsettled issuer fetches remain globally charged across close and late settlement',async()=>{const fs=[];for(let i=0;i<5;i++)fs.push(await issuerFixture());const releases=[];try{for(let i=0;i<4;i++){fs[i].holdIssuer(()=>new Promise(r=>releases.push(r)));click(fs[i],'issuer-review');await waitFor(()=>releases.length===i+1);}await issuerReview(fs[4]);assert.equal(fs[4].requests.length,0);for(let i=0;i<4;i++)fs[i].review.close();const closedText=fs.slice(0,4).map(f=>f.issuerStatus());await assert.rejects(fs[4].review.prepare());assert.equal(releases.length,4);releases.forEach(r=>r());await new Promise(r=>setTimeout(r,30));assert.equal((await fs[4].review.prepare()).phase,'REVIEWING');for(let i=0;i<4;i++){assert.equal(fs[i].nodes['issuer-create'].disabled,true);assert.equal(fs[i].review.status().phase,'CLOSED');assert.equal(fs[i].issuerStatus(),closedText[i],'late rejection/settlement cannot publish status after close');}}finally{releases.forEach(r=>r());fs.forEach(f=>f.review.close());}});
test('pruned genuine stored history cannot turn a pending projection into accepted authority',async()=>{const f=await issuerFixture();try{await issuerReview(f);const db=await new Promise((yes,no)=>{const q=indexedDB.open('ztse-draft02-trust-v1',1);q.onsuccess=()=>yes(q.result);q.onerror=()=>no(q.error);});try{await new Promise((yes,no)=>{const tx=db.transaction('owner-root-high-water','readwrite'),store=tx.objectStore('owner-root-high-water'),q=store.openCursor();q.onsuccess=()=>{const c=q.result;if(c){if(typeof c.key==='string'&&c.key.startsWith('accepted-manifest:'))c.delete();c.continue();}};tx.oncomplete=yes;tx.onabort=no;});}finally{db.close();}await issuerCreate(f);assert.match(f.issuerStatus(),/unknown/i);assert.equal(f.nodes['issuer-import'].disabled,true);assert.equal(f.nodes['issuer-complete'].disabled,true);assert.equal(f.requests.filter(r=>r.url.endsWith('/intents')).length,1);}finally{f.review.close();}});
test('owner drift after genuine pending history verification refuses positive publication',async()=>{const f=await issuerFixture(),{Draft02TrustStore}=await import(sdk+'draft02-trust-store.js'),original=Draft02TrustStore.prototype.verifyStoredHistory;try{await issuerReview(f);Draft02TrustStore.prototype.verifyStoredHistory=async function(...args){const result=await original.apply(this,args);f.setSession(s=>s.session_id='44444444-4444-4444-8444-444444444444');return result;};await issuerCreate(f);assert.match(f.issuerStatus(),/unknown/i);assert.equal(f.nodes['issuer-complete'].disabled,true);assert.equal(f.nodes['issuer-retry'].disabled,true);}finally{Draft02TrustStore.prototype.verifyStoredHistory=original;f.review.close();}});
test('read-only recovery preserves original commitment and cannot manufacture another approval',async()=>{const f=await issuerFixture();let g;try{f.createMode('uncertain');await issuerReview(f);await issuerCreate(f);click(f,'issuer-recovery-export');await waitFor(()=>f.downloads.length===1);const bytes=await f.downloads[0].arrayBuffer(),{File}=require('node:buffer');g=await fixture();g.nodes['issuer-recovery'].files=[new File([bytes],'recovery.json')];click(g,'issuer-recover');await waitFor(()=>g.nodes['issuer-status'].textContent.includes('read-only lookup'));assert.equal(g.nodes['issuer-create'].disabled,true);assert.equal(g.nodes['issuer-complete'].disabled,true);assert.equal(g.nodes['issuer-lookup'].disabled,false);click(g,'issuer-create');await new Promise(r=>setImmediate(r));assert.equal(g.nodes['issuer-create'].disabled,true);await assert.rejects(g.review.prepare());}finally{if(g)g.review.close();f.review.close();}});

test('CREATE retry and COMPLETE consume the same three positive attempts',async()=>{const f=await issuerFixture();try{await issuerReview(f);f.createMode('uncertain');await issuerCreate(f);f.createMode('valid');await issuerCreate(f,true);await f.sign();click(f,'issuer-import');await waitFor(()=>!f.nodes['issuer-complete'].disabled);f.nodes['issuer-factor'].value='123456';click(f,'issuer-complete');await waitFor(()=>/acknowledged this exact/.test(f.issuerStatus()));const sent=f.requests.filter(r=>r.options.method==='POST');assert.equal(sent.length,3);assert.equal(sent[0].options.body,sent[1].options.body);assert.equal(sent[2].url.endsWith('/complete'),true);click(f,'issuer-retry');f.nodes['issuer-factor'].value='123456';click(f,'issuer-complete');await new Promise(r=>setImmediate(r));assert.equal(f.requests.filter(r=>r.options.method==='POST').length,3);assert.equal(f.nodes['issuer-factor'].value,'');}finally{f.review.close();}});

test('input drift after review closes positive actions without spending another attempt',async()=>{const f=await issuerFixture();try{await issuerReview(f);f.nodes.bundle.value='cd'.repeat(16);click(f,'issuer-create');await waitFor(()=>/unavailable|unknown/i.test(f.issuerStatus()));assert.equal(f.requests.filter(r=>r.options.method==='POST').length,0);assert.equal(f.nodes['issuer-create'].disabled,true);assert.equal(f.nodes['issuer-retry'].disabled,true);assert.equal(f.nodes['issuer-complete'].disabled,true);}finally{f.review.close();}});
