// SPDX-License-Identifier: AGPL-3.0-only
"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),line=require("./conversation-line-setup.js");
const enc=new TextEncoder(),cat=(...xs)=>Uint8Array.from(xs.flatMap(x=>[...x])),hash=async b=>new Uint8Array(await crypto.subtle.digest("SHA-256",b));
const num=n=>{const b=new Uint8Array(8);new DataView(b.buffer).setBigUint64(0,BigInt(n));return b;},text=s=>{const b=enc.encode(s),n=new Uint8Array(2);new DataView(n.buffer).setUint16(0,b.length);return cat(n,b);};
// Same public geometry/scope as root-material line_key_registration/fixture.rs.
async function fixture(issued=1000,expires=301000){
 // Published P-256 generator and 2G, 4G fixture points; no private production key.
 const points=["046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5","047cf27b188d034f7e8a52380304b51ac3c08969e277f21b35a60b48fc4766997807775510db8ed040293d9ac69f7430dbba7dade63ce982299e04b79d227873d1","04e2534a3532d08fbba02dde659ee62bd0031fe2db785596ef509302446b030852e0f1575a4c633cc719dfee5fda862d764efc96c3f30ee0055c42c23f184ed8c6"].map(h=>Uint8Array.from(Buffer.from(h,"hex")));
 const pin=cat(enc.encode("ZTRP\x02"),new Uint8Array(16).fill(1),num(1),points[0]),fp=await hash(cat(enc.encode("ZTSE/root-pin/v2\0"),pin));
 const bytes=cat(enc.encode("ZTSE/line/owner-key/register/v1\0"),...[1,2,3,4,5].map(n=>new Uint8Array(16).fill(n)),num(1),new Uint8Array(16).fill(6),new Uint8Array(32).fill(7),num(issued),num(expires),pin,fp,points[1],await hash(points[1]),await hash(points[2]),num(8),num(9),text("site-fixture"),text("instance-fixture"),text("https://owner.invalid"));
 const expected=line.parseRegistration(bytes);return {bytes,expected};
}
test("shared Rust fixture scope and geometry are independently verified",async()=>{const f=await fixture(),s=await line.inspectRegistration(f.bytes,f.expected,2000n);assert.equal(s.generation,1n);assert.equal(s.connectionEpoch,8n);assert.equal(s.deploymentEpoch,9n);assert.equal(s.account,"01010101-0101-0101-0101-010101010101");assert.equal(s.site,"site-fixture");});
for(const field of ["account","user","session","device","line","generation","connectionEpoch","deploymentEpoch","site","instance","origin"])test("independent "+field+" substitution is rejected",async()=>{const f=await fixture();f.expected[field]=typeof f.expected[field]==="bigint"?2n:"substituted";await assert.rejects(line.inspectRegistration(f.bytes,f.expected,2000n));});
for(const field of ["rootPin","rootFingerprint","approvalPoint","approvalFingerprint","pairedFingerprint"])test("independent "+field+" substitution is rejected",async()=>{const f=await fixture();f.expected[field]=Uint8Array.from(f.expected[field]);f.expected[field][0]^=1;await assert.rejects(line.inspectRegistration(f.bytes,f.expected,2000n));});
for(const now of [999n,301000n])test("time outside exact five-minute packet is refused: "+now,async()=>{const f=await fixture();await assert.rejects(line.inspectRegistration(f.bytes,f.expected,now));});
test("purpose, truncation and trailing bytes are rejected",async()=>{const f=await fixture(),bad=Uint8Array.from(f.bytes);bad[0]^=1;for(const b of [bad,f.bytes.subarray(0,f.bytes.length-1),cat(f.bytes,Uint8Array.of(0))])assert.throws(()=>line.parseRegistration(b));});
test("root signature cannot be substituted with approval signature",async()=>{const f=await fixture(),pair=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},false,["sign","verify"]),sig=line.normalizeSignature(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},pair.privateKey,f.bytes)));await assert.rejects(line.verifyRegistrationRoot(f.expected,sig));});

async function phoneFixture(){const f=await fixture(),key=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},false,["sign","verify"]),point=new Uint8Array(await crypto.subtle.exportKey("raw",key.publicKey)),ids=[f.expected.account,f.expected.line,f.expected.device,f.expected.challenge].map(id=>Uint8Array.from(Buffer.from(id.replaceAll("-",""),"hex"))),api=Uint8Array.of(0,31,1,0,0,0,4),bytes=cat(enc.encode("ZTSE/line/device-confirm/v1\0"),ids[0],ids[1],ids[2],num(1),ids[3],f.expected.nonce,api),signature=line.derFromRaw(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key.privateKey,bytes))),expected={account:f.expected.account,line:f.expected.line,device:f.expected.device,generation:1n,challenge:f.expected.challenge,nonce:f.expected.nonce,phonePoint:point,pairedFingerprint:await hash(point)};return {bytes,signature,expected};}
test("paired phone proof reconstructs exact existing SEALED owner domain",async()=>{const f=await phoneFixture(),p=await line.verifyPhoneProof(f.bytes,f.signature,f.expected);assert.equal(p.androidApi,31);assert.equal(p.subscription,4);assert.deepEqual(p.ownerStatement,cat(enc.encode("ZTSE/line/owner-approve/v1\0"),f.bytes,await hash(f.signature)));});
for(const field of ["account","line","device","generation","challenge"])test("phone proof exact "+field+" substitution refused",async()=>{const f=await phoneFixture();f.expected[field]=field==="generation"?2n:"different";await assert.rejects(line.verifyPhoneProof(f.bytes,f.signature,f.expected));});
test("wrong paired key and malformed DER refuse approval",async()=>{const f=await phoneFixture();f.expected.pairedFingerprint[0]^=1;await assert.rejects(line.verifyPhoneProof(f.bytes,f.signature,f.expected));const g=await phoneFixture();g.signature[1]--;await assert.rejects(line.verifyPhoneProof(g.bytes,g.signature,g.expected));});
for(const mode of ["api","multiSIM","negativeSubscription"])test(mode+" fail closed before signature verification",async()=>{const f=await phoneFixture();f.bytes[f.bytes.length-(mode==="api"?6:mode==="multiSIM"?5:4)]=mode==="api"?28:mode==="multiSIM"?2:255;await assert.rejects(line.verifyPhoneProof(f.bytes,f.signature,f.expected),/single-SIM/);});

// Exact public vector independently produced by the shared Rust codec.
test("native shared public vector is byte-exact",async()=>{const f=await fixture(2000,62000);assert.equal(Buffer.from(f.bytes).toString("hex"),"5a5453452f6c696e652f6f776e65722d6b65792f72656769737465722f7631000101010101010101010101010101010102020202020202020202020202020202030303030303030303030303030303030404040404040404040404040404040405050505050505050505050505050505000000000000000106060606060606060606060606060606070707070707070707070707070707070707070707070707070707070707070700000000000007d0000000000000f2305a54525002010101010101010101010101010101010000000000000001046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5650363c155189c0015b94a30cd545f34c4894e88f12d486f4e47694634068540047cf27b188d034f7e8a52380304b51ac3c08969e277f21b35a60b48fc4766997807775510db8ed040293d9ac69f7430dbba7dade63ce982299e04b79d227873d1a9f300eb5960e89133af7362011a1e26f0e2ea2e36dc402a04af6c192b891a8c617e37f7a48d30a63de6efeaa44faa4832e06c17d000e5499d3c5876cc22508000000000000000080000000000000009000c736974652d666978747572650010696e7374616e63652d66697874757265001568747470733a2f2f6f776e65722e696e76616c6964");assert.equal(Buffer.from(await hash(f.bytes)).toString("hex"),"8ae2bc3d84891920b6de2778d670ac4db48720b07799ce9bbc683ccaf2dc8e63");});

test("actual fixture existing root approves identical raw transcript only",async()=>{const f=await fixture(),p=f.expected.rootPin.subarray(29),d=new Uint8Array(32);d[31]=1;const b64=b=>Buffer.from(b).toString("base64url"),key=await crypto.subtle.importKey("jwk",{kty:"EC",crv:"P-256",x:b64(p.subarray(1,33)),y:b64(p.subarray(33)),d:b64(d)},{name:"ECDSA",namedCurve:"P-256"},false,["sign"]),sig=line.normalizeSignature(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,f.bytes)));await line.verifyRegistrationRoot(f.expected,sig);const bad={...f.expected,bytes:Uint8Array.from(f.bytes)};bad.bytes[bad.bytes.length-1]^=1;await assert.rejects(line.verifyRegistrationRoot(bad,sig));});
test("caller mutation cannot replace expected scope during crypto wait",async()=>{const f=await fixture(),pending=line.inspectRegistration(f.bytes,f.expected,2000n);f.expected.rootFingerprint.fill(0);f.expected.origin="https://changed.invalid";assert.equal((await pending).origin,"https://owner.invalid");});
async function setupFixture({enabled=true}={}){
 const f=await fixture(),s=f.expected,b64=b=>Buffer.from(b).toString("base64"),publicFile=b=>({size:b.length,arrayBuffer:async()=>Uint8Array.from(b).buffer}),id=n=>Buffer.alloc(16,n).toString("hex").replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,"$1-$2-$3-$4-$5"),phonePoint=Uint8Array.from(Buffer.from("04e2534a3532d08fbba02dde659ee62bd0031fe2db785596ef509302446b030852e0f1575a4c633cc719dfee5fda862d764efc96c3f30ee0055c42c23f184ed8c6","hex"));
 async function privateKey(point,n){const d=new Uint8Array(32);d[31]=n;return crypto.subtle.importKey("jwk",{kty:"EC",crv:"P-256",x:Buffer.from(point.subarray(1,33)).toString("base64url"),y:Buffer.from(point.subarray(33)).toString("base64url"),d:Buffer.from(d).toString("base64url")},{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);}
 const rootKey=await privateKey(s.rootPin.subarray(29),1),phoneKey=await privateKey(phonePoint,4),paired=await hash(phonePoint),children=[],requests=[],events={};let mono=0,phase="awaiting_device",ack=false,packet=null,receipt=null,completion=0,approval=0,hold=null,unknownComplete=false,unknownApprove=false,sessionId=s.session,projectionChange=null;
 const selection={enabled:true,sessionConsent:true,account_id:s.account,device_id:s.device,line_id:s.line,nextGeneration:"1",rootFingerprint:Buffer.from(s.rootFingerprint).toString("hex"),pairedFingerprint:Buffer.from(paired).toString("hex"),origin:s.origin};
 const document={cookie:"__Host-zrotext_csrf=fixture",hidden:false,addEventListener:(e,fn)=>events[e]=fn,removeEventListener(){},createElement:()=>({append(){},remove(){children.pop();}})},window={location:{origin:s.origin},confirm:()=>true,addEventListener:(e,fn)=>events[e]=fn,removeEventListener(){}};
 const challengeId=id(9),nonce=Uint8Array.from(Buffer.alloc(32,9)),phoneBytes=cat(enc.encode("ZTSE/line/device-confirm/v1\0"),Uint8Array.from(Buffer.alloc(16,1)),Uint8Array.from(Buffer.alloc(16,5)),Uint8Array.from(Buffer.alloc(16,4)),num(1),Uint8Array.from(Buffer.alloc(16,9)),nonce,Uint8Array.of(0,31,1,0,0,0,4)),phoneSignatureInitial=line.derFromRaw(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},phoneKey,phoneBytes)));let phoneSignature=phoneSignatureInitial,ownerBytes=cat(enc.encode("ZTSE/line/owner-approve/v1\0"),phoneBytes,await hash(phoneSignature));
 const request=async(path,options)=>{const body=options.body?JSON.parse(options.body):null;requests.push({path,options,body});if(hold)await hold(path,options);let value;
 if(path==="/v1/auth/session")value={account_id:s.account,user_id:s.user,session_id:sessionId,role:"owner"};
 else if(path.endsWith("/bootstrap")){value={v:1,untrusted_projection:true,account_id:s.account,user_id:s.user,session_id:sessionId,device_id:s.device,line_id:s.line,expected_next_binding_generation:"1",root_pin:b64(s.rootPin),root_fingerprint:b64(s.rootFingerprint),current_device_signing_fingerprint:b64(paired),connection_epoch:"8",deployment_epoch:"9",site_id:s.site,instance_id:s.instance,server_now_ms:"2000"};if(projectionChange)projectionChange(value);}
 else if(path.endsWith("/owner-key/challenge")){const ap=Uint8Array.from(Buffer.from(body.approval_point,"base64"));assert.equal(ap.length,65);packet=cat(enc.encode("ZTSE/line/owner-key/register/v1\0"),...[1,2,3,4,5].map(n=>Uint8Array.from(Buffer.alloc(16,n))),num(1),Uint8Array.from(Buffer.alloc(16,6)),Uint8Array.from(Buffer.alloc(32,7)),num(2000),num(62000),s.rootPin,s.rootFingerprint,ap,await hash(ap),paired,num(8),num(9),text(s.site),text(s.instance),text(s.origin));value={challenge_id:id(6),unsigned_statement:b64(packet),issued_ms:"2000",expires_ms:"62000",root_pin:b64(s.rootPin),root_fingerprint:b64(s.rootFingerprint),current_device_signing_fingerprint:b64(paired),approval_fingerprint:b64(await hash(ap))};}
 else if(path.endsWith("/complete")){completion++;assert.equal(body.factor,"fixture-factor");const parsed=line.parseRegistration(packet);await line.verifyRegistrationRoot(parsed,Uint8Array.from(Buffer.from(body.root_signature,"base64")));const k=await crypto.subtle.importKey("raw",parsed.approvalPoint,{name:"ECDSA",namedCurve:"P-256"},false,["verify"]);assert.equal(await crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},k,Uint8Array.from(Buffer.from(body.approval_signature,"base64")),packet),true);receipt={registration_id:id(6),unsigned_statement:b64(packet),root_signature:body.root_signature,approval_signature:body.approval_signature,completed_ms:"2000",assigned_challenge_id:null,retired_ms:null,activated_ms:null};if(unknownComplete)throw Error("Fixture lost response");value={receipt};}
 else if(path.endsWith("/status"))value={receipt};
 else if(path.endsWith("/challenges"))value={challenge_id:challengeId,account_id:s.account,line_id:s.line,device_id:s.device,binding_generation:"1",nonce:b64(nonce),expires_ms:"62000",status:phase,phone_acknowledged:false};
 else if(path.endsWith("/view"))value={challenge_id:challengeId,line_id:s.line,device_id:s.device,binding_generation:"1",expires_ms:"62000",status:phase,phone_acknowledged:ack,observation:phase==="awaiting_owner"?{android_api_level:31,active_subscription_count:1,selected_subscription_id:4}:null,device_statement:phase==="awaiting_owner"?b64(phoneBytes):null,device_signature_der:phase==="awaiting_owner"?b64(phoneSignature):null,owner_statement:phase==="awaiting_owner"?b64(ownerBytes):null};
 else if(path.endsWith("/approve")){approval++;const p=line.parseRegistration(packet).approvalPoint,key=require("node:crypto").createPublicKey({key:{kty:"EC",crv:"P-256",x:Buffer.from(p.subarray(1,33)).toString("base64url"),y:Buffer.from(p.subarray(33)).toString("base64url")},format:"jwk"});assert.equal(require("node:crypto").verify("sha256",ownerBytes,key,Buffer.from(body.owner_signature_der,"base64")),true);phase="activated";if(unknownApprove)throw Error("Fixture lost approval response");return new Response(null,{status:204});}
 else throw Error("Unknown fixture endpoint");return new Response(JSON.stringify(value),{headers:{"Content-Type":"application/json"}});};
 const controller=line.create({enabled,document,window,host:{append:p=>children.push(p)},readSelection:()=>selection,fetch:request,URL:{createObjectURL:()=>"blob:fixture",revokeObjectURL(){}},monotonic:()=>mono});
 return {controller,phoneFile:publicFile(phonePoint),async rootFile(){return publicFile(line.normalizeSignature(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},rootKey,packet))));},selection,children,requests,events,window,document,get completion(){return completion;},get approval(){return approval;},setPhase:v=>phase=v,setAck:v=>ack=v,setMono:v=>mono=v,hold:fn=>hold=fn,replaceSession:()=>sessionId=id(10),mutateProjection:fn=>projectionChange=fn,signedPhoneProof:()=>({bytes:phoneBytes,signature:phoneSignature,point:phonePoint}),wrongProofNonce:async()=>{phoneBytes[enc.encode("ZTSE/line/device-confirm/v1\0").length+16*4+8]^=1;phoneSignature=line.derFromRaw(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},phoneKey,phoneBytes)));ownerBytes=cat(enc.encode("ZTSE/line/owner-approve/v1\0"),phoneBytes,await hash(phoneSignature));},loseApprove:()=>unknownApprove=true,loseComplete:()=>unknownComplete=true};
}
test("concrete registration and SEALED exchange waits for durable phone ACK",async()=>{const f=await setupFixture();try{assert.equal((await f.controller.begin(f.phoneFile)).phase,"awaiting_root");assert.equal(f.children.length,1);assert.equal((await f.controller.complete(await f.rootFile(),"fixture-factor")).phase,"registered");await f.controller.open();assert.equal((await f.controller.view()).phase,"awaiting_device");f.setPhase("awaiting_owner");assert.equal((await f.controller.view()).subscription,4);assert.equal((await f.controller.approve()).phase,"activation_committed");assert.equal((await f.controller.view()).phase,"activation_committed");f.setAck(true);assert.equal((await f.controller.view()).phase,"phone_acknowledged");assert.equal(f.completion,1);assert.equal(f.approval,1);assert.equal(f.children.length,0);for(const r of f.requests.filter(r=>r.body))assert.equal(r.body.expected_session_id,f.selection.account_id.replaceAll("01","03"));}finally{f.controller.close();}});
test("disabled line setup performs zero HTTP and key setup",async()=>{const f=await setupFixture({enabled:false});await assert.rejects(f.controller.begin(f.phoneFile));assert.equal(f.requests.length,0);});
for(const mode of ["close","expiry","session","selection","csrf","decline"])test("line registration "+mode+" causes zero completion",async()=>{const f=await setupFixture();try{await f.controller.begin(f.phoneFile);const file=await f.rootFile();if(mode==="close")f.controller.close();if(mode==="expiry")f.setMono(60000);if(mode==="session")f.replaceSession();if(mode==="selection")f.selection.line_id=f.selection.device_id;if(mode==="csrf")f.document.cookie="__Host-zrotext_csrf=replaced";if(mode==="decline")f.window.confirm=()=>false;await assert.rejects(f.controller.complete(file,"fixture-factor"));assert.equal(f.completion,0);}finally{f.controller.close();}});
test("lost registration response reconciles immutable receipt without repeating factor",async()=>{const f=await setupFixture();try{await f.controller.begin(f.phoneFile);f.loseComplete();await assert.rejects(f.controller.complete(await f.rootFile(),"fixture-factor"),/unknown/);await assert.rejects(f.controller.complete(await f.rootFile(),"fixture-factor"));assert.equal((await f.controller.reconcileRegistration()).phase,"registered");assert.equal(f.completion,1);}finally{f.controller.close();}});
test("held raw signature file abort cannot complete",async()=>{const f=await setupFixture();await f.controller.begin(f.phoneFile);const signed=await f.rootFile();let release;const pending=f.controller.complete({size:64,arrayBuffer:()=>new Promise(r=>release=r)},"fixture-factor");f.controller.close();release(await signed.arrayBuffer());await assert.rejects(pending);assert.equal(f.completion,0);});
test("held challenge response close cannot publish session candidate",async()=>{const f=await setupFixture();let release;f.hold(path=>path.endsWith("/owner-key/challenge")?new Promise(r=>release=r):undefined);const pending=f.controller.begin(f.phoneFile);while(!release)await new Promise(r=>setImmediate(r));f.controller.close();release();await assert.rejects(pending);assert.equal(f.children.length,0);assert.equal(f.controller.state().closed,true);});
test("replaced operational lease cannot register previously approved scope",async()=>{const f=await setupFixture();try{await f.controller.begin(f.phoneFile);f.mutateProjection(v=>v.connection_epoch="10");await assert.rejects(f.controller.complete(await f.rootFile(),"fixture-factor"),/lease/);assert.equal(f.completion,0);}finally{f.controller.close();}});

async function awaitingOwner(f){await f.controller.begin(f.phoneFile);await f.controller.complete(await f.rootFile(),"fixture-factor");await f.controller.open();f.setPhase("awaiting_owner");await f.controller.view();}
test("held owner approval current-session read abort causes zero approval",async()=>{const f=await setupFixture();await awaitingOwner(f);let release;f.hold(path=>path==="/v1/auth/session"?new Promise(r=>release=r):undefined);const pending=f.controller.approve();while(!release)await new Promise(r=>setImmediate(r));f.controller.close();release();await assert.rejects(pending);assert.equal(f.approval,0);});
test("expired session key cannot approve selected SIM proof",async()=>{const f=await setupFixture();await awaitingOwner(f);f.setMono(60000);await assert.rejects(f.controller.approve());assert.equal(f.approval,0);assert.equal(f.controller.state().closed,true);});
test("lost owner approval response needs explicit read and never repeats signature submit",async()=>{const f=await setupFixture();try{await awaitingOwner(f);f.loseApprove();await assert.rejects(f.controller.approve(),/unknown/);await assert.rejects(f.controller.approve());assert.equal((await f.controller.view()).phase,"activation_committed");f.setAck(true);assert.equal((await f.controller.view()).phase,"phone_acknowledged");assert.equal(f.approval,1);}finally{f.controller.close();}});
test("new approval private key is nonextractable and late generation abort cannot publish",async()=>{const f=await setupFixture(),original=crypto.subtle.generateKey.bind(crypto.subtle);let release,extractable;const descriptor=Object.getOwnPropertyDescriptor(crypto.subtle,"generateKey");Object.defineProperty(crypto.subtle,"generateKey",{configurable:true,value:async(algorithm,exportable,usages)=>{extractable=exportable;const candidate=await original(algorithm,exportable,usages);await assert.rejects(crypto.subtle.exportKey("pkcs8",candidate.privateKey));await new Promise(r=>release=r);return candidate;}});try{const pending=f.controller.begin(f.phoneFile);while(!release)await new Promise(r=>setImmediate(r));f.controller.close();release();await assert.rejects(pending);assert.equal(extractable,false);assert.equal(f.children.length,0);assert.equal(f.requests.filter(v=>v.path.endsWith("/owner-key/challenge")).length,0);}finally{if(descriptor)Object.defineProperty(crypto.subtle,"generateKey",descriptor);else delete crypto.subtle.generateKey;f.controller.close();}});

test("local state revalidation observes replaced CSRF and closes memory custody without HTTP",async()=>{const f=await setupFixture();await f.controller.begin(f.phoneFile);const count=f.requests.length;f.document.cookie="__Host-zrotext_csrf=replaced";assert.equal(f.controller.state().closed,true);assert.equal(f.children.length,0);assert.equal(f.requests.length,count);});

test("legitimate paired phone signature with wrong frozen challenge nonce cannot be approved",async()=>{const f=await setupFixture();await f.controller.begin(f.phoneFile);await f.controller.complete(await f.rootFile(),"fixture-factor");await f.controller.open();f.setPhase("awaiting_owner");await f.wrongProofNonce();const proof=f.signedPhoneProof(),p=proof.point,key=require("node:crypto").createPublicKey({key:{kty:"EC",crv:"P-256",x:Buffer.from(p.subarray(1,33)).toString("base64url"),y:Buffer.from(p.subarray(33)).toString("base64url")},format:"jwk"});assert.equal(require("node:crypto").verify("sha256",proof.bytes,key,proof.signature),true);await assert.rejects(f.controller.view(),/scope changed/);assert.equal(f.approval,0);assert.equal(f.controller.state().closed,true);});
