// SPDX-License-Identifier: AGPL-3.0-only
const test=require("node:test"),assert=require("node:assert/strict"),{create}=require("./conversation-owner-setup.js"),Bootstrap=require("./conversation-bootstrap.js"),{createHash}=require("node:crypto");
const hex=b=>Buffer.from(b).toString("hex"),uuid=b=>hex(b).replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,"$1-$2-$3-$4-$5"),b64=b=>Buffer.from(b).toString("base64");
async function fixture(){const {genesisFixture}=await import("../../sdk/typescript/test/conversation-genesis-fixture.mjs"),{archiveFixture}=await import("../../sdk/typescript/test/conversation-archive-fixture.mjs"),{join,signFixtureSuccessor02}=await import("../../sdk/typescript/test/conversation-refresh-fixture.mjs"),f=await genesisFixture(),a=await archiveFixture(),api=await import("../../sdk/typescript/dist/conversation-genesis-proposal.js"),sdk=await import("../../sdk/typescript/dist/draft02-manifest.js"),s=f.input.selection,gen=new Uint8Array(8);new DataView(gen.buffer).setBigUint64(0,s.generation);const phone=join(Uint8Array.of(90,84,80,75,1),s.account,s.device,s.line,s.phoneSigningFingerprint,gen,f.input.phoneReaderPoint,f.input.phoneSignerPoint),fp=new Uint8Array(createHash("sha256").update(join(new TextEncoder().encode("ZTSE/phone-keys/v1\0"),phone)).digest()),selection={enabled:true,genesisConsent:true,manifestVersion:"0",manifestDigest:"0".repeat(64),account_id:uuid(s.account),device_id:uuid(s.device),line_id:uuid(s.line),binding_generation:1,peer:s.peer,rootFingerprint:hex(f.input.comparedRootFingerprint),phoneFingerprint:hex(fp),archiveKeyId:hex(a.options.binding.archiveReader),phoneSigningFingerprint:hex(s.phoneSigningFingerprint)},state={posts:[],signed:0,decisions:0,manifest:null,change:null};
 const projection=()=>({v:1,trust_candidate:true,owner_session_live:true,authority_live:true,device_key_live:true,line_binding_live:true,account_id:selection.account_id,session_id:uuid(s.session),device_id:selection.device_id,line_id:selection.line_id,binding_generation:1,peer:s.peer,current_device_signing_fingerprint:b64(s.phoneSigningFingerprint),server_now_ms:"2000",trust_generation:"1",manifest_version:state.manifest?"1":"0",current_manifest:state.manifest?b64(state.manifest.bytes):null,manifest_digest:state.manifest?b64(state.manifest.digest):null,root_pin:b64(f.input.rootPin),root_fingerprint:b64(f.input.comparedRootFingerprint),...state.change});
 const document={cookie:"__Host-zrotext_csrf=fixture",addEventListener(){}},window={location:{origin:f.input.origin},addEventListener(){},confirm(){state.decisions++;return true;}},fetch=async(path,options)=>{state.posts.push(path);if(path.endsWith("/bootstrap"))return new Response(JSON.stringify(projection()),{status:200,headers:{"Content-Type":"application/json"}});if(path.endsWith("/install")){const body=JSON.parse(options.body);state.installBody=body;assert.equal(body.current_device_signing_fingerprint,b64(s.phoneSigningFingerprint));assert.equal(body.expected_root_fingerprint,b64(f.input.comparedRootFingerprint));assert.equal(body.phone_reader_point,b64(f.input.phoneReaderPoint));state.manifest=await sdk.verifyManifest02(new Uint8Array(Buffer.from(body.signed_manifest,"base64")),await sdk.enrollRootPin02(f.input.rootPin,f.input.comparedRootFingerprint),f.input.nowMs);return new Response(null,{status:204});}throw Error("Unexpected fixture path");},bootstrap={...Bootstrap,requestFileSignature({review,typedProposal}){state.signed++;assert.equal(typedProposal[3],71);return {result:signFixtureSuccessor02(f.f,review.unsigned).then(bytes=>{state.afterSign?.();return bytes.slice(-64);})};}},setup=create({enabled:true,document,window,host:{},readSelection:()=>selection,loadSdk:async()=>sdk,loadGenesisSdk:async()=>api,bootstrap,fetch}),file=bytes=>({size:bytes.length,arrayBuffer:async()=>Uint8Array.from(bytes).buffer});return {state,selection,setup,phone:file(phone),archive:file(a.options.encrypted)};}
test("ordinary genesis imports independently compared public artifacts and verifies installed checkpoint",async()=>{const f=await fixture();assert.equal(f.state.posts.length,0);const accepted=await f.setup.provisionInitial(f.phone,f.archive);assert.equal(accepted.manifestVersion,"1");assert.equal(accepted.manifestDigest,hex(f.state.manifest.digest));assert.equal(f.state.decisions,1);assert.equal(f.state.signed,1);assert.equal(f.state.posts.filter(p=>p.endsWith("/install")).length,1);assert.ok(f.state.posts.every(p=>p.includes("/genesis/")));});
test("missing owner decision or independently compared artifact blocks genesis signing",async()=>{for(const field of ["enabled","genesisConsent","phoneFingerprint","archiveKeyId","manifestVersion"]){const f=await fixture();f.selection[field]=field==="enabled"||field==="genesisConsent"?false:field==="manifestVersion"?"1":"09".repeat(32);await assert.rejects(f.setup.provisionInitial(f.phone,f.archive));assert.equal(f.state.signed,0);assert.equal(f.state.posts.filter(p=>p.endsWith("/install")).length,0);}});
test("session key revocation selection substitution and expiry after offline signing block install",async()=>{for(const change of [{owner_session_live:false},{device_key_live:false},{authority_live:false},{line_binding_live:false},{session_id:"09090909-0909-0909-0909-090909090909"},{current_device_signing_fingerprint:b64(new Uint8Array(32).fill(9))},{binding_generation:2},{server_now_ms:"1802000"}]){const f=await fixture();f.state.afterSign=()=>{f.state.change=change;};await assert.rejects(f.setup.provisionInitial(f.phone,f.archive));assert.equal(f.state.posts.filter(p=>p.endsWith("/install")).length,0);}});

test("genesis installation carries the exact owner session reviewed by the custodian",async()=>{const f=await fixture();await f.setup.provisionInitial(f.phone,f.archive);assert.equal(f.state.installBody.expected_session_id,"02020202-0202-0202-0202-020202020202");});

test("genesis transport refuses missing nil and malformed owner session before posting",async()=>{
 const {genesisFixture}=await import("../../sdk/typescript/test/conversation-genesis-fixture.mjs"),{encodeConversationGenesisProposal02}=await import("../../sdk/typescript/dist/conversation-genesis-proposal.js"),{signFixtureSuccessor02}=await import("../../sdk/typescript/test/conversation-refresh-fixture.mjs"),f=await genesisFixture(),i=f.input,s=i.selection,r=await encodeConversationGenesisProposal02(i),signed=await signFixtureSuccessor02(f.f,r.unsigned);let posts=0;
 const http=Bootstrap.createHttp({enabled:true,document:{cookie:"__Host-zrotext_csrf=fixture",addEventListener(){}},window:{addEventListener(){}},fetch:async()=>{posts++;return new Response(null,{status:204});}}),input={device_id:uuid(s.device),line_id:uuid(s.line),binding_generation:Number(s.generation),peer:s.peer,current_device_signing_fingerprint:s.phoneSigningFingerprint,root_fingerprint:i.comparedRootFingerprint,phone_reader_point:i.phoneReaderPoint,archive_reader_point:i.archiveReaderPoint,phone_signer_point:i.phoneSignerPoint,owner_signer_point:i.rootPin.slice(29)};
 for(const expected_session_id of [undefined,"00000000-0000-0000-0000-000000000000","not-a-session"])await assert.rejects(http.genesisInstall({...input,expected_session_id},signed));assert.equal(posts,0);
});
