// SPDX-License-Identifier: AGPL-3.0-only
"use strict";
const {test}=require("node:test"),assert=require("node:assert/strict");
const {createHttp,requestFileSignature}=require("./conversation-bootstrap.js");
const selected={device_id:"11111111-1111-4111-8111-111111111111",line_id:"22222222-2222-4222-8222-222222222222",binding_generation:1,peer:"+12",disclosure_version:1,content_transfer_confirmed:true};
const manifest=new Uint8Array(218),cookie={cookie:"__Host-zrotext_csrf=synthetic-csrf"};
function projection(){const out={...selected,binding_generation:"1",v:1,trust_candidate:true,owner_session_live:true,consent_live:false,account_id:selected.device_id,session_id:selected.line_id,phase:"unprepared",interval_id:null,server_now_ms:"1",manifest_version:"1",trust_generation:"1"};for(const name of ["root_pin","root_fingerprint","current_manifest","manifest_digest","phone_reader_id","phone_reader_point","archive_reader_id","archive_reader_point","phone_signer_id","phone_signer_point"])out[name]=Buffer.alloc(name.endsWith("point")?65:name==="root_pin"?94:name==="current_manifest"?218:32).toString("base64");return out;}
test("authenticated exact projection remains explicitly untrusted",async()=>{let path;const c=createHttp({enabled:true,document:cookie,fetch:async p=>{path=p;return Response.json(projection());}});const r=await c.bootstrap(selected);assert.equal(path,"/v1/owner/conversation/bootstrap");assert.equal(r.trusted,false);assert.equal(r.candidate.root_pin,projection().root_pin);});
test("foreign scope and noncanonical projection are refused",async()=>{for(const change of [{peer:"+13"},{server_now_ms:"01"},{root_pin:"noncanonical"}]){const c=createHttp({enabled:true,document:cookie,fetch:async()=>Response.json({...projection(),...change})});await assert.rejects(c.bootstrap(selected),/projection/);}});
test("projection selection is held across asynchronous response",async()=>{const input={...selected};const c=createHttp({enabled:true,document:cookie,fetch:async()=>{input.peer="+13";return Response.json({...projection(),peer:"+13"});}});await assert.rejects(c.bootstrap(input),/scope refused/);});
test("session changes while statement body is read refuse artifact",async()=>{const document={...cookie};const c=createHttp({enabled:true,document,fetch:async()=>({status:200,headers:new Headers({"Content-Type":"application/vnd.zrotext.conversation-statement.v1"}),arrayBuffer:async()=>{document.cookie="__Host-zrotext_csrf=changed";return Uint8Array.of(1).buffer;}})});await assert.rejects(c.activate(selected,manifest),/session changed/);});
test("disabled bootstrap never invokes HTTP",async()=>{let calls=0;const c=createHttp({document:cookie,fetch:()=>{calls++;}});await assert.rejects(c.activate(selected,manifest),/closed/);assert.equal(calls,0);});
test("activation sends exact fixed scope consent and public successor",async()=>{let seen;const c=createHttp({enabled:true,document:cookie,fetch:async(path,options)=>{seen={path,options};return new Response(Uint8Array.of(1),{status:200,headers:{"Content-Type":"application/vnd.zrotext.conversation-statement.v1"}});}});assert.deepEqual(await c.activate(selected,manifest),Uint8Array.of(1));assert.equal(seen.path,"/v1/owner/conversation/activation");assert.equal(seen.options.redirect,"error");assert.equal(seen.options.credentials,"same-origin");assert.equal(seen.options.headers["x-zrotext-csrf"],"synthetic-csrf");assert.deepEqual(JSON.parse(seen.options.body).consent,selected);});
test("separate consent and canonical scope are required before request",async()=>{let calls=0;const c=createHttp({enabled:true,document:cookie,fetch:()=>{calls++;}});await assert.rejects(c.activate({...selected,content_transfer_confirmed:false},manifest),/consent/);await assert.rejects(c.activate({...selected,device_id:"foreign"},manifest),/scope/);assert.equal(calls,0);});
test("CSRF rotation during admission closes client without retry",async()=>{const document={...cookie};let calls=0;const c=createHttp({enabled:true,document,fetch:async()=>{calls++;document.cookie="__Host-zrotext_csrf=rotated";return new Response(null,{status:204});}});const input={...selected,phone_reader:new Uint8Array(32),archive_reader:new Uint8Array(32),signer:new Uint8Array(32),predecessor:new Uint8Array(32),public_point:new Uint8Array(65),signed_successor:manifest};await assert.rejects(c.enroll(input),/session changed/);await assert.rejects(c.enroll(input),/closed/);assert.equal(calls,1);});
test("successful enrollment explicitly requires independent verified reread",async()=>{const c=createHttp({enabled:true,document:cookie,fetch:async()=>new Response(null,{status:204})});const r=await c.enroll({...selected,phone_reader:new Uint8Array(32),archive_reader:new Uint8Array(32),signer:new Uint8Array(32),predecessor:new Uint8Array(32),public_point:new Uint8Array(65),signed_successor:manifest});assert.deepEqual(r,{status:"installed",requiresVerifiedReread:true});});
function dom(){const nodes=[];const document={createElement(tag){const n={tag,listeners:{},append(...children){this.children=children;},setAttribute(){},addEventListener(name,fn){this.listeners[name]=fn;},remove(){this.removed=true;}};nodes.push(n);return n;}};const host={append(n){this.child=n;}};let revoked=0;const URL={createObjectURL(){return "blob:synthetic";},revokeObjectURL(){revoked++;}};return {document,host,URL,nodes,revoked:()=>revoked};}
test("offline file accepts only exact proposal plus signature and tears down",async()=>{const d=dom(),unsigned=new Uint8Array(154),signature=new Uint8Array(64).fill(7),signed=new Uint8Array(218);signed.set(signature,154);const approval=requestFileSignature({...d,review:{unsigned}});const file=d.nodes.find(n=>n.tag==="input");file.files=[{size:218,arrayBuffer:async()=>signed.buffer}];await file.listeners.change();assert.deepEqual(await approval.result,signature);assert.equal(d.revoked(),1);assert.equal(d.host.child.removed,true);});
test("changed public proposal is refused before returning signature",async()=>{const d=dom(),approval=requestFileSignature({...d,review:{unsigned:new Uint8Array(154)}});const rejection=assert.rejects(approval.result,/differs/);const file=d.nodes.find(n=>n.tag==="input"),signed=new Uint8Array(218);signed[0]=1;file.files=[{size:218,arrayBuffer:async()=>signed.buffer}];await file.listeners.change();await rejection;assert.equal(d.revoked(),1);});
test("close during asynchronous file read never releases a signature",async()=>{const d=dom(),approval=requestFileSignature({...d,review:{unsigned:new Uint8Array(154)}});const rejection=assert.rejects(approval.result,/closed/);let release;const file=d.nodes.find(n=>n.tag==="input");file.files=[{size:218,arrayBuffer:()=>new Promise(r=>release=r)}];const pending=file.listeners.change();approval.close();release(new Uint8Array(218).buffer);await pending;await rejection;assert.equal(d.revoked(),1);});
test("pagehide closes both HTTP and pending file approval",async()=>{const listeners=[];const window={addEventListener(name,fn){if(name==="pagehide")listeners.push(fn);},removeEventListener(){}};const d=dom(),approval=requestFileSignature({...d,window,review:{unsigned:new Uint8Array(154)}}),rejection=assert.rejects(approval.result,/closed/);const c=createHttp({enabled:true,window,document:cookie,fetch:()=>{throw Error("must not request");}});for(const fn of listeners)fn();await rejection;await assert.rejects(c.bootstrap(selected),/closed/);assert.equal(d.revoked(),1);});
test("session abort closes public file controls and prevents stale signature",async()=>{const d=dom(),lifetime=new AbortController(),approval=requestFileSignature({...d,signal:lifetime.signal,review:{unsigned:new Uint8Array(154)}}),rejection=assert.rejects(approval.result,/closed/);lifetime.abort();await rejection;assert.equal(d.revoked(),1);assert.equal(d.host.child.removed,true);assert.throws(()=>requestFileSignature({...dom(),signal:lifetime.signal,review:{unsigned:new Uint8Array(154)}}),/closed/);});
test("oversized projection stream is cancelled at the byte bound",async()=>{let cancelled=false;const body=new ReadableStream({pull(controller){controller.enqueue(new Uint8Array(40000));},cancel(){cancelled=true;}});const c=createHttp({enabled:true,document:cookie,fetch:async()=>new Response(body,{headers:{"Content-Type":"application/json"}})});await assert.rejects(c.bootstrap(selected),/size refused/);assert.equal(cancelled,true);});
test("cleanup failure still removes controls and settles closed approval",async()=>{const d=dom();d.URL.revokeObjectURL=()=>{throw Error("Synthetic cleanup failure");};const approval=requestFileSignature({...d,review:{unsigned:new Uint8Array(154)}}),rejection=assert.rejects(approval.result,/closed/);approval.close();await rejection;assert.equal(d.host.child.removed,true);});

test("typed download preserves public wrapper and exact signed-file takeback",async()=>{const d=dom(),unsigned=new Uint8Array(154),typed=new Uint8Array(161);typed.set([90,84,67,70,1,0,154]);let blob;d.URL.createObjectURL=value=>{blob=value;return "blob:synthetic";};const approval=requestFileSignature({...d,review:{unsigned},typedProposal:typed});assert.deepEqual(new Uint8Array(await blob.arrayBuffer()),typed);assert.equal(d.nodes.find(n=>n.tag==="a").download,"conversation-role5-proposal.bin");const rejection=assert.rejects(approval.result,/closed/);approval.close();await rejection;typed[160]=1;assert.throws(()=>requestFileSignature({...dom(),review:{unsigned},typedProposal:typed}),/differs/);});
