// SPDX-License-Identifier: AGPL-3.0-only
"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),{webcrypto}=require("node:crypto");
if(!globalThis.crypto)Object.defineProperty(globalThis,"crypto",{value:webcrypto});
const bridge=require("./conversation-root-enrollment.js"),enc=new TextEncoder();
const ids={account:"11111111-1111-4111-8111-111111111111",user:"22222222-2222-4222-8222-222222222222",session:"33333333-3333-4333-8333-333333333333",backup:"44444444-4444-4444-8444-444444444444",challenge:"55555555-5555-4555-8555-555555555555"};
const bytes=s=>Uint8Array.from(s.replaceAll("-","").match(/../g),v=>parseInt(v,16)),cat=(...xs)=>Uint8Array.from(xs.flatMap(x=>[...x])),b64=b=>Buffer.from(b).toString("base64"),hash=async b=>new Uint8Array(await crypto.subtle.digest("SHA-256",b));
const file=b=>({size:b.length,arrayBuffer:async()=>Uint8Array.from(b).buffer});
async function fixture({enabled=true}={}){
 const origin="https://owner.invalid",o=enc.encode(origin),pair=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]),point=new Uint8Array(await crypto.subtle.exportKey("raw",pair.publicKey));
 const pin=new Uint8Array(94);pin.set([90,84,82,80,2]);pin.set(bytes(ids.account),5);new DataView(pin.buffer).setBigUint64(21,1n);pin.set(point,29);
 const fp=await hash(cat(enc.encode("ZTSE/root-pin/v2\0"),pin)),backup=new Uint8Array(236+o.length);backup.set([90,84,82,66,1,1]);backup.set(bytes(ids.backup),6);backup.set(bytes(ids.account),22);new DataView(backup.buffer).setBigUint64(38,1n);backup.set(fp,46);new DataView(backup.buffer).setUint16(78,o.length);backup.set(o,80);new DataView(backup.buffer).setUint32(184+o.length,48);
 const card=new Uint8Array(133+o.length);card.set([90,84,82,67,1]);new DataView(card.buffer).setUint16(5,o.length);card.set(o,7);card.set(pin,7+o.length);card.set(await hash(backup),101+o.length);
 const unsigned=new Uint8Array(151+o.length);unsigned.set([90,84,82,69,1]);for(const [id,at]of [[ids.account,5],[ids.user,21],[ids.session,37],[ids.challenge,53]])unsigned.set(bytes(id),at);unsigned.fill(7,69,101);unsigned.set(fp,101);new DataView(unsigned.buffer).setBigUint64(133,1000n);new DataView(unsigned.buffer).setBigUint64(141,61000n);new DataView(unsigned.buffer).setUint16(149,o.length);unsigned.set(o,151);
 const len=new Uint8Array(4);new DataView(len.buffer).setUint32(0,unsigned.length);const statement=cat(enc.encode("ZTSE/root-custody/v1\0"),len,unsigned,await hash(backup),await hash(card),fp);
 const N=BigInt("0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551");async function sign(b){const s=new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},pair.privateKey,b));let v=BigInt("0x"+Buffer.from(s.subarray(32)).toString("hex"));if(v>N/2n){v=N-v;s.set(bytes(v.toString(16).padStart(64,"0")),32);}return s;}
 const enrollment=await sign(cat(enc.encode("ZTSE/root-enroll/v1\0"),len,unsigned)),custody=await sign(statement),signatures=file(enc.encode(`Enrollment signature: ${Buffer.from(enrollment).toString("hex")}\nCustody signature: ${Buffer.from(custody).toString("hex")}\n`));
 let removals=0;let current={account_id:ids.account,user_id:ids.user,session_id:ids.session,role:"owner"},identity={enabled:true,publicationConsent:true,account_id:ids.account,backup_id:ids.backup,rootFingerprint:Buffer.from(fp).toString("hex"),origin},wall=2000,mono=0,completion=0,requests=[],hold=null,exportMutation=null;
 const children=[],events={},document={cookie:"__Host-zrotext_csrf=fixture",hidden:false,removeEventListener:()=>removals++,addEventListener:(e,f)=>events[e]=f,createElement:()=>({append(){},remove(){children.pop();}})},window={location:{origin},confirm:()=>true,removeEventListener:()=>removals++,addEventListener:(e,f)=>events[e]=f};
 const request=async(path,options)=>{requests.push([path,options]);if(hold)await hold(path,options);let value;if(path==="/v1/auth/session")value=current;else if(path.endsWith("challenge"))value={root_pin_b64:b64(pin),unsigned_enrollment_b64:b64(unsigned),custody_statement_b64:b64(statement)};else if(options.method==="POST"){completion++;value={account_id:ids.account,challenge_id:ids.challenge,root_pin_b64:b64(pin),root_fingerprint_b64:b64(fp),completed_ms:wall};}else{value={account_id:ids.account,challenge_id:ids.challenge,backup_id:ids.backup,generation:1,root_pin_b64:b64(pin),root_fingerprint_b64:b64(fp),encrypted_backup_b64:b64(backup),public_card_b64:b64(card),unsigned_enrollment_b64:b64(unsigned),custody_signature_b64:b64(custody)};if(exportMutation)exportMutation(value);}return new Response(JSON.stringify(value),{headers:{"Content-Type":"application/json"}});};
 const value=bridge.create({enabled,document,window,host:{append:p=>children.push(p)},readIdentity:()=>identity,fetch:request,URL:{createObjectURL:()=>"blob:fixture",revokeObjectURL(){}},now:()=>wall,monotonic:()=>mono});
 return {value,backup:file(backup),card:file(card),signatures,children,events,document,window,requests,get completion(){return completion;},get removals(){return removals;},setIdentity:f=>f(identity),setSession:f=>f(current),setTime:(w,m)=>{wall=w;mono=m;},hold:f=>hold=f,mutateExport:f=>exportMutation=f};
}
test("existing custody signatures complete only after authoritative root/session reread",async()=>{const f=await fixture();await f.value.begin(f.backup,f.card);assert.equal(f.children.length,1);const r=await f.value.complete(f.signatures,"fixture-factor");assert.equal(r.rootEnrolled,true);assert.deepEqual(Object.keys(r).sort(),["account_id","rootEnrolled","rootFingerprint"]);assert.equal(f.completion,1);assert.equal(f.children.length,0);await assert.rejects(f.value.complete(f.signatures,"fixture-factor"));});
test("disabled bridge performs zero requests",async()=>{const f=await fixture({enabled:false});await assert.rejects(f.value.begin(f.backup,f.card));assert.equal(f.requests.length,0);});
for(const mode of ["close","session","identity","expiry","decline","tamper"])test(mode+" refuses completion",async()=>{const f=await fixture();try{await f.value.begin(f.backup,f.card);if(mode==="close")f.value.close();if(mode==="session")f.setSession(v=>v.session_id=ids.backup);if(mode==="identity")f.setIdentity(v=>v.backup_id=ids.session);if(mode==="expiry")f.setTime(61000,59000);if(mode==="decline")f.window.confirm=()=>false;const input=mode==="tamper"?file(enc.encode("Enrollment signature: "+"01".repeat(64)+"\nCustody signature: "+"01".repeat(64)+"\n")):f.signatures;await assert.rejects(f.value.complete(input,"fixture-factor"));assert.equal(f.completion,0);}finally{f.value.close();}});
test("held signature file close is zero completion",async()=>{const f=await fixture();await f.value.begin(f.backup,f.card);let release;const held={size:f.signatures.size,arrayBuffer:()=>new Promise(r=>release=r)};const pending=f.value.complete(held,"fixture-factor");f.value.close();release(await f.signatures.arrayBuffer());await assert.rejects(pending);assert.equal(f.completion,0);});
test("held challenge response abort cannot publish download",async()=>{const f=await fixture();let release;f.hold((path)=>path.endsWith("challenge")?new Promise(r=>release=r):undefined);const p=f.value.begin(f.backup,f.card);while(!release)await new Promise(r=>setImmediate(r));f.value.close();release();await assert.rejects(p);assert.equal(f.children.length,0);assert.equal(f.completion,0);});
test("accepted response with mismatched reread never claims root authority",async()=>{const f=await fixture();await f.value.begin(f.backup,f.card);f.mutateExport(v=>v.backup_id=ids.session);await assert.rejects(f.value.complete(f.signatures,"fixture-factor"),/outcome unknown/);assert.equal(f.completion,1);});
test("backup byte mutation is refused before challenge",async()=>{const f=await fixture(),bad=new Uint8Array(await f.backup.arrayBuffer());bad[bad.length-1]^=1;await assert.rejects(f.value.begin(file(bad),f.card));assert.equal(f.requests.filter(([p])=>p.endsWith("challenge")).length,0);});


test("close removes visibility and page lifecycle listeners",async()=>{const f=await fixture();await f.value.begin(f.backup,f.card);f.value.close();assert.equal(f.removals,2);assert.equal(f.children.length,0);});
test("HTTP failure cannot publish challenge or completion",async()=>{const f=await fixture();f.hold(()=>{throw Error("Fixture owner endpoint unavailable");});await assert.rejects(f.value.begin(f.backup,f.card));assert.equal(f.completion,0);assert.equal(f.children.length,0);});
test("root bridge imports public verification key only and never browser recovery or storage",()=>{const source=require("node:fs").readFileSync(require.resolve("./conversation-root-enrollment.js"),"utf8");assert.ok(source.includes('importKey("raw",pin.subarray(29)'));assert.ok(!/localStorage|sessionStorage|indexedDB|generateKey|decrypt|deriveKey|deriveBits|privateKey/.test(source));});
