// SPDX-License-Identifier: AGPL-3.0-only
"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),{create}=require("./conversation-owner-setup.js"),Bootstrap=require("./conversation-bootstrap.js");
const hex=b=>Buffer.from(b).toString("hex"),uuid=b=>hex(b).replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,"$1-$2-$3-$4-$5"),b64=b=>Buffer.from(b).toString("base64");
async function fixture({selectedReaders=false,readerScope=8}={}){
 const {archiveFixture}=await import("../../sdk/typescript/test/conversation-archive-fixture.mjs"),f=await archiveFixture(),sdk={...await import("../../sdk/typescript/dist/draft02-manifest.js"),...await import("../../sdk/typescript/dist/conversation-refresh-proposal.js"),...await import("../../sdk/typescript/dist/conversation-activation-proposal.js"),...await import("../../sdk/typescript/dist/conversation-reader.js"),...await import("../../sdk/typescript/dist/original-reply-selection.js")},{unlockExistingArchive02}=await import("../../sdk/typescript/dist/conversation-archive-custody.js"),{signFixtureSuccessor02}=await import("../../sdk/typescript/test/conversation-refresh-fixture.mjs");
 if(selectedReaders){
  const {originalReplyFixture}=await import("../../sdk/typescript/test/original-reply-fixture.mjs"),original=await originalReplyFixture(),header=f.predecessor.bytes.slice(0,151);header[150]=5;
  const selectedRecord=original.manifest.bytes.slice(300,449);selectedRecord[131]=readerScope;const unsigned=Uint8Array.from(Buffer.concat([header,f.predecessor.bytes.subarray(151,449),selectedRecord,f.predecessor.bytes.subarray(449,-64)]));
  const pin=new Uint8Array(94);pin.set([90,84,82,80,2]);pin.set(f.options.binding.account,5);new DataView(pin.buffer).setBigUint64(21,1n);pin.set(f.predecessor.rootPoint,29);
  const trust={...await sdk.enrollRootPin02(pin,f.comparedRootFingerprint),version:6n,digest:f.predecessor.bytes.slice(53,85)};
  f.predecessor=await sdk.verifyManifest02(await signFixtureSuccessor02(f,unsigned),trust,f.nowMs);
 }
 const b=f.options.binding,selection={enabled:true,contentConsent:true,sessionConsent:true,account_id:uuid(b.account),device_id:uuid(b.device),line_id:uuid(b.line),binding_generation:1,peer:b.peer,rootFingerprint:hex(f.comparedRootFingerprint),manifestVersion:f.predecessor.version.toString(),manifestDigest:hex(f.predecessor.digest)},state={manifest:f.predecessor,live:true,phase:"active",posts:[],decisions:[],signed:0,unlocks:0,handoffs:[]};
 if(selectedReaders){const reader=f.predecessor.keys.find(k=>k.role===3);selection.integrationReadersText=uuid(new Uint8Array(16).fill(8))+", "+uuid(new Uint8Array(16).fill(9))+", "+hex(reader.keyId);selection.integrationTransferConsent=true;}
 const pin=new Uint8Array(94);pin.set([90,84,82,80,2]);pin.set(b.account,5);new DataView(pin.buffer).setBigUint64(21,1n);pin.set(f.predecessor.rootPoint,29);
 function projection(){const m=state.manifest,record=role=>m.keys.find(k=>k.role===role);return {v:1,trust_candidate:true,owner_session_live:true,consent_live:state.live,account_id:selection.account_id,session_id:state.session||uuid(b.session),...{device_id:selection.device_id,line_id:selection.line_id,binding_generation:"1",peer:b.peer},phase:state.phase,interval_id:uuid(b.interval),server_now_ms:f.nowMs.toString(),root_pin:b64(pin),root_fingerprint:b64(f.comparedRootFingerprint),current_manifest:b64(m.bytes),manifest_digest:b64(m.digest),manifest_version:m.version.toString(),trust_generation:"1",...Object.fromEntries([[1,"phone_reader"],[2,"archive_reader"],[4,"phone_signer"]].flatMap(([role,name])=>[[name+"_id",b64(record(role).keyId)],[name+"_point",b64(record(role).point)]]))};}
 const document={cookie:"__Host-zrotext_csrf=synthetic-csrf",addEventListener(){},getElementById:id=>id==="review-body"?{textContent:"Synthetic ordinary reply"}:{hidden:false}},window={location:{origin:f.origin},addEventListener(){},confirm:message=>{state.decisions.push(message);return true;}},fetch=async(path,options)=>{state.posts.push({path,options});if(path.endsWith("/selection")){await state.holdSelection?.();return Response.json(state.selectionProof);}if(path.endsWith("/bootstrap")){if(state.phase==="pending")state.afterActivation?.();return new Response(JSON.stringify(projection()),{status:200,headers:{"Content-Type":"application/json"}});}if(path.endsWith("/activation")){if(state.holdActivation)await state.holdActivation();state.phase="pending";const payload=JSON.parse(options.body),next=await sdk.verifyManifest02(new Uint8Array(Buffer.from(payload.next_manifest,"base64")),sdk.verifiedManifestTrust02(state.manifest,f.nowMs),f.nowMs);state.original=await originalStatement(f,state.manifest,next,payload.integration_readers??[]);state.mutateOriginal?.(state.original);return new Response(state.original,{status:200,headers:{"Content-Type":"application/vnd.zrotext.conversation-statement.v"+(payload.integration_readers?.length?2:1)}});}if(path.endsWith("/enrollment")){const payload=JSON.parse(options.body);assert.equal(payload.peer,b.peer);assert.equal(payload.predecessor,b64(state.manifest.digest));state.manifest=await sdk.verifyManifest02(new Uint8Array(Buffer.from(payload.signed_successor,"base64")),sdk.verifiedManifestTrust02(state.manifest,f.nowMs),f.nowMs);return new Response(null,{status:204});}throw Error("Unexpected fixture endpoint");};
 const bootstrap={...Bootstrap,requestPhoneFile:({kind,content,signal})=>{if(signal.aborted)throw Error("closed");const file={kind,content:Uint8Array.from(content),closed:false,close(){this.closed=true;}};state.handoffs.push(file);return file;},requestArchiveUnlock:({context,signal})=>{state.unlocks++;return {result:unlockExistingArchive02({...f.options,...context,signal,consumeUnlockDecision:async()=>{}})};},requestFileSignature:({review,typedProposal})=>{state.signed++;assert.ok(typedProposal[3]===70||typedProposal[3]===65);assert.deepEqual(Array.from(typedProposal.subarray(0,3)),[90,84,67]);return {result:signFixtureSuccessor02(f,review.unsigned).then(bytes=>bytes.slice(-64))};}};
 const setup=create({enabled:true,document,window,host:{},readSelection:()=>selection,bootstrap,loadSdk:async()=>sdk,fetch});return {f,state,selection,setup,projection,document,window,fetch,sdk,bootstrap};
}
test("ordinary setup performs no network or SDK/key work before explicit enabled decisions",async()=>{let calls=0;const setup=create({readSelection:()=>{calls++;},loadSdk:async()=>{calls++;}});await assert.rejects(setup.custodyOptions(),/unavailable/);assert.equal(calls,0);});
test("selected activation binds the exact separately approved reader list into the phone handoff",async()=>{
 const f=await fixture({selectedReaders:true});f.state.phase="unprepared";
 try{const original=await f.setup.activate();assert.equal(original[4],2);assert.deepEqual(f.state.handoffs[0].content.slice(7,7+original.length),original);
 const sent=JSON.parse(f.state.posts.find(p=>p.path.endsWith("/activation")).options.body);
 assert.equal(sent.integration_readers.length,1);assert.equal(sent.integration_transfer_confirmed,true);
 assert.deepEqual(sent.integration_readers[0].key_id,Array.from(f.state.manifest.keys.find(k=>k.role===3).keyId));
 assert.ok(f.state.decisions.some(v=>v.includes("customer-controlled readers")&&v.includes(hex(f.state.manifest.keys.find(k=>k.role===3).keyId))));
 }finally{f.setup.close();}
});
test("phone statement reader substitution and missing separate consent cannot publish setup",async()=>{
 for(const boundary of ["consent","statement"]){const f=await fixture({selectedReaders:true});f.state.phase="unprepared";
 if(boundary==="consent")f.selection.integrationTransferConsent=false;else f.state.mutateOriginal=bytes=>{bytes[bytes.length-1]^=1;};
 try{await assert.rejects(f.setup.activate());assert.equal(f.state.handoffs.length,0);if(boundary==="consent")assert.equal(f.state.posts.length,0);}finally{f.setup.close();}}
});
test("selected inbound transfer accepts an existing read-both manifest key with separate inbound consent",async()=>{
 const f=await fixture({selectedReaders:true,readerScope:12});f.state.phase="unprepared";
 try{assert.equal(f.state.manifest.keys.find(k=>k.role===3).scope,12);const original=await f.setup.activate();assert.equal(original[4],2);assert.equal(f.state.handoffs.length,1);assert.equal(JSON.parse(f.state.posts.find(p=>p.path.endsWith("/activation")).options.body).integration_readers.length,1);}finally{f.setup.close();}
});
test("reader list mutation during activation refuses the pending phone artifact",async()=>{
 const f=await fixture({selectedReaders:true});f.state.phase="unprepared";f.state.holdActivation=async()=>{f.selection.integrationReadersText=f.selection.integrationReadersText.replace(/^08080808/,"09090909");};
 try{await assert.rejects(f.setup.activate(),/selection changed/);assert.equal(f.state.handoffs.length,0);}finally{f.setup.close();}
});
async function ownerSelectionFixture(){
 const f=await fixture({selectedReaders:true}),readers=Bootstrap.parseReaderSelections(f.selection.integrationReadersText,true),m=f.state.manifest;
 const statement=await originalStatement(f.f,{...m,version:6n,digest:m.bytes.slice(53,85)},m,readers),point=m.keys.find(k=>k.role===4).point,scalar=new Uint8Array(32);scalar[31]=4;
 const key=await crypto.subtle.importKey("jwk",{kty:"EC",crv:"P-256",x:Buffer.from(point.slice(1,33)).toString("base64url"),y:Buffer.from(point.slice(33)).toString("base64url"),d:Buffer.from(scalar).toString("base64url")},{name:"ECDSA",namedCurve:"P-256"},false,["sign"]);scalar.fill(0);
 const sign=async name=>{const domain=new TextEncoder().encode(`zrotext/conversation/${name}/v2\0`),input=new Uint8Array(domain.length+4+statement.length);input.set(domain);new DataView(input.buffer).setUint32(domain.length,statement.length);input.set(statement,domain.length+4);return f.sdk.canonicalSignature02(new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},key,input)));};
 f.state.selectionProof={v:1,statement:b64(statement),approval_signature:b64(await sign("approve")),installation_signature:b64(await sign("install")),activation_manifest_version:m.version.toString(),activation_manifest_digest:b64(m.digest),accepted_at_ms:f.f.nowMs.toString()};
 const {originalReplyFixture}=await import("../../sdk/typescript/test/original-reply-fixture.mjs");f.envelope=(await originalReplyFixture()).envelope;
 return f;
}
test("owner archive callback verifies phone approval and installation using locally accepted activation history",async()=>{
 const f=await ownerSelectionFixture();try{const options=await f.setup.custodyOptions(),proof=await options.readSelection(f.envelope);assert.equal(proof.readers.length,1);assert.deepEqual(proof.archiveReader,f.f.options.binding.archiveReader);assert.deepEqual(proof.interval,f.f.options.binding.interval);assert.equal(f.state.posts.filter(p=>p.path.endsWith("/selection")).length,1);}finally{f.setup.close();}
});
test("owner archive callback refuses unaccepted history, forged signatures and approval after the event",async()=>{
 for(const mutation of ["history","signature","time"]){const f=await ownerSelectionFixture();
 if(mutation==="history")f.state.selectionProof.activation_manifest_digest=b64(new Uint8Array(32).fill(9));
 if(mutation==="signature")f.state.selectionProof.approval_signature=b64(new Uint8Array(64).fill(9));
 if(mutation==="time")f.state.selectionProof.accepted_at_ms=(f.f.nowMs+1n).toString();
 try{const options=await f.setup.custodyOptions();await assert.rejects(options.readSelection(f.envelope));}finally{f.setup.close();}}
});
test("owner authority withdrawal while selection proof is read cannot release an archive proof",async()=>{
 const f=await ownerSelectionFixture();f.state.holdSelection=async()=>{f.state.live=false;};try{const options=await f.setup.custodyOptions();await assert.rejects(options.readSelection(f.envelope),/approval/);}finally{f.setup.close();}
});
test("ordinary HTTP projection composes real SDK archive lease, offline role5 enrollment and exact signed reply",async()=>{const f=await fixture(),{prepareConversationCustody02}=await import("../../sdk/typescript/dist/conversation-custody.js");assert.equal(f.state.posts.length,0);const options=await f.setup.custodyOptions(),custody=await prepareConversationCustody02(options);try{const authority=await custody.authority();assert.equal(authority.scope.account,f.selection.account_id);const review=await custody.prepare(authority.scope,"Synthetic ordinary reply"),packet=await custody.signReviewed(review,authority.scope,"Synthetic ordinary reply");assert.ok(packet.envelope&&packet.confirmation&&packet.signature);assert.equal(f.state.unlocks,1);assert.equal(f.state.signed,1);assert.equal(f.state.posts.filter(v=>v.path.endsWith("/enrollment")).length,1);assert.ok(f.state.decisions.some(v=>v.includes("interval")));}finally{custody.close();f.setup.close();}});
test("downloaded account/fingerprint/checkpoint cannot replace independent expected authority",async()=>{for(const field of ["account_id","rootFingerprint","manifestVersion","manifestDigest"]){const f=await fixture();f.selection[field]=field==="account_id"?uuid(new Uint8Array(16).fill(9)):field==="manifestVersion"?"9":"00".repeat(32);await assert.rejects(f.setup.custodyOptions());assert.equal(f.state.unlocks+f.state.signed,0);f.setup.close();}});
test("missing content/session consent and pending phone approval cannot unlock or enroll",async()=>{for(const field of ["enabled","contentConsent","sessionConsent","pending"]){const f=await fixture();if(field==="pending")f.state.phase="pending";else f.selection[field]=false;await assert.rejects(f.setup.custodyOptions());assert.equal(f.state.unlocks+f.state.signed,0);f.setup.close();}});
test("archive loss closes setup and isolates presentation listeners",async()=>{const f=await fixture(),options=await f.setup.custodyOptions();let cleared=0;f.setup.onClose(()=>{throw Error("Synthetic UI close failure");});f.setup.onClose(()=>cleared++);options.archiveLease.close();assert.equal(cleared,1);await assert.rejects(options.readCurrent(),/closed/);});
test("session/selected scope mutation before signing fails closed",async()=>{const f=await fixture(),options=await f.setup.custodyOptions();try{f.selection.peer="+13";await assert.rejects(options.consumeOwnerDecision(f.f.review),/selection changed/);}finally{f.setup.close();}});

test("activation submits only existing signed successor with preserved records and separate consent",async()=>{const f=await fixture(),{signFixtureSuccessor02}=await import("../../sdk/typescript/test/conversation-refresh-fixture.mjs");f.state.phase="unprepared";const unsigned=Uint8Array.from(f.state.manifest.bytes.subarray(0,-64)),v=new DataView(unsigned.buffer);v.setBigUint64(29,f.state.manifest.version+1n);unsigned.set(f.state.manifest.digest,53);const signed=await signFixtureSuccessor02(f.f,unsigned),original=await f.setup.activate({size:signed.length,arrayBuffer:async()=>signed.buffer});assert.deepEqual(original,f.state.original);assert.ok(original.length>=380&&original.length<=1024);assert.equal(f.state.posts.filter(v=>v.path.endsWith("/activation")).length,1);assert.equal(f.state.unlocks+f.state.signed,0);assert.ok(f.state.decisions.some(v=>v.includes("Phone approval remains required")));await assert.rejects(f.setup.custodyOptions(),/phone approval/);f.setup.close();});
test("activation rejects role insertion or archive mutation before any activation POST",async()=>{for(const change of ["insert","archive"]){const f=await fixture(),{signFixtureSuccessor02}=await import("../../sdk/typescript/test/conversation-refresh-fixture.mjs");f.state.phase="unprepared";const unsigned=change==="insert"?Uint8Array.from(f.f.review.unsigned):Uint8Array.from(f.state.manifest.bytes.subarray(0,-64));if(change==="archive"){new DataView(unsigned.buffer).setBigUint64(29,f.state.manifest.version+1n);unsigned.set(f.state.manifest.digest,53);for(let at=151;at<unsigned.length;at+=149)if(unsigned[at]===2)new DataView(unsigned.buffer).setBigUint64(at+140,f.nowMs||3000n);}const signed=await signFixtureSuccessor02(f.f,unsigned);await assert.rejects(f.setup.activate({size:signed.length,arrayBuffer:async()=>signed.buffer}));assert.equal(f.state.posts.filter(v=>v.path.endsWith("/activation")).length,0);f.setup.close();}});
test("owner session substitution after archive unlock closes its memory lease",async()=>{const f=await fixture(),options=await f.setup.custodyOptions();f.state.session=uuid(new Uint8Array(16).fill(9));await assert.rejects(options.readCurrent(),/session changed/);await assert.rejects(options.archiveLease.withKey(options.binding,async()=>{}),/unavailable/);});
test("clear aborts pending archive setup and closes a late lease before publication",async()=>{const f=await fixture(),controller=new AbortController();let release,entered;const started=new Promise(resolve=>entered=resolve);f.bootstrap.requestArchiveUnlock=()=>({result:new Promise(resolve=>{release=resolve;entered();})});const pending=f.setup.custodyOptions({signal:controller.signal});await started;controller.abort();let closes=0;release({close(){closes++;},onClose(){throw Error("Late lease must not subscribe");}});await assert.rejects(pending,/closed/);assert.equal(closes,1);assert.equal(f.state.signed,0);});
test("already aborted setup performs no HTTP or archive/key work",async()=>{const f=await fixture(),controller=new AbortController();controller.abort();await assert.rejects(f.setup.custodyOptions({signal:controller.signal}),/closed/);assert.equal(f.state.posts.length+f.state.unlocks+f.state.signed,0);});
test("HTTP origin does not import SDK or create keys",async()=>{const f=await fixture();f.window.location.origin="http://owner.invalid";await assert.rejects(f.setup.custodyOptions(),/Secure/);assert.equal(f.state.posts.length+f.state.unlocks+f.state.signed,0);f.setup.close();});
async function activationArtifact(f){const {signFixtureSuccessor02}=await import("../../sdk/typescript/test/conversation-refresh-fixture.mjs"),unsigned=Uint8Array.from(f.state.manifest.bytes.subarray(0,-64));new DataView(unsigned.buffer).setBigUint64(29,f.state.manifest.version+1n);unsigned.set(f.state.manifest.digest,53);return signFixtureSuccessor02(f.f,unsigned);}
for(const boundary of ["file","HTTP"])test(`activation abort at held ${boundary} boundary blocks late success`,async()=>{const f=await fixture(),signed=await activationArtifact(f),controller=new AbortController();f.state.phase="unprepared";let release,entered;const held=new Promise(resolve=>entered=resolve),wait=()=>new Promise(resolve=>{release=resolve;entered();});if(boundary==="HTTP")f.state.holdActivation=wait;const pending=f.setup.activate({size:signed.length,arrayBuffer:async()=>{if(boundary==="file")await wait();return signed.buffer;}},{signal:controller.signal});await held;controller.abort();release();await assert.rejects(pending,/closed/);assert.equal(f.state.posts.filter(v=>v.path.endsWith("/activation")).length,boundary==="file"?0:1);assert.equal(f.state.unlocks+f.state.signed,0);assert.equal(f.state.handoffs.length,0);});
test("parallel activation and custody ceremonies cannot overwrite selected authority",async()=>{const f=await fixture(),signed=await activationArtifact(f);f.state.phase="unprepared";let release,entered;const held=new Promise(resolve=>entered=resolve),pending=f.setup.activate({size:signed.length,arrayBuffer:()=>new Promise(resolve=>{release=()=>resolve(signed.buffer);entered();})});await held;await assert.rejects(f.setup.custodyOptions(),/already active/);release();await pending;f.setup.close();});

test("ordinary explicit activation builds typed public proposal and consumes existing offline file signature before HTTP",async()=>{const f=await fixture();f.state.phase="unprepared";await f.setup.activate();assert.equal(f.state.signed,1);assert.equal(f.state.unlocks,0);assert.equal(f.state.posts.filter(v=>v.path.endsWith("/activation")).length,1);assert.ok(f.state.decisions.some(v=>v.includes("does not sign consent")));f.setup.close();});

async function originalStatement(f,before,next,readers=[]){const b=f.options.binding,parts=[],put=x=>parts.push(Uint8Array.from(x)),num=n=>{const x=new Uint8Array(8);new DataView(x.buffer).setBigUint64(0,n);put(x);},text=s=>{const x=new TextEncoder().encode(s);put([x.length]);put(x);};put([90,84,67,65,readers.length?2:1]);put(b.account);put(b.device);put(b.line);num(b.generation);put(b.interval);put(new Uint8Array(16).fill(6));put(b.session);put(new Uint8Array(32).fill(7));num(f.nowMs+200000n);text(b.peer);text("conversation-content-v1");put(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(readers.length?"With your approval, ZROtext transfers encrypted SMS content for this selected phone line and conversation to your paired browser and the explicitly listed customer-controlled readers. Stop closes new capture and transfer; retained encrypted content is deleted separately.":"With your approval, ZROtext transfers encrypted SMS content for this selected phone line and conversation to your paired browser. Stop closes new capture and transfer; retained encrypted content is deleted separately."))));put(b.archiveReader);put(before.keys.find(k=>k.role===4).keyId);num(next.generation);num(before.version);put(before.digest);num(next.version);put(next.digest);num(1n);num(1n);text("fixture");text("fixture");if(readers.length){put([readers.length]);for(const r of readers){put(Buffer.from(r.connector_id.replaceAll("-",""),"hex"));put(Buffer.from(r.read_grant_id.replaceAll("-",""),"hex"));put(r.key_id);}}const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let at=0;for(const p of parts){out.set(p,at);at+=p.length;}return out;}
test("setup handoff copies exact original, verified archive point and existing phone reader ID",async()=>{const f=await fixture();f.state.phase="unprepared";const original=await f.setup.activate(),file=f.state.handoffs[0],n=new DataView(file.content.buffer).getUint16(5);assert.equal(file.kind,"setup");assert.deepEqual(file.content.slice(0,5),Uint8Array.of(90,84,80,83,1));assert.equal(file.content.length,7+n+97);assert.deepEqual(file.content.slice(7,7+n),original);assert.deepEqual(file.content.slice(7+n,7+n+65),f.state.manifest.keys.find(k=>k.role===2).point);assert.deepEqual(file.content.slice(-32),f.state.manifest.keys.find(k=>k.role===1).keyId);f.setup.close();assert.equal(file.closed,true);});
for(const offset of [5,21,37,45,93,149,202])test(`foreign statement byte ${offset} cannot publish phone setup`,async()=>{const f=await fixture();f.state.phase="unprepared";f.state.mutateOriginal=bytes=>bytes[offset]^=1;await assert.rejects(f.setup.activate());assert.equal(f.state.handoffs.length,0);f.setup.close();});
test("reply handoff contains independently verified installed manifest and exact session signer",async()=>{const f=await fixture(),{prepareConversationCustody02}=await import("../../sdk/typescript/dist/conversation-custody.js"),custody=await prepareConversationCustody02(await f.setup.custodyOptions());try{const file=f.state.handoffs[0],n=new DataView(file.content.buffer).getUint16(5),signer=f.state.manifest.keys.find(k=>k.role===5);assert.equal(file.kind,"reply");assert.deepEqual(file.content.slice(0,5),Uint8Array.of(90,84,80,82,1));assert.equal(file.content.length,7+n+32);assert.deepEqual(file.content.slice(7,7+n),f.state.manifest.bytes);assert.deepEqual(file.content.slice(-32),signer.keyId);}finally{custody.close();f.setup.close();}assert.equal(f.state.handoffs[0].closed,true);});

test("owner session loss on post-activation projection blocks public setup publication",async()=>{const f=await fixture();f.state.phase="unprepared";f.state.afterActivation=()=>f.state.session=uuid(new Uint8Array(16).fill(9));await assert.rejects(f.setup.activate(),/session changed/);assert.equal(f.state.handoffs.length,0);f.setup.close();});
test("selection mutation while public download is being published closes candidate",async()=>{const f=await fixture();f.state.phase="unprepared";const publish=f.bootstrap.requestPhoneFile;f.bootstrap.requestPhoneFile=options=>{const file=publish(options);f.selection.peer="+13";return file;};await assert.rejects(f.setup.activate(),/selection changed/);assert.equal(f.state.handoffs.length,1);assert.equal(f.state.handoffs[0].closed,true);f.setup.close();});

test("phone setup download closes automatically at statement expiry",async()=>{const f=await fixture();f.state.phase="unprepared";f.state.mutateOriginal=bytes=>new DataView(bytes.buffer).setBigUint64(141,f.f.nowMs+100n);await f.setup.activate();const file=f.state.handoffs[0];assert.equal(file.closed,false);await new Promise(resolve=>setTimeout(resolve,150));assert.equal(file.closed,true);f.setup.close();});

test("actual SDK enrollment displays exact manual public reply text and lease loss erases it",async()=>{const f=await fixture(),nodes=[],document={createElement(tag){const node={tag,append(...children){this.children=children;},setAttribute(){},remove(){this.removed=true;}};nodes.push(node);return node;}},host={append(node){this.child=node;}};f.bootstrap.requestPhoneFile=options=>Bootstrap.requestPhoneFile({...options,document,host,URL:{createObjectURL(){return "blob:synthetic";},revokeObjectURL(){}}});const {prepareConversationCustody02}=await import("../../sdk/typescript/dist/conversation-custody.js"),custody=await prepareConversationCustody02(await f.setup.custodyOptions());try{const field=nodes.find(n=>n.tag==="textarea"),bytes=new Uint8Array(Buffer.from(field.value,"base64")),length=new DataView(bytes.buffer).getUint16(5);assert.deepEqual(bytes.slice(0,5),Uint8Array.of(90,84,80,82,1));assert.deepEqual(bytes.slice(7,7+length),f.state.manifest.bytes);assert.deepEqual(bytes.slice(-32),f.state.manifest.keys.find(k=>k.role===5).keyId);custody.close();assert.equal(field.value,"");assert.equal(host.child.removed,true);}finally{custody.close();f.setup.close();}});
